### ISSUE TITLE
Build out infographics section of Airway

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#100]
The intention for this section is for the user to be able to slide and zoom into the various infographics related to Airway. This would include various documents from source documents:

Page 2 https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/SAS%20COVID%2019%20infographics%201%202.pdf

https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/COVID-19_Emergency_Intubation_Checklist.png

https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/WH_ANAES_COGAID_ExtubationETTDisconnectionV1.0.pdf

@galtaforce @benblackman @fabiendade
Please feel free to comment if I have missed anything.

Otherwise it can be assigned @Western-Health-Covid19-Collaboration/designers i

**Comment by greggmiller** [comment]
This is a duplicate issue of #37 my mistake @lukesleeman @marcedwards Should we close one?

**Comment by lukesleeman** [comment]
Yeah, thanks for flagging that.  I'll close 👍
