### ISSUE TITLE
Build out extubation screen

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#101]
Please refer document:
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/WH_Extubation_infographic.pdf

The intention would be for the user to have step by step guide to follow for extubating a patient.
This document will require an anaesthetist to review first to order it sequentially.

Alternatively, this could be breaking down the infographic
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/Extubation_Infographic.pdf

@Western-Health-Covid19-Collaboration/medical  @fabiendade anyone keen?
Otherwise, I will try to get to over the next couple of days.

**Comment by greggmiller** [comment]
@A-Gynther has kindly agreed to look at this at some point over next few days.

**Comment by lukesleeman** [comment]
Just heard from @greggmiller .  For V1 of the app, we can just include the `Extubation_Infographic.pdf` on this screen as a standard infographic screen.  No need for anything fancy

If anybody is wondering it looks like this:

![image](https://user-images.githubusercontent.com/902252/77839478-c9b98d00-71c8-11ea-81da-53fec71e9486.png)

**Comment by lukesleeman** [comment]
Annnnnd actually, this is already covered under issue #112 .  I'm going to close this issue down now.  We can re-open this issue down the track once we need to design a nicer extubation screen
