### ISSUE TITLE
On Android it's currently possible to back out of disclaimer 

### ISSUE THREAD

**Issue by maks** [Western-Health-Covid19-Collaboration/wh_covid19_app#103]
If you press the back button, you nca back out of the disclaimer without accepting it!

**Comment by maks** [comment]
Whoever fixes this, please add tests for the fix. :pray:

**Comment by joshcase** [comment]
I'll tackle this

**Comment by workerbee22** [comment]
Just use the following when pushing the Disclaimer button. So replace 
`Navigator.pushNamed'' with `Navigator.pushReplacement'

**Comment by joshcase** [comment]
Looks like we are already using Navigator.pushReplacementNamed, I will do a bit more digging
```
Future<void> _checkDisclaimerFirstView() async {
    final prefs = await SharedPreferences.getInstance();
    final disclaimerFirstView = prefs.getBool('disclaimer_first_view') ?? false;

    if (disclaimerFirstView) {
      await Navigator.of(context).pushReplacementNamed(Routes.home);
    } else {
      await Navigator.of(context).pushReplacementNamed(Routes.disclaimer);
    }
  }
```

**Comment by workerbee22** [comment]
Check the build method for `_DisclaimerViewState` it has a `.pushNamed` in the `_agreeButton` Container.

**Comment by workerbee22** [comment]
So need to update the route used when the button is pressed. Not the route that gets to the home or disclaimer screen.

**Comment by joshcase** [comment]
> So need to update the route used when the button is pressed. Not the route that gets to the home or disclaimer screen.

I can't see how that's related at this stage, as pressing the back button doesn't seem to call the onPressed function for the button.

Resolved the issue by wrapping the Scaffold in a WillPopScope. Writing the tests now and will send PR soon.

**Comment by workerbee22** [comment]
So I guess we need to test. When on Disclaimer, what happens when press Back? But also, if you accept the Disclaimer by pressing the button and then end up in the home screen, what happens when you press Back again, and again and again?

**Comment by workerbee22** [comment]
Looks like BOTH are an issue. Just tested:

- Back button on Disclaimer ends up at Home screen, so effectively skips the Disclaimer acceptance. So not good.
- If you accept the Disclaimer and end up on Home, then push Back it does do back to the Disclaimer screen (but does show you have accepted), but it should not go back to Disclaimer screen at all. So also not good.

Thus we should also change the `_DisclaimerViewState` build from a `.pushNamed` in the `_agreeButton` Container to `Navigator.pushReplacement` as well.

**Comment by joshcase** [comment]
Fixed in #106 - did not provide testing as I couldn't work out how to simulate the Android back button in any testing environment

**Comment by lukesleeman** [comment]
@joshcase I just tested this on my Android phone.  Thanks for your work so far!

There are some minor issues I've seen around the back button behaviour:
- On android when you first launch the app you should be able to click the back button, and just have the app close.  Basically if somebody opens it for the first time, decides they don't like the disclaimer, they should be able to press back and get back to their homescreen

- You can access the disclaimer at any time from the information screen.  If you go in and look at the disclaimer you can now no longer get back out.

If you want to submit some further PRs that would be great.  Otherwise let us know and I can chase down another flutter dev to look at it.

**Comment by workerbee22** [comment]
We should probably close this issue once solved, but moving discussion over to [issue 47](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/47).

Having deeper look at Disclaimer requirement and behaviour in [issue 47](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/47) and discussing fixes there, including this bug.

**Comment by lukesleeman** [comment]
Ok, I'm closing this, it can just be tracked as part of issue #47
