### ISSUE TITLE
Build re-usable infographic widget

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#111]
There are a number of infographic screens in the app.  They all need to

- Display a single pinch to zoom image
- Have either a "x" or "<" button in the left hand corner
~- Have a share button in the top right which brings up the OS share sheet to share the image~
- Have configurable theming.  Either blue, purple or green
- Have a configurable title.

**These are the colours to use in green mode**
![Yourself : PPE : Detail 02 - Infographic](https://user-images.githubusercontent.com/902252/77820096-e48df200-7133-11ea-8049-78845edf29d4.png)

**These are the colours to use in purple mode**
![Yourself : PPE : Detail 05 - Infographic](https://user-images.githubusercontent.com/902252/77820110-f1aae100-7133-11ea-9fc9-5ca9e0199d54.png)
(note the grey background)

**These are the colours to use in blue mode**
![ICU : General Care](https://user-images.githubusercontent.com/902252/77820129-1010dc80-7134-11ea-8260-e3f4562d9270.png)
(Yes, I know the picture should have the share icon, not the phone.  You know what to do 😁 )

~I'm not sure if we can do different icons per platform, but if possible on Android we should use the 
`icon_share_android.svg` and on ios `icon_share_ios.svg`~

**Comment by lukesleeman** [comment]
Here is a mockup of the screen showing an image.

![Intubation : Algorithm](https://user-images.githubusercontent.com/902252/77820398-2e77d780-7136-11ea-9144-a2c3d8759c26.png)

Note the padding around the image when it first appears.  Obviously once you start to zoom in that will go away.

**Comment by kimngyn** [comment]
Yes, Sir!

**Comment by lukesleeman** [comment]
Once this issue is complete, issue #112 can be moved to ready for dev

**Comment by yimingc2** [comment]
![image](https://user-images.githubusercontent.com/14011195/77841049-a77c3b00-71d9-11ea-8d16-9d1f66884573.png)
This is the big view.

**Comment by lukesleeman** [comment]
Yep!  For this issue (and PR!) just build the reusable widget.  Then as part of #112 we will use the widget in a bunch of places.

For this issue just stay focused on the widget, don't need to hook it up in all the various places

**Comment by yimingc2** [comment]
@lukesleeman , do we need to implement the "Share Button"? Or do it in next PR?

**Comment by lukesleeman** [comment]
> @lukesleeman , do we need to implement the "Share Button"? Or do it in next PR?

Yep, please implement the share button

**Comment by kimngyn** [comment]
I have unassigned myself due to personal commitments, and I have passed this issue on to June.  I will still probably be around to review things and check for errors. 

Hopefully, everything will go well. Thanks :)

**Comment by lukesleeman** [comment]
👋 wave is it possible to get a bit of a status update on what's been done and what is still in progress? What beach are you working in?

**Comment by yimingc2** [comment]
Hi @lukesleeman , I'm also on this card. The reuseable infographic page with different theme is done basically. I'm working on "Making padding around the image when it first appears." right now.

**Comment by rockgecko-development** [comment]
@yimingc2 let me know if you need a hand re sharing the image to the system share sheet. This is something I have done in another flutter project, so happy to help

**Comment by yimingc2** [comment]
> @yimingc2 let me know if you need a hand re sharing the image to the system share sheet. This is something I have done in another flutter project, so happy to help

That would be great. I thought sharing as PDF was not included in this PR. What do you suggest?

**Comment by rockgecko-development** [comment]
> > @lukesleeman , do we need to implement the "Share Button"? Or do it in next PR?
> 
> Yep, please implement the share button

It is, see above ^

I think the share_extend package might share the image, I've used it before.
If it doesnt work by default, you might have to get a path to the underlying asset file...and if that's not possible you'd have to write it to a temp file.... there's a bit of an example on the pub.dev page but it's in chinese :) . EN here https://github.com/zhouteng0217/ShareExtend/blob/master/README-en.md

**Comment by lukesleeman** [comment]
>  there's a bit of an example on the pub.dev page but it's in chinese :) 

FYI June can read Chinese 😁   Very useful skill!

**Comment by lukesleeman** [comment]
👋 @yimingc2 I've moved the requirement for a share button out to issue #141  - we can address that much later.
