### ISSUE TITLE
Build out infographic screens

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#112]
This issue depends on issue #111 and #96 being built out 1st.   Once we have our reusable infographic widget and the home screen is updated, there are 5 different infographics screens which need to be added to the app which will make use of it.

TASKS
- [x] PPE ON infographic
- [x] Taking off PPE Method One
- [x] Taking off PPE Method Two
- [x] Intubation Infographic
- [x] Intubation Checklist Infographic
- [x] Extubation Infographic

# PPE ON infographic
![Yourself : PPE : Detail 02 - Infographic](https://user-images.githubusercontent.com/902252/77846482-12da0300-7202-11ea-98aa-3c9d9e0000b1.png)

Image:  `putting_on_ppe.png`
left hand side button: `X`
Theme: Green
Title: `PPE ON Infographic`
How you access the screen: On the putting on PPE step by step guide screen add a button to view the PDF 👇

![image](https://user-images.githubusercontent.com/902252/77846494-2f763b00-7202-11ea-97e4-e6ee7b676f19.png)

# Taking off PPE Method One

![Yourself : PPE : Detail 04 - Method One Infographic](https://user-images.githubusercontent.com/902252/77846573-b3302780-7202-11ea-8811-b00faa27a89b.png)

Image:  `taking_off_ppe_1.png`
left hand side button: `X`
Theme: Purple
Title: `Method One Infographic`
How you access the screen: On the PPE screen, in the method one step by step guide  add a button to view the PDF 👇

![image](https://user-images.githubusercontent.com/902252/77846586-ccd16f00-7202-11ea-8987-ef15c105f218.png)

# Taking off PPE Method Two

![Yourself : PPE : Detail 06 - Method Two Infographic](https://user-images.githubusercontent.com/902252/77846596-dd81e500-7202-11ea-980b-743cb2e13342.png)

Image:  `taking_off_ppe_2.png`
left hand side button: `X`
Theme: Purple
Title: `Method Two Infographic`
How you access the screen: On the PPE screen, in the method two step by step guide  add a button to view the PDF 👇

![image](https://user-images.githubusercontent.com/902252/77846628-1ae67280-7203-11ea-894b-cd1ecee95735.png)

# Intubation Infographic

![Intubation : Guide - Infographic](https://user-images.githubusercontent.com/902252/77846675-6b5dd000-7203-11ea-854b-7b436f600025.png)

Image:  `airway_management.png`
left hand side button: `X`
Theme: Green
Title: `Intubation Infographic`
How you access the screen: Under the Intubation Guide screen add a button to view the PDF 👇

![image](https://user-images.githubusercontent.com/902252/77846725-bb3c9700-7203-11ea-89c1-0851e2b122b5.png)

# Intubation Checklist Infographic

![Intubation : Checklist - Infographic](https://user-images.githubusercontent.com/902252/77846742-d909fc00-7203-11ea-9d1b-bc6cba4a7b93.png)

Image:  `intubation_checklist.png`
left hand side button: `X`
Theme: Green
Title: `Intubation Checklist Infographic`
How you access the screen: Under the Intubation checklist screen add a button to view the PDF 👇

![image](https://user-images.githubusercontent.com/902252/77846801-4ddd3600-7204-11ea-81a6-6bb7a78fdcd5.png)

# Extubation infographic

![Extubation : Infographic](https://user-images.githubusercontent.com/902252/77846844-a01e5700-7204-11ea-871e-74be7b9182d6.png)

Image:  `extubation_process.png`
left hand side button: `<`
Theme: Green
Title: `Extubation Infographic`
How you access the screen: Clicking the Extubation button on the main screen 👇

![image](https://user-images.githubusercontent.com/902252/77846894-01462a80-7205-11ea-855b-741e6e122a60.png)

**Comment by lukesleeman** [comment]
If anybody wants to see some examples of what some of these screens should look like, we have:
![Intubation : Algorithm](https://user-images.githubusercontent.com/902252/77821906-f24a7400-7141-11ea-9cdc-21451fbb376a.png)
![Extubation : Infographic](https://user-images.githubusercontent.com/902252/77821907-f4143780-7141-11ea-8176-a5893610458c.png)

**Comment by lukesleeman** [comment]
Question for @greggmiller do we also need to include page 1 of of the `SAS COVID 19 infographics 1 2.pdf` in infographic form?   That page will be adapted into a beautifully designed mobile app screen as part of issue #37 - but do we need to include the original un-altered infographic.

FYI. this is what Page 1 of `SAS COVID 19 infographics.pdf` looks like:


![](https://user-images.githubusercontent.com/902252/77730417-dae18d00-7054-11ea-96d0-8da4eb7310f4.png)

I'm guessing that since we should be including all the original infographics in the app somewhere, the answer would be yes?

**Comment by lukesleeman** [comment]
@marcedwards Are you able to put a better version of `intubation_checklist.png` in the repo?  I think it's the wrong size, and it's in the wrong folder.

Also, are you able to update sketch and zeplin designs to reflect my awful mockups I put on this issue 😂   I'm guessing you can make them look better than my attempts in keynote

**Comment by greggmiller** [comment]
@marcedwards re: intubation_checklist.png  
Images of the same table appear on right hand side of Safe Airway Society twitter
https://twitter.com/safeairway?lang=en

I am not sure if the image on twitter will be better or worse quality to update 😅

**Comment by lukesleeman** [comment]
👋 I have integrated all the latest designs, and updated the description of this issue.

Once issue #111 and issue #96 are complete, this issue should be `Ready for dev` 😁

**Comment by lukesleeman** [comment]
As discussed in tonights call, I'm moving this one over to @yimingc2 with the possibility of @kimngyn helping out a little bit if she gets any time.

@yimingc2 please go on with this one **only after** your PR get merged and we can close off #111

**Comment by kimngyn** [comment]
Okie dokie :)
