### ISSUE TITLE
DisclaimerView causing overflow errors on some devices

### ISSUE THREAD

**Issue by joshcase** [Western-Health-Covid19-Collaboration/wh_covid19_app#115]
Note that DisclaimerView uses a MediaQuery to decide whether to build a scrollable list or a static container. This MediaQuery depends on an arbitrary height value that causes overflow errors on some devices, such as my HTC One.

We likely need a more responsive approach that does not depend on arbitrary height values.

**Comment by workerbee22** [comment]
Working on a fix now to remove the MediaQuery so works regardless of device height.

**Comment by workerbee22** [comment]
Can probably close this issue as tracking in issue [#47](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/47)

**Comment by lukesleeman** [comment]
Awesome, closing!  Thanks for the bug report @joshcase - keep up the eagle eyes! 👀
