### ISSUE TITLE
Slight change to wording of disclaimer text

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#118]
Currently part of the disclaimer says:

> The app is made available on the understanding that Western Health and its employees have have no liability …

We should update it to:

> The app is made available on the understanding that Western Health, Western Health employees, the designers, developers, testers, reviewers, organisers and all other contributors to the project have have no liability …

**Comment by sallychung** [comment]
I can take this one. Nice intro to the project

**Comment by workerbee22** [comment]
Just be aware .... also working on Disclaimer atm ... but not the text content.

**Comment by lukesleeman** [comment]
Yep, Mike is doing some very heavy changes with this screen right now (I'm on a zoom call with him RN :-) )

I've removed `ready for dev` - I think @sallychung just hold up until mike has finished his rebuild

**Comment by workerbee22** [comment]
@sallychung Please message me directly when this is in. Also note we are adding in i[ssue 47](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/47) a requirement to the Disclaimer, where with the Disclaimer text there is an accompanying version flag. Idea is:

- When the Disclaimer text is changed AND the accompanying version flag, then the user is asked to re-accept the new Disclaimer ie. users must always have accepted the current Disclaimer text to use the app, as it may change.

**Comment by lukesleeman** [comment]
@workerbee22 did you want to also log the changes that apple requested to the disclaimer in here?  Then we can hit the text all at once

**Comment by lukesleeman** [comment]
Based on https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/113#issuecomment-606547631 we might put something like 

> This app is designed to serve as an educational tool and interactive cognitive aid for Western Health Anaesthetists and ICU doctors 👩‍⚕ 👨‍⚕ who are managing patients with COVID-19 🤒 .
>
>🛑 ✋ It is ONLY for Clinician or hospital staff use ✋ 🛑

Right up the top of the disclaimer to address what apple needs of us.

**Comment by workerbee22** [comment]
Yep I will 👍

**Comment by lukesleeman** [comment]
I think given the situation I'll also assign @workerbee22 to this issue - I think it looks like @sallychung will be mostly focusing on QA.  It might make sense for mike to just implement all this as part of his disclaimer changes.

**Comment by workerbee22** [comment]
Yep easy ... will fold these words into my current branch `fix/disclaimer-update`

**Comment by lukesleeman** [comment]
Here are @Mattro 's designs from zeplin for the extra text:

![Disclaimer : Long](https://user-images.githubusercontent.com/902252/78124900-0f41b880-745c-11ea-96ff-6d1e1582d001.png)

Screens are in zeplin
