### ISSUE TITLE
Android release builds need to be signed 

### ISSUE THREAD

**Issue by maks** [Western-Health-Covid19-Collaboration/wh_covid19_app#12]
Need to setup CI to sign release builds for Android

**Comment by workerbee22** [comment]
@maks This seems done. Its in codemagic, but where should we store all the Keys? Do we have a Key Store somewhere? We should store them securely before we close this issue.

**Comment by maks** [comment]
Yes sorry Mike it's done. Will close and follow up with you and Gregg about keystore
