### ISSUE TITLE
PNG image assets need to be smaller

### ISSUE THREAD

**Issue by maks** [Western-Health-Covid19-Collaboration/wh_covid19_app#136]
PNG image assets are too big and need to be minified with https://tinypng.com/ or similar.

We need to do this for all existing assets in the app and then going forwards for all new images.

Part of #131

**Comment by ericjiang97** [comment]
Also SVGs need to have inline styles!

**Comment by marcedwards** [comment]
Which PNGs? The ones that were derived from the PDFs have already been run through ImageOptim. We definitely may be able to shave some more bytes off, or even switch to JPEG, but they are large dimension images.

To be clear: I’m _all_ for having a tiny bundle and I can definitely take a look at crunching these down further. Just know that I did a bit of work initially.

Also… lots of ❤️ for calling a 33MB app “large”. I’m definitely on that team! 

------

@ericjiang97 Do any of the SVGs on the repo need changing? I’ve tried to ensure all new SVGs I make use inline styles.

**Comment by ericjiang97** [comment]
@marcedwards Not at the moment, I've been changing them myself when they're not styled inline. 

But I reckon it will be cool if we can automate the compression/inline-styling as a pre-commit hook?

**Comment by marcedwards** [comment]
@ericjiang97 It’s just an export setting in Illustrator. Not sure anything needs to be automated, but it’s an app global setting, so anyone exporting the SVGs needs to be aware of it (right now, it has just been me exporting them).

If anyone reading this wants to know how to set Illustrator up to export SVGs with inline styles, it’s in the Export for Screens SVG settings (`Export for Screens` › click the settings cog › `SVG` › `Styles: Inline`).

![Illustrator](https://user-images.githubusercontent.com/1121547/77967127-33a07680-7330-11ea-9e87-1e70e7c4132f.png)

**Comment by workerbee22** [comment]
@marcedwards Try tinypng.com ... does not seem to reduce clarity, just optimises PNG format. Pick any PNG ... I was getting 40 - 70% size reductions.

**Comment by workerbee22** [comment]
For example `off_hand_hygiene.png` from 143 KB down to 40 KB.

**Comment by workerbee22** [comment]
SVGs should be fine and minifed already and inherently.  Just bitmap images like PNGs.

**Comment by marcedwards** [comment]
>For example off_hand_hygiene.png from 143 KB down to 40 KB.

Tinypng and similar tools usually achieve that by using indexed PNGs, and reducing the number of colours, often with dithering techniques that assist compression. There’s only so much you can do before the images get severely damaged and are lower quality. I was able to get `off_hand_hygiene.png` down to 90,597 bytes and most of the images are indexed PNGs with reduced number of colours already. I’d be very careful using lossy compression beyond that.

https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/138 contains lots of improvements.

It’s also worth noting that Xcode can undo PNG compression. I don’t know how this works with a Flutter build process, but by default for native projects, Xcode recompresses PNGs using PNGCrush. More info: https://bjango.com/articles/pngcompression/
