### ISSUE TITLE
iOS release builds need to be signed 

### ISSUE THREAD

**Issue by maks** [Western-Health-Covid19-Collaboration/wh_covid19_app#14]
Need to setup CI to sign release builds for iOS

**Comment by workerbee22** [comment]
I'll pick this up as part of the Firebase App Dist work as they are highly correlated.

**Comment by workerbee22** [comment]
Needs the Apple Developer account to create a provisioning profile, to then sign the iOS file and produce a .IPA file for distribution via Firebase App Distribution (or TestFlight or App Store).

**Comment by workerbee22** [comment]
Setup complete and confirmed iOS signing in Codemagic working correctly. Closing th eissue.
