### ISSUE TITLE
Update information section design and links

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#140]
Edit by Luke:
The information screen needs updating to match the designs posted by @cjmlgrto below 👇 

Changes required
- [ ] WH Novel Coronavirus information button renamed to "WH Novel Coronavirus Website" and changed to purple
- [ ] Purple "WH Anaesthetic Microsite" button to be added, which links to https://whcovid19.wixsite.com/covid19
- [ ] Purple "ICU Microsite" button to be added, which links to https://whicu2020.wixsite.com/icuquickguide
- [ ] Lorium ipsum to be removed and replaced by "Built with ❤️ by a band of volunteers"

~Similar to #117 Add WH Novel Coronavirus website fixed so expertly by @yimingc2  😄 👍~

~So with the blessing of @Western-Health-Covid19-Collaboration/designers and @lukesleeman this one may be ready for dev?~

~Request:~
~**Add WH Anaesthesia COVID-19 to the information screen.**~
~The intention would be to directly link through the external browser~
~https://whcovid19.wixsite.com/covid19~

~This link should be the top one above WH Novel Coronavirus site~
~This is the WH anaesthesia COVID-19 microsite which @galtaforce has very nicely put together through over the last few weeks.~
~This mobile-friendly microsite contains a more comprehensive range of documents for our anaesthetic department, that runs in parallel with the app 😄.~
~The app is intended as a fast aid educational tool and cognitive aid (as per TestFlight description and onboarding screen).~

**Comment by lukesleeman** [comment]
@Mattro or @marcedwards - Can you folks update the designs to put a new button in the information screen above the "WH Novel Coronavirus information" one?  Once thats done post a screenshot and change to ready for dev :-)

**Comment by cjmlgrto** [comment]
Here's what that screen will look like.

![Information](https://user-images.githubusercontent.com/1712450/78468395-f9354000-775a-11ea-8521-5657929839f0.png)

**Comment by greggmiller** [comment]
As discussed with @cjmlgrto but to clarify for others...

The info page could do with 3 links at the top that would be most useful for user on this.
This is 
WH Novel Coronavirus microsite
WH Anaesthesia COVID-19 microsite
and 
WH ICU COVID-19 microsite.

This is in addition to the other sites on additional resources.

I think @cjmlgrto has some designs for this that he might be adding to Zeplin.
Thanks 😄

**Comment by lukesleeman** [comment]
I've cleaned up the issue description, and moved this over to ready for dev.

One small change - After thinking it over, it might be better to say:
> Built with ❤️ by a band of volunteers

"Bunch", sounds like we are bunch of bananas or something 😂

I think "band" either sounds like we are either some musicians coming together to jam out some awesome tunes, or a roving band of desperados hiding out in the mountains, and coming together to fight for justice. - either of which I'm fine with 😂

Happy to take suggestion on the copy from others though

**Comment by kimngyn** [comment]
by volunteer developers? :)
