### ISSUE TITLE
Share infographics

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#141]
It would be helpful for users to be able to share the infographics in the app, along with downloading and viewing the original PDFs.

We had a crack at this as part of issue #111  however it proved to be quite complex.  We started running into OS specific issues around permissions, etc.  

We can build out a better specified, more functional implementation as part of this issue.

**Comment by lukesleeman** [comment]
I've marked this as a `low prority` and `medic` - we can probably start the process off by asking @greggmiller what exact problem and user need we will solve via the share button.

TBH, I added in the share button requirement because it sounded like a valuable thing for staff to be able to send the infographics to each other, etc, and because it sounded like an easy thing to add.

Its now not looking quite so easy.  But perhaps it's still a valuable thing to put in?  Or are we better off not doing this?

**Comment by greggmiller** [comment]
@lukesleeman We can probably live without the feature of sharing.

The infographic as a tertiary screen that @Mattro  behind checklists and guides works very well as a visual aid the user can rapidly move between.

For sharing, all the infographics are available on the WH Anaethestia COVID-19 microsite.
https://whcovid19.wixsite.com/covid19

This site is a more comprehensive information page and is easy to navigate so anaesthetists will know to get them there.
We could consider this feature again some way down the track, but would not be necessary until a much later version. 

If that answers your question, we could close this issue for now? 😄

**Comment by lukesleeman** [comment]
Yep, I'll close
