### ISSUE TITLE
Build out Extubation Screen

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#144]
The intention is that this provides a step-by-step for the user highlighting main ways COVID19 intubations are different from our day to day intubations. 
It is some pointer and a list of do’s and don’ts for intubation. 
This guide can both be used in the preparation phase, the simulated environment for training and as an educational/revision tool.

The 5 tabs for **scrollable tab** would be

* Planning
* Prepare
* PPE
* Perform
* Post-ETT
Each of these steps will have a few bullet points of information next to them, please feel free to modify emojis.

The full information would be:

**Planning** 

✅ Is patient clinically stable to extubate now?

✅ Assemble team - Anaesthetist and Anaesthetic nurse

💬 Discuss extubation plan.

🤔Consider strategies to reduce coughing if you are familiar with them.
* Lignocaine
* Remifentanil
* Spont breathing deep extubation
* Dexmedetomidine
* LMA exchange

**Prepare** 

⚙️  Have equipment available for reintubation of patient
🏃  Have runner in anaesthetic bay.

🦠 Ensure Viral filter and etCO2 ready to be connected to disposable mask following extubation.

**PPE** 

✅     All staff in room must wear FULL PPE including N95 mask and eye protection

😊    Buddy check each other PPE prior to performing extubation

Perform
✅     Extubate patient with cuff down and APL fully open (NO positive pressure).

🚮 Carefully discard ETT into clinical waste bin.

✅    Immediately apply face mask to patient with 2 hand grip (over nasal prongs if present).

✅    Continue to apply face mask until able to protect their own airway.

✅    Switch to surgical mask with Hudson or Nasal Prongs over the top.

**Post-ETT**

🚮 Carefully discard face mask and other disposable equipment into clinical waste.

😷 Patient must wear surgical mask on transfer back to ward.

😊      Doff PPE with Buddy check.

* The above headings are unlikely to change, but the bullet points may. As our knowledge of COVID19 increases, we will refine our advice and guidelines on the safest intubation technique.

Relevant Source documents:
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/WH_ANAES_C19ExtubationGuidelinesV1.0.docx

It would be useful if following document could appear when using a territory button for PDF
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/Extubation_Infographic.pdf
This is the same as @mattro has laid out some of the intubation screens.

Feel free to comment @A-Gynther  or make recommendations for change 😄

**Comment by lukesleeman** [comment]
FYI, we are currently just putting the infographic into the extubation screen - I guess once this is designed properly, we will move that out under a "PDF" button?

**Comment by greggmiller** [comment]
Yes @lukesleeman  I have had a discussion with @Mattro about this and how the scrollable tabs can be used to display this very well.

It would be an excellent addition for the first full beta version as it is an aspect of care we discuss a lot but this would depend on how much extra time it would take the team and particularly @Mattro who has said he would be keen to take this one on 😄

**Comment by cjmlgrto** [comment]
Alright, here's a first pass at the screens. Main thing I'm unsure about is the sentence capitalisation.

Keen to hear your thoughts @Western-Health-Covid19-Collaboration/medical + @Western-Health-Covid19-Collaboration/designers 

![Slice](https://user-images.githubusercontent.com/1712450/78471195-d44cc700-7772-11ea-9c97-c1b563023b15.png)

**Comment by kimngyn** [comment]
Friendly suggestion: in the room. 

And please make the word “including” with a capital I? You seem to have done it everywhere else. 

I’m not on a computer at the moment to cross-check. I’ll check again tomorrow morning 😊

![EDD074A9-3B56-46EE-A151-B8084EB0492C](https://user-images.githubusercontent.com/42886400/78471498-124aea80-7775-11ea-9b78-51a0364a9e42.jpeg)

**Comment by kimngyn** [comment]
Friendly suggestion: lower case a

![Screenshot (97)_LI](https://user-images.githubusercontent.com/42886400/78513277-b6707800-77ed-11ea-84b1-964631dac876.jpg)

**Comment by kimngyn** [comment]
Friendly suggestion: "Have a runner in the anaesthetic bay" and lower case v

![Screenshot (98)_LI](https://user-images.githubusercontent.com/42886400/78513286-c9834800-77ed-11ea-8837-5e0555cbdb43.jpg)

**Comment by kimngyn** [comment]
Friendly suggestion: inconsistent capitals? possibly, nasal prongs. 

![Screenshot (100)_LI](https://user-images.githubusercontent.com/42886400/78513329-19faa580-77ee-11ea-807d-00c69a7e7c9c.jpg)

**Comment by kimngyn** [comment]
Friendly suggestion: lowercase b for buddy. 

![Screenshot (99)_LI](https://user-images.githubusercontent.com/42886400/78513341-2da60c00-77ee-11ea-9a84-137899e77d1b.jpg)

**Comment by greggmiller** [comment]
Thanks @kimngyn for your close eye to detail.

I agree with all the changes you have suggested.

A couple of others I would recommend:

**Planning:**

Bullet point under assemble team we can add ONLY to the end so it reads:
"Anaesthetists and anaesthetic nurse ONLY"

(The emphasise on ONLY as we want to minimise those in the room at the time that we might be aerosolising viral particles)

**Prepare section**

remove "of patient" to make it "Have equipment available for reintubation."

@marcedwards Are you happy to make these on Zeplin before @bramt picks it up?

**Comment by lukesleeman** [comment]
I think lets just move this one over to ready for dev, then the designers can circle back around later to update the copy on the zeplin side

**Comment by Mattro** [comment]
Thanks everyone. These copy adjustments are up to date in Zeplin too. 👍

**Comment by lukesleeman** [comment]
> Thanks everyone. These copy adjustments are up to date in Zeplin too. 👍

Great work Matt!

I've hidden all the to-and-fro on the copy - @rockgecko-development be sure to check out zeplin for the latest copy and ... well copy form there :-)
