### ISSUE TITLE
Build a Licenses screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#147]
We will probably need to add in a licenses screen for the various bits of open source software we are including

**Comment by lukesleeman** [comment]
@marcedwards or @Mattro when you get some time, can you put a button to link out to licenses on the information screen.

In terms of how the licenses screen its self needs to look - I think just a huge wall of text?

**Comment by workerbee22** [comment]
Note Flutter has two classes for these sorts of things. But they result in a default UI. We can roll our own but use these to automatically provide the info for the app, especially all licences info:

https://api.flutter.dev/flutter/material/LicensePage-class.html
https://api.flutter.dev/flutter/material/AboutDialog-class.html

It allows for easily getting the current app icon, version and other details. So we should use these classes where appropriate for the data from the app. No hard coding data !

So we just need the 'look' designed.

**Comment by lukesleeman** [comment]
Yeah, I'm thinking for the licenses screen, there is no point spending any design time on it.  I think if @Mattro or @marcedwards can just add a button to the information screen to launch it, and update the flow diagram, then we can move this one over to ready for dev.

**Comment by maks** [comment]
:+1: to using the builtin AboutDialog and LicensePage we get alot of functionality for free and no need to spend effort on this non-core functionality.
@lukesleeman can this go out for dev to pickup now?

**Comment by lukesleeman** [comment]
> 👍 to using the builtin AboutDialog and LicensePage we get alot of functionality for free and no need to spend effort on this non-core functionality.
> @lukesleeman can this go out for dev to pickup now?

@maks any idea on how we go about getting a list of licenses we need to include?

**Comment by maks** [comment]
@lukesleeman The beauty of it is it should all be automatic with the package manager taking care of it: https://api.flutter.dev/flutter/foundation/LicenseRegistry-class.html

**Comment by lukesleeman** [comment]
Oh, nice!  In that case moving this one to ready for dev!

**Comment by lukesleeman** [comment]
Thanks for the updates to the diagram @cjmlgrto  - I'm moving this one over to dev 🙂
