### ISSUE TITLE
Build out the Acknowledgements and references screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#148]
We need to build out an Acknowledgements and references screen

**Comment by lukesleeman** [comment]
@greggmiller are you able to provide some details on what should go in it?  For acknowledgements we have some in the Readme.md we could use.  What kind of references did you envisage this screen having?

**Comment by greggmiller** [comment]
@lukesleeman I'll do this by tomorrow... References will be the medical evidence and guidelines all the apps information is from. This is mainly Australia New Zealand College of Anaesthesia (ANZCA) and the Australia New Zealand Intensive Care Society (ANZICS) and a few others. 

Should hopefully not require too much design/dev time after that.

**Comment by greggmiller** [comment]
The intention is to both acknowledge everyone who has worked so hard on this project and to also cite the references from which the content is derived. 

_**References:**_

1. The Safe Airway Society for allowing us to use their guidelines and infographics.
https://www.safeairwaysociety.org/covid19/
2. Intensive Care Society https://www.ics.ac.uk/ICS/Education/Wellbeing/ICS/Wellbeing.aspx
3. Australian New Zealand Intensive Care Society COVID-19 guidelines
https://www.anzics.com.au/coronavirus-guidelines/
4. Western Health department of Anaesthesia policies and procedures
5. Western Health Novel Coronavirus Information
https://coronavirus.wh.org.au/
6. RNS ASCAR (Royal North Shore)
https://www.rnsascar.com/

The links can follow or be embedded within the text. Whatever works best.

**_Acknowledgements_**

In the interests of time, acknowledgements can be pulled from the contributors and acknowledgements section of Readme.

The best way to lay this out can be at the discretion of @Western-Health-Covid19-Collaboration/designers 

It is likely that both the references and the acknowledgements will increase in length over time.
@Western-Health-Covid19-Collaboration/designers

**Comment by maks** [comment]
@lukesleeman  Can we do this in the About Dialog and so use the work fror #147  ?

**Comment by lukesleeman** [comment]
> @lukesleeman Can we do this in the About Dialog and so use the work fror #147 ?

I think that sounds like a good idea.  If we use the about dialog what kind of guidance do we need from the designers?

**Comment by lukesleeman** [comment]
So I've bumped the priority on this as it turns out having references for where we sourced all the info is pretty important 🙂

In terms of what we need from design - nothing fancy, just some sort of textual screen to present this info.

**Comment by cjmlgrto** [comment]
I've used the same styling from #45 for this screen by making those cards work like links with descriptions. [Here's the design for it on Zeplin](https://app.zeplin.io/project/5e7597a68651056664fb6e53/screen/5e8b0f2d904a5820961a9418/).

![Acknowledgements and References](https://user-images.githubusercontent.com/1712450/79037293-08ad0100-7c13-11ea-92e6-554cae06a1ae.png)

**Comment by kimngyn** [comment]
“Department” with capitalisation? Maybe? 

“Codemagic and Manichord for additional build minutes and support “ maybe? 

Everything else looks good.

**Comment by greggmiller** [comment]
Great work @cjmlgrto 🙌 

Yeah probably a D for Department.

Codemagic and Manichord did provide additional minutes and support so should be recognised 👍 

I also think its right that each contributor (dev, developer etc.) is named (if they wish to be) under acknowledgements or a contributor section? Maybe the contributor a separate colour for a link or it scrolls down to that? Happy for that decision to be made by all the collaborators/contributors as how this should be done 😄 

Otherwise, this is good to go!

**Comment by cjmlgrto** [comment]
Done— [on Zeplin now](https://app.zeplin.io/project/5e7597a68651056664fb6e53/screen/5e8b0f2d904a5820961a9418/) 👍 

Might be worth adding a link to the repository in this project perhaps? Tapping "Made with ♥︎ by a band of volunteers" could do that? That way the app doesn't have to keep being updated for every new contributor?

**Comment by greggmiller** [comment]
This one looks ready for @Western-Health-Covid19-Collaboration/flutter-devs.
 @lukesleeman ?

**Comment by lukesleeman** [comment]
Yep, this one looks ready for dev!

I think with individual contributors, it would be nice if all our names were in there somewhere 🙂  But in the interests of keeping this particular task focused, let just build to the designs right now - hopefully a little bit later, the designers can come up with some kind of cool easter egg, or way of putting us all in there.

**Comment by greggmiller** [comment]
@lukesleeman Yes agree, individual names and role/contribution should be in there 😄 👍. 

This can probably be copied directly from the README?

**Comment by sallychung** [comment]
✅ v1.0.146
