### ISSUE TITLE
Need to add tool for Crash Reporting & Analytics

### ISSUE THREAD

**Issue by maks** [Western-Health-Covid19-Collaboration/wh_covid19_app#15]
I'm familiar with Sentry and it works well for Flutter in prev project so I can set up Sentry account and add to app unless someone else has different preferences?
cc: @workerbee22 @alessandrofavero @adamkoch @domesticmouse

**Comment by adamkoch** [comment]
I've only used Sentry with RN before. It seems good. Other option which I've used with Flutter is [Firebase Crashlytics](https://pub.dev/packages/firebase_crashlytics) which also works quite well although it has an open where it catches all exceptions as non-fatal (you an still see all the info fine though).

**Comment by maks** [comment]
Thanks @adamkoch . Yes I had lots of trouble last year with crashlytics for Flutter app, so went with Sentry on several apps so far includign a commerical one and works very well.

**Comment by adamkoch** [comment]
Sentry SGTM

**Comment by workerbee22** [comment]
Given we have FB support in the app for FB App Dist ... we could use Crashlytics, but I'm not that wedded to it.

**Comment by workerbee22** [comment]
@maks @lukesleeman @rockgecko-development So this along with analytics can be delayed until just before large beta group. Also **expanding the scope of this issue to include analytics**. But I think in this case Crashlytics may be the better choice because:

- `google-services` already in the app code for iOS and Android
- Firebase app setup for Android and iOS also already setup in the app and integrated into the app and the Firebase console
- because of the two above getting setup for iOS and Android should be easy from here
- Google Analytics also because of above will be easy from here for iOS and Android setup.
- Firebase console is very 'non tech' friendly and with Crash Reporting + Analytics shown in Firebase console (and more detailed data get shown in Google Analytics console) this makes it kind of a friendly one-stop-shop for Gregg to use later after the app is live.

**Comment by maks** [comment]
There's trade offs on both sides.

My main reasons for suggesting Sentry over Crashlytics:

* Personal experience in trying to get Crashlytics working on previous commercial Flutter project was **absymal**
* **Real time** data reporting so you don't wait X hours to find out about mass crash spikes
* Sentry package pure dart so much easier to work with than FB
* Sentry dashboard much more developer friendly, I don't see the argument for why we need it to be non tech user friendly ? as the specific audience is developers *not* nontech project users
* *Subjectively* I've found quality and stability of Sentry dart package much better than FB Crashlytics one

So we need to balance all the pros for FB in Mike's comment with the above and try to come up with our preferred option.

**Comment by workerbee22** [comment]
Ok we need to make a decision at some point. Sentry wise yep I like too and is a friendly console too. 

But I also have Crashlytics working on Android and iOS in multiple projects and didn't see big issues. Reporting is also not that long ... from memory it like 10s of minutes not hours to report to console. 

@maks do we know how good Sentry is with iOS? I've only used on Android.

But how about we vote to make the call?

**Comment by maks** [comment]
I'm ok with Crashlytics as long as I don't have to set it up 😉

But is the error reporting from Flutter not being given error status in Crashlytics still an issue?

Also seems to be problems getting it working properly on iOS: https://stackoverflow.com/q/60111182/85472

**Comment by workerbee22** [comment]
I can set it up, given I know it better than most.

That info on crashes not being reported as 'non-fatal' is no longer true. See below:

![image](https://user-images.githubusercontent.com/5154664/78633390-d767c480-78e4-11ea-8dd2-839af7be8504.png)

🙈See several 'Crash' status errors reported ... won't show the rest of the list ... lots of Carsh status errors 🙈🤣

See also working on iOS ... but haven't been actively using my iOS apps lately so only 1 crash in console atm. But to confirm I'll go back and simulate the various levels of crashes/errors on iOS just to make sure they all come through 👍

![image](https://user-images.githubusercontent.com/5154664/78633582-53620c80-78e5-11ea-9df5-17f1e37820d9.png)

There is also a PR in already for the FlutterFire package to migrate over to the NEW Firebase Crashlytics SDK (no more Fabric dependencies etc.) that is currently in Beta. So I'll have a closer look now to update myself first. 👍

**Comment by adamkoch** [comment]
> That info on crashes not being reported as 'non-fatal' is no longer true. See below:

Interesting. I've never been able to get it working personally. For reference, the issue is here:
https://github.com/FirebaseExtended/flutterfire/issues/398

**Comment by workerbee22** [comment]
@adamkoch Yeah I might have to update the issue FirebaseExtended/flutterfire#398 with some 'tricks' I've discovered. But before we finalise Crashlytics wan to do some quick retesting ... just in case.

**Comment by workerbee22** [comment]
Here are more examples of crashes:

![image](https://user-images.githubusercontent.com/5154664/78654093-6be31e80-7907-11ea-8ac8-c892f1651144.png)

**Comment by adamkoch** [comment]
@workerbee22 awesome, if you can add more info to the public bug that would be great, then others can also try and get it working 👍

**Comment by workerbee22** [comment]
Rechecked Crashlytics and still takes a while for the crashes to hit the console. So will do a combined PR for both of these together.
