### ISSUE TITLE
Audit app UI against Zeplin and raise `UI Polish` issues

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#154]
There are a lot of small places where the app needs additional polish or minor work to bring it in line with the screens in zeplin.  Things like padding, colours, and other minor visual tweeks would go a long way.

This issue is for somebody to go through the app screen by screen and do a cross check agains't what is in zeplin.  Any problems can be written up as issues in Github and tagged with the `UI Polish` label.

You can check the existing list of UI polish issues here to make sure there are no duplicates
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues?q=is%3Aopen+is%3Aissue+label%3A%22UI+Polish%22

**Note**. This issue _isn't_ about fixing anything up - just to co-ordinate the audit of the app and raising issues.

**Comment by lukesleeman** [comment]
I've also assigned @kimngyn who says she will be @sallychung's assistant 🙂

A designer that I have worked with is particularly good at reporting issues like these.  What he typically does is, produce a screenshot, which he annotates with labels:

![image](https://user-images.githubusercontent.com/902252/78416912-7b006d00-7678-11ea-919b-ba20dc692844.png)

Which gets included in the issue.  He uses markdown in the github issue to produce a simple checklist of all the things that need addressing like so:

```
- [ ] *A* - Update padding between buttons to 16dp
- [ ] *B* - Change the ...
- [ ] *C* - Update the ...
```

**Comment by sallychung** [comment]
Checklist here on what’s been audited

- [x] Disclaimer
- [x] Main Screen
- [x] Information
- [x] PPE
- [x] PPE - Putting On Step By Step Guide
- [x] PPE - Putting On Step By Step Infographic
- [x] PPE - Taking off Method 1 Step By Step Guide
- [x] PPE - Taking off Method 1 Step By Step Infographic
- [x] PPE - Taking off Method 2 Step By Step Guide
- [x] PPE - Taking off Method 2 Step By Step Infographic
- [x] Your Welfare
- [x] Intubation Guide
- [x] Intubation Guide Infographic
- [x] Intubation Checklist
- [x] Intubation Checklist Infographic
- [x] Extubation Infographic
- [ ] Ventilation
- [ ] Ventilation - Infographic
- [ ] ICU Daily Round
- [ ] Landscape support

**Comment by sallychung** [comment]
@lukesleeman What’s the extent on us supporting landscape mode? I noticed a bug was raised about it in the main screen. Should I audit every other screen with landscape?

**Comment by lukesleeman** [comment]
> @lukesleeman What’s the extent on us supporting landscape mode? I noticed a bug was raised about it in the main screen. Should I audit every other screen with landscape?

Thats a really good question.  I think in general we just need to support a bunch of screen sizes.  Trying things in landscape mode is a good way of finding bugs that may happen on something with a wider screen, such as a phablet or small tablet.  So it might be a good thing to test.

With that said, I don't think landscape is a huge priority - problems in landscape are more just an indication that we are not doing something properly layout wise.

**Comment by lukesleeman** [comment]
Ok, I'm actually moving this over into version 1, since we probably need to give the full set of screens a once over before the first public release

**Comment by sallychung** [comment]
### Home
- [x] Disclaimer (first install)
- [x] Main Screen
- [x] Information
	- [x] App Feedback
	- [x] Disclaimer & Conditions of Use
	- [x] Acknowledgements
	- [x] References
		- [x] Safe Airway Society
		- [x] Intensive Care Society
		- [x] Australian New Zealand Intensive Care Society
		- [x] Western Health Department of Anaesthesia
		- [x] Western Health Novel Coronavirus Information
		- [x] RNS ASCAR (Royal North Shore)
	- [x] Third-Party License
- [x] Phonebook button

### Staff Welfare

##### PPE Technique
- [x] Donning
	- [x] Step By Step Guide
	- [x] Step By Step Infographic
- [x] Doffing
	- [x] Method 1 Step By Step Guide
	- [x] 📄 Method 1 Step By Step Infographic
	- [x] Method 2 Step By Step Guide
	- [x] 📄 Method 2 Step By Step Infographic

##### Your Welfare
- [x] The basics
- [x] Pre-phase
- [x] Initial phase
- [x] Core phase
- [x] End phase
- [x] Long term

### Airway

##### Intubation Guide
- [x] Activation
- [x] Preparation
- [x] Intubation
- [x] Transfer to ventilator
- [x] Post-ETT
- [x] 📄 Infographic

##### Intubation Checklist
- [x] Team
- [x] Patient
- [x] Equipment
- [x] Plan
- [x] Final
- [x] 📄 Infographic

##### Extubation Guide
- [x] Planning
- [x] Prepare
- [x] PPE
- [x] Perform
- [x] Post-ETT

### ICU

##### Ventilation
- [x] Principles
- [x] Initial Steps
- [x] Adjuncts
- [x] 📄 Infographic

##### Daily Ward Round
- [x] A - Airway
- [x] B - Breathing
- [x] C - Circulation
- [x] D - Neaurological
- [x] E - Infection/Exposure
- [x] F - Renal
- [x] G - GIT
- [x] Final Check


##### Quick ICU training
- [x] Proning
	- [x] Indication
	- [x] Staff Pre-Manoeuvre
	- [x] Patient Pre-Manoeuvre
	- [x] Manoeuvre
	- [x] Post-Manoeuvre
- [x] Proning Technique
- [x] ALS/BLS Pandemic Modifications
	- [x] Principles
	- [x] PPE
	- [x] BLS
	- [x] ALS
	- [x] 📄 Infographic

### Resources
- [x] WH resources
 	- [x] WH Novel Coronavirus Website
 	- [x] WH Anaesthetic Microsite
 	- [x] WH ICU Microsite

**Comment by sallychung** [comment]
Draft: These are notes I took while testing. As the Zeplin files no longer match some of the screens, I’ve focused on UI more than the copy.

All
 - Tables with cells. Bottom margins from text content needs to be smaller
 - Tables with cells with list of emojis. Each line item needs a smaller margin in between
 - Section titles needs to have slightly bigger gap below text

Information 
- Made by love's emoji is not red

Disclaimer 
- Text content should be black. Hard to read grey text against white background on iPad where there is more white space
- Close gap between subtitles and content. 
	- Please keep in mind, This is not a compre..
	- WHAC19 does not ..., It is your respon...

Acknowledgements 
- Text should be grey. Similar issue with Acknowledgements

References 
- Subtitle should be a darker grey, slightly bolder

Third Party license 
- No Zeplin file but looks fine. Text could be darker for readibility

PPE
- PPE - Donning title top margin needs to be smaller
- PPE - Donning - Step by step - top margin needs to be larger
- PPE - Doffing - Step by step - Header text color should be darker
- PPE - Doffing - Step by step - Header text bottom margin needs to be smaller

Your welfare
The basics
 - Title top margin too small
 - Gap between title and "Basic tips" needs to be bigger
 - Cell detail text should be slightly bolder?
 - Cell's with a bold title at the top should have a slightly larger margin below

**Comment by lukesleeman** [comment]
Thanks for the great work @sallychung !

What would you like us to do with this issue? Did you want to keep it open against the Beta 3 milestone?  Or is the work for this issue done?

**Comment by sallychung** [comment]
There are varying levels of issues I think we should fix vs ones that could be left for later. 

AFAIK, most of these aren’t yet captured but I wanted to also double check that. 

I could highlight the ones I’d recommend fixing for release?

**Comment by lukesleeman** [comment]
> I could highlight the ones I’d recommend fixing for release?

👍 That sounds like a good plan

**Comment by sallychung** [comment]
I’ve created 2 issues that I think are worth fixing for release

#322 - Bottom cell margins in ICU sections needs to be smaller
#323 - Fix up Disclaimer text colour and margin

**Comment by lukesleeman** [comment]
Thanks for all your help on this @sallychung  - now we have everything in the audit ticked off, should I close this issue, or move it against a different version?

**Comment by sallychung** [comment]
Yeah, let’s close this off. We can create a new one if we need to do it again 🙂
