### ISSUE TITLE
Home screen Content Alignment

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#155]
The headings and card edges on the Home screen are not quite aligned to the left.

Changes required:
- No changes to the AppBar as this will be addressed by a separate issue.
- Content padding: let’s leave it at the passing defined in zeplin. 16pt/dp margins, 8pt/dp spacing. So headings padded slightly more to be aligned with edge of cards.

![image](https://user-images.githubusercontent.com/5154664/78415686-1260c280-766f-11ea-9168-faca4eed03ae.png)

**Comment by alessandrofavero** [comment]
@workerbee22 
![Screenshot_1585975702](https://user-images.githubusercontent.com/43284065/78418843-c7a17380-768b-11ea-81e8-21f310c3d47b.png)

**Comment by lukesleeman** [comment]
Whoever picks this up should be aware that issue #159 also touches these sections of the home screen and may result in some refactoring.

Check out issue #159 and see what status if has before its you get too far into this.

**Comment by workerbee22** [comment]
Can be closed also 👍
