### ISSUE TITLE
Home screen Background not full Width in Landscape

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#156]
Home screen background (green/blue/purple Western Health branding) is fixed width, and when the phone is rotated to landscape, does not adapt to the new landscape orientation screen width. Found by @kimngyn 👍

Changes required:
- Home screen in landscape, the background image should be the width of the screen
- Background image should not 'distort'

![image](https://user-images.githubusercontent.com/5154664/78415959-ec3c2200-7670-11ea-9461-5527de161d8f.png)

**Comment by alessandrofavero** [comment]
I can pick this one up!

**Comment by alessandrofavero** [comment]
Can something like this be alright? @workerbee22
![Screenshot_1585974390](https://user-images.githubusercontent.com/43284065/78418527-b0ad5200-7688-11ea-9e24-7b349160a5a9.png)

**Comment by alessandrofavero** [comment]
![untitled](https://user-images.githubusercontent.com/43284065/78418544-e05c5a00-7688-11ea-8f61-a1fbf821c432.gif)

**Comment by alessandrofavero** [comment]
Or this:
![Screenshot_1585974785](https://user-images.githubusercontent.com/43284065/78418626-9cb62000-7689-11ea-9a27-2bea3f9d34ba.png)

**Comment by lukesleeman** [comment]
I think thats looking pretty good.  We will need to talk to the designers about getting something which adapts better to wide screens, but in the meantime I think you have done a pretty good job of solving the issue.

**Comment by workerbee22** [comment]
Yeah the changes to orientation for landscape are the default widget rebuild behaviour right now. But when we do that there are several issues to consider where we may want to slightly change layout in landscape orientation change. We should do them all together.

@alessandrofavero I think this can be closed.
