### ISSUE TITLE
Simple modifications to PPE step-by-step

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#157]
A few simple changes required that should be ready for @Western-Health-Covid19-Collaboration/flutter-devs 
Assuming @Western-Health-Covid19-Collaboration/designers  and @lukesleeman are happy with below:

on PPE screen:
- Change words "Putting on" to "Donning"
- Change words "Taking off" to "Doffing"

------------ 

In "Donning" step by step guide (previously called putting ON)

- In Step 2: the words "in back neck" can be changed to "at the neck"

- Step 3: change words "middle of head" to  "crown of head"

------------------

In "Doffing" (previously taking off):

- in Method 1:

Step 3: 
Remove the first bullet point "Unfasten gown ties, taking care that sleeves don't contact your body when reaching for ties."

---------------------------

Apologies, some of this may seem pedantic, but these are important points as this is such a high risk time for us to get accidentally contaminated 😄 

Thank you to @A-Gynther for bringing these to my attention and feel free to comment if I have made any omissions. 

 @yimingc2 Let me know if I can clarify further any of this 😄

**Comment by lukesleeman** [comment]
@Mattro or @marcedwards Do you want to update the designs, so that they stay in sync?

**Comment by lukesleeman** [comment]
So I've pulled the designers off this until we get the code updated.  Once thats done, I'll hook them back up to sync whats in zeplin with the app.

**Comment by lukesleeman** [comment]
This is now in the app - I'm moving over to design, to sync zeplin with the copy in the app 🙂

**Comment by cjmlgrto** [comment]
Design are now synced to Zeplin 👌
