### ISSUE TITLE
Minor amendment to Intubation guide Pre-oxygenation tab

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#158]
On intubation guide can remove dot point: 

"Attached to manual ventilation device or Anaesthetic machine."

Point probably not required. Thanks for bringing it to my attention @A-Gynther 

Probably ready for dev @lukesleeman and a good first issue?

**Comment by lukesleeman** [comment]
@Mattro or @marcedwards are you able to update the designs so they stay in sync?

**Comment by lukesleeman** [comment]
So I've pulled the designers off this until we get the code updated.  Once thats done, I'll hook them back up to sync whats in zeplin with the app.

**Comment by lukesleeman** [comment]
Now this is in the app, I'm re-assigning to the @Western-Health-Covid19-Collaboration/designers for them to sync the copy changes with what is in zeplin

**Comment by cjmlgrto** [comment]
Designs synced — they're up on Zeplin now 👍
