### ISSUE TITLE
Update the layout of the airway section

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#159]
The airway section in the app currently has "Intubation checklist" and "Extubation Guide" as small buttons side by side:

![image](https://user-images.githubusercontent.com/902252/78418057-6c1fb780-7684-11ea-82d4-e794c67193dc.png)

Where as the designs in Zeplin have them in a list:

![image](https://user-images.githubusercontent.com/902252/78418069-89ed1c80-7684-11ea-8996-9c8c9dfd6b98.png)

The airway section needs updating bring the app in line with the zeplin designs

**Comment by lukesleeman** [comment]
I had a look into why this is occurring and it seems to be just a bit more than some one line fixes.  We have a `CardContainer` widget which contains a title, and a list of cards.  The way it lays out its cards depends on how many there are in the list:

- 2 Cards go in a horizontal row
- 3 Cards with one large one, and two smaller ones underneath
- 4 Cards go in a grid of small cards
- Otherwise it returns an empty container with nothing in it 😳 

If we change the logic for the 3 card case, we will break the ICU section which needs to have 1 big and 2 small cards.

I think it could be fixed by either:

- Changing `CardContainer` so instead of deciding what the layout should be based on the number of cards it has, we instead pass in an enum which switches which layout it uses.

- Just deleting `CardContainer` - The original thought was we would need this on a bunch of screens, but currently its only used in the home screen.  Perhaps we don't even need it.

I would like to get @workerbee22 and @maks thoughts on what would be the best approach

**Comment by lukesleeman** [comment]
Whoever picks this up should be aware that issue #155 also touches these sections of the home screen

Check out issue #155 and see what status if has before its you get too far into this.

**Comment by alessandrofavero** [comment]
I like the idea of enums! @lukesleeman  I can make the change if @workerbee22  and @maks agree

**Comment by workerbee22** [comment]
enum is fine, although there is only one instance of this layout, so lets not get too tricky given we use it once.

**Comment by maks** [comment]
@alessandrofavero yes given that this isn't used anywhere else, I'd say just change the current layout for 3 items to be full width. Pls assign this to yourself if you'll be picking it up to fix.

**Comment by lukesleeman** [comment]
> @alessandrofavero yes given that this isn't used anywhere else, I'd say just change the current layout for 3 items to be full width. Pls assign this to yourself if you'll be picking it up to fix.

If you do this, unfortunately it will break the layout for ICU

![image](https://user-images.githubusercontent.com/902252/78420613-5cac6880-769c-11ea-9afb-a564fc85d6de.png)

I've attached a screenshot of the ICU layout.  I think in this case an enum may be a better solution

**Comment by alessandrofavero** [comment]
@lukesleeman @workerbee22 @maks something like this:

![ezgif com-resize](https://user-images.githubusercontent.com/43284065/78420833-a1d19a00-769e-11ea-9929-a2f101d0f8de.gif)

**Comment by lukesleeman** [comment]
Nice!

**Comment by sallychung** [comment]
✅ v1.0.117

![IMG_102410EF0875-1](https://user-images.githubusercontent.com/12321678/78961074-73870b00-7b33-11ea-83f6-137ed54cd013.jpeg)
