### ISSUE TITLE
PR build status checks currently not working from Codemagic

### ISSUE THREAD

**Issue by maks** [Western-Health-Covid19-Collaboration/wh_covid19_app#16]
I've left a message in Codemagic's slack support channel reporting this and asking for help last night, need to wait til europe wakes up today til I hear back from them.
But for now it means everyone needs to check the status of PR builds on CI manually (failures should be reported in slack channel) before merging into master please :disappointed: 

FYI: @domesticmouse @alessandrofavero  @adamkoch @workerbee22

**Comment by lukesleeman** [comment]
This is sort of working, though as I mentioned in issue #98 it doesn't seem like failed builds are showing up.

Did we want to close this issue and track the failed builds problem by #98 ?

**Comment by lukesleeman** [comment]
I'm closing this issue as most of the discussion is under #98
