### ISSUE TITLE
Intubation - UI Inconsistencies

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#164]
Intubation Guide
- [x] *A* - Title font should be semi bold
- [x] *B* - Subtitle in cells should be grey (Zeplin: #blackAlpha600)
- [ ] *E* - Emojis don’t match Zeplin designs 🤏⚖️

![Simulator Screen Shot - iPhone 5s - 2020-04-04 at 17 33 55](https://user-images.githubusercontent.com/12321678/78420500-6bdee680-769b-11ea-8a34-1f4c0a13fbe1.png)

![Simulator Screen Shot - iPhone 5s - 2020-04-04 at 17 54 43](https://user-images.githubusercontent.com/12321678/78420800-40a9c680-769e-11ea-9d42-a4eb21cecf0e.png)

Intubation Checklist
- [ ] *C* - Title font should be black (Zeplin: #blackAlpha900)
- [ ] *D* - Cell background should be white (Zeplin: #grey500)

![Simulator Screen Shot - iPhone 5s - 2020-04-04 at 17 33 58](https://user-images.githubusercontent.com/12321678/78420498-6aadb980-769b-11ea-960d-88394464aa3a.png)

**Comment by rockgecko-development** [comment]
Item `A,C,D` was fixed by @ericjiang97 in #178 
Item `E` is intentional, as I mentioned under 'things to note' in original issue #133 
Will submit a PR for `B`

**Comment by rockgecko-development** [comment]
I'll leave this for @sallychung  to confirm all is resolved

**Comment by kimngyn** [comment]
@lukesleeman we can close this now?

**Comment by lukesleeman** [comment]
Yep, I think so

**Comment by sallychung** [comment]
✅ Intubation Guide v1.0.115

![IMG_0060](https://user-images.githubusercontent.com/12321678/78894014-a8ea1500-7aaf-11ea-9a87-6c0ff3c5d0ff.PNG)

**Comment by sallychung** [comment]
❌ Intubation Checklist background not white. (#grey50)

![IMG_0061](https://user-images.githubusercontent.com/12321678/78894027-aedff600-7aaf-11ea-8ec8-03671fe8c647.PNG)

**Comment by lukesleeman** [comment]
Owwww, good catch.  This appears to be be because in the sketch file, the colour is called `Colors.grey50` - but its actually not grey at all, its white: 255,255,255

**Comment by sallychung** [comment]
✅ v1.0.160

![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 49 59](https://user-images.githubusercontent.com/12321678/80369113-116b2b80-88d1-11ea-9801-33df1905b19d.png)
