### ISSUE TITLE
Update Information screen & remove Lorem ipsum

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#166]
![Simulator Screen Shot - iPhone 5s - 2020-04-04 at 18 12 28](https://user-images.githubusercontent.com/12321678/78420981-e578d380-769f-11ea-9429-92d5347a29c3.png)

**Comment by cjmlgrto** [comment]
The repo's README's sums up the intent of the app nicely. I've re-worded it a little:

> This app aims to help safeguard the welfare of Western Health anaesthetists working amidst the COVID-19 pandemic by providing the most up-to-date information for time-critical procedures to ensure optimal patient care.

**Comment by kimngyn** [comment]
@greggmiller  is that ok with you?

**Comment by greggmiller** [comment]
Thanks @sallychung and @kimngyn for picking up on this one! Discussed in #172 and probably best we remove it as all the content is going to be elsewhere within the app. 👍

**Comment by lukesleeman** [comment]
I'm putting this in design, for the designers to have a think about what to put in here.  It may still be good to say _something_ though I am not sure what?

> Built with ❤️ by a bunch of volunteers

?

**Comment by cjmlgrto** [comment]
How's this? Tidied this up as well, since some of them will open Flutter's out-of-the-box screens for info about the app, based discussions from #147.

![Information](https://user-images.githubusercontent.com/1712450/78468395-f9354000-775a-11ea-8521-5657929839f0.png)

**Comment by lukesleeman** [comment]
That looks great!  I'm moving this one over to ready for dev, and hiding a bunch of comments, just so its clear what we need to build out in this screen 🙂👍

**Comment by lukesleeman** [comment]
Actually, I just noticed #140 covers the same things.  I'm closing off this issue in favour of issue #140 where things are a bit more fully specified

**Comment by sallychung** [comment]
✅ v1.0.114

![IMG_2ED4A7BD0750-1](https://user-images.githubusercontent.com/12321678/78889945-0b3f1780-7aa8-11ea-9688-25cfd78d3c01.jpeg)
