### ISSUE TITLE
Disclaimer - UI Inconsistencies

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#167]
- [x] *A* - Content needs to be indented for sections under "Please keep in mind” and “WHAC19 does not...”
- [x] *B* - Font colour should be grey (Zeplin: #blackAlpha900, 60%)

![Simulator Screen Shot - iPhone 5s - 2020-04-04 at 18 17 48](https://user-images.githubusercontent.com/12321678/78421091-da727300-76a0-11ea-9bb5-19efa85f4844.png)

**Comment by workerbee22** [comment]
Event though  I did this originally. Happy for another Dev to pick this up as should be straight forward tweaks. 👍

**Comment by lukesleeman** [comment]
I'm adding @workerbee22 in on this - as discussed in tonights call he may be able to address a bunch of these with the theming work he is planning tomorrow.

**Comment by Mattro** [comment]
May I add to this issue?

**Main screen > Info > Disclaimer's** back button is missing on the latest TestFlight build (104). (Tested on iPod touch [iOS 12] and iPhone 11 Pro [iOS 13.4].

<img width="320" alt="image" src="https://user-images.githubusercontent.com/1920449/78660497-8a99e300-7910-11ea-8166-de3c4da8a979.png">

**Comment by workerbee22** [comment]
@Mattro Yep we have an bug logged already. IS actually there but is white on white. https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/195

**Comment by sallychung** [comment]
✅ v1.0.114

![IMG_C5C13404D10D-1](https://user-images.githubusercontent.com/12321678/78890972-f2376600-7aa9-11ea-9f66-a0327dfadf31.jpeg)
