### ISSUE TITLE
Intubation Checklist resets when traversing between tabs

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#171]
**Steps to reproduce**
1. Go to Intubation Checklist 
2. Select cells under Teams
3. Go to any other tab and select cells, ie, Patient
4. Go back to Teams

Expected:
Selected cells should remain selected

Actual:
All cells have been deselected

![checklist_bug](https://user-images.githubusercontent.com/12321678/78424704-0bf83800-76bb-11ea-9f50-0981f7192e2d.gif)

**Comment by lukesleeman** [comment]
Owwwww, good catch!
We wanted it to reset if you leave the page - but probably resetting if you move between tabs is a bit too much!

**Comment by workerbee22** [comment]
Yep tab switching needs to retain state. Easy to do.

**Comment by sallychung** [comment]
✅ v1.0.114

![intu-bug-fix](https://user-images.githubusercontent.com/12321678/78889850-d92db580-7aa7-11ea-9c51-cb3fbbf11075.gif)
