### ISSUE TITLE
Main Screen - UI Inconsistencies

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#173]
- [ ] A - Info button is not aligned to the title
- [ ] B - Content below title is not aligned on the left
- [ ] C - Buttons’s height under Intubation are too tall

![Simulator Screen Shot - iPhone 5s - 2020-04-04 at 21 34 35](https://user-images.githubusercontent.com/12321678/78424969-d6ece500-76bc-11ea-8b3c-fdd784108881.png)

**Comment by lukesleeman** [comment]
I've moved this over to "Ready for dev". - Also just a huge ❤️ for those who have already put in so much effort to polish this screen!  Its getting very close to 💯 ✨ ✨ ✅ 

Keep up the amazing work!

**Comment by workerbee22** [comment]
@sally issues A and B are intentional. A previous PR aligned to the left the content. But @Mattro wanted to leave the AppBa.r title and 'i' for now as standard spacing.

So I think we need designer discussion on this one before its ready for dev. So I've removed 'ready for dev' sorry @lukesleeman but need to discuss with @Mattro

**Comment by Mattro** [comment]
To talk to this a bit. The navbar content can be omitted from the margins stuff - I don't mind where it sits.

**"What the hell are you talking about, crazy designer?"**
I'm glad you asked.

This was done in a mega hurry. I dropped a stock-standard iOS navbar on the top of the design, then removed it's background. Then, I removed it's title. The only thing remaining were it's alignments and right-side icon.

There isn't high design intent or opinion in the way the header is laid out.

In saying this, the margins on the side of the **content view** are: 16pt/dp on the sides. 
The "Western Health" word-mark is part of the content view, and so is the info button.

As it appears here, it is all part of content (no navbar or appbar visible).
<img width="375" alt="image" src="https://user-images.githubusercontent.com/1920449/78465385-51a71600-7738-11ea-94c2-a9821afd5455.png">

The intent is that on scroll, a real navigation bar (or app bar) [appears above it](https://zpl.io/a78vxG8) with a title of "WHAC19" and a right-side info icon. The layout of that element is up to the system. Not up to me.

**Comment by lukesleeman** [comment]
Yeah, I think it all just speaks to how quickly we had to bring the whole thing together!  Damn we moved quick 🙂❤️

So we can get a bit of a conclusion on what way to go with this issue - do people think we need to address Items "A" and "B"?   How much dev effort is involved in changing it?

**Comment by Mattro** [comment]
A: Info button should be top aligned to the wordmark as per Zeplin.
B: Content should sit 16px/pt/dp from the edge, which is the same as aligning it to that logo.
C: Button height is a deliberate 88px/pt/dp. 

Each task is legit.

**Comment by benblackman** [comment]
Hey all, looking great even if there's a couple of little things to polish. 

Just wanted to feedback that on iOS the title bar does a bit of a strobe thing when you scroll (obviously wants to be clear at the top of the screen and white when scrolling down to cover anything underneath) there's evidently a point in the scroll where it can't make up its mind and goes a bit 📸💥🚨 

Video screenshot:
https://wetransfer.com/downloads/c6a6cd1e2b80610803cc2e62a4fd439920200405072717/f40cae1ae1d3295deaf8a69a4cbdba2320200405072717/dda172

**Comment by kimngyn** [comment]
@benblackman I think @mike will deal with that issue

**Comment by benblackman** [comment]
Thanks kim and mike
