### ISSUE TITLE
Information - UI inconsistencies

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#174]
- [x] A - Title is too large
- [x] B - Button height is taller than specified on Zeplin
- [x] C - Margin between buttons are bigger than in Zeplin
- [x] D - Font and color in About section doesn’t quite match
- [x] E - Icon should have rounded corners with more margin around it

Screenshot is on an iPhone 5s so that it’s easier to read in GitHub. Also checked against iPhone 11 Pro Max

![Simulator Screen Shot - iPhone 5s - 2020-04-04 at 21 45 57](https://user-images.githubusercontent.com/12321678/78426825-86c35200-76bf-11ea-8cb6-94851e7472e0.png)

**Comment by workerbee22** [comment]
👍The other thing I've noticed too is Status bar icons are white on white. But I'm raising a separate issue for that tomorrow.

**Comment by workerbee22** [comment]
E - We should use the Flutter classes which will then grab the correct icon for this version of the app ie. the Android or the iOS icon.

Flutter Devs have a look at this API, but we'll need to not use the default UI https://api.flutter.dev/flutter/material/showAboutDialog.html

**Comment by rockgecko-development** [comment]
I think this task might have been superseded by design changes in #140 . Definitely that issue should be checked before making changes here

**Comment by rockgecko-development** [comment]
Luke notes that A,B,C,E are still relevant

**Comment by lukesleeman** [comment]
I'm adding @workerbee22 in on this - as discussed in tonights call he may be able to address a bunch of these with the theming work he is planning tomorrow.

**Comment by rockgecko-development** [comment]
Done in PR #194

**Comment by sallychung** [comment]
✅ v1.0.114

![IMG_CCB1ED3A1CF8-1](https://user-images.githubusercontent.com/12321678/78890899-d59b2e00-7aa9-11ea-8692-f48b014b633d.jpeg)
