### ISSUE TITLE
Your Welfare - UI Inconsistencies

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#175]
- [x] A - Title too large
- [x] B - Phone icon doesn't match design
- [ ] C - Margins needs to be larger
- [ ] D - Font colour should be black (Zeplin #blackAlpha900)

Note: Broken emojis raised as a separate issue #176

![Simulator Screen Shot - iPhone 5s - 2020-04-04 at 22 03 21](https://user-images.githubusercontent.com/12321678/78431475-e110e280-76c0-11ea-9c6a-178cf8514568.png)

**Comment by workerbee22** [comment]
Raises an interesting question. The user base is 90% ish iOS, so we can move to iOS style icons easily without designers have to provide assets, they just choose the standard iOS ones.

**Comment by rockgecko-development** [comment]
`A,B` fixed
For `C`, what should the margin be? The mock doesn't have content for this screen, but every other screen has margins of 16dp, which is what this is currently set to also.
`D` fixed, but I don't see that information in the mock https://app.zeplin.io/project/5e7597a68651056664fb6e53/screen/5e75996b2f9154659ff7e114

**Comment by rockgecko-development** [comment]
Need more info for `C` before this can close

**Comment by rockgecko-development** [comment]
Mock has updated, and the margin is 16dp, same as what is already implemented.

**Comment by sallychung** [comment]
✅ v1.0.115

![IMG_6CCE35EA8037-1](https://user-images.githubusercontent.com/12321678/78893712-1e091a80-7aaf-11ea-9fe4-89f8eb6cf922.jpeg)
