### ISSUE TITLE
Support only iOS 12 and above

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#176]
Emojis aren’t displayed correctly on iOS 11.0.1
- Eat well
- Stay in contact with loved ones
- Avoid unhelpful coping strategies...

Note: This was tested on simulator only as I don’t have a physical device

![Simulator Screen Shot - iPhone 5s - 2020-04-04 at 22 12 46](https://user-images.githubusercontent.com/12321678/78433390-6c8a7380-76c1-11ea-9921-8a18cbcceb7f.png)

**Comment by workerbee22** [comment]
Note everyone that currently we are supporting iOS 9 and above. But we can easily increase that to say 11.

**Comment by lukesleeman** [comment]
@sallychung - are you able to provide any advice about why this may be?  Does the OS not support those emoji we are using?

Do you have any recommendations as to what OS levels on the iOS side we should support?

**Comment by sallychung** [comment]
Some of those emojis used are from later releases. For example, the broccoli was released on iOS 11.1

I’d say probably support from iOS 12 and above? The adoption rate for iOS 13 is quite high sitting at around 77% https://developer.apple.com/support/app-store/

**Comment by lukesleeman** [comment]
👍 As discussed in our call this evening, we can lock the app down to a higher OS version.  I'll update the title of this issue to be "Support iOS 12 and above" and open a different issue up for Android.

**Comment by workerbee22** [comment]
Done in PR https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/184

**Comment by sallychung** [comment]
✅ v1.0.114, TestFlight shows min iOS 12.0

![IMG_BBD85F7BD98A-1](https://user-images.githubusercontent.com/12321678/78889182-88698d00-7aa6-11ea-90fe-81927c11f572.jpeg)
