### ISSUE TITLE
System Bars styling 

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#177]
The status bar on iOS and Android and the navigation bar on Android are usually styled by the system. For example by ensuring contracts and color, icons can always be clearly visible for users.

- **Operating System version variations** - Different versions of iOS and Android take different approaches to ensuring clarity of system and navigation bars, and so the result varies based on the operating system version. On Android different launchers also change this behaviour.

- **App Styling** - Apps can also change the system bar styling for their screens. Flutter automatically tries to set the apps system bar colors and style, based on the colors of certain widgets like AppBars. Apps also change the styling of system bars to re-enforce their brand design.

Currently in our app we have some issues on several screens where typically the status bar icons are not clear:

**iPhones 6 on iOS v12.x**

White status bar icons on white background:

![image](https://user-images.githubusercontent.com/5154664/78463072-30383100-771c-11ea-9eb6-77f1efaefe22.png)

Black status bar icons on black background:

![image](https://user-images.githubusercontent.com/5154664/78463098-67a6dd80-771c-11ea-8b8a-65032d1e58d3.png)

**iPhone 11 Pro Max on iOS v13.3 (simulator)**

Black status bar icons on black background:

![image](https://user-images.githubusercontent.com/5154664/78463197-6629e500-771d-11ea-9256-c3e13609f81b.png)

White status bar icons on white background when scrolling Home screen:

![image](https://user-images.githubusercontent.com/5154664/78463217-907ba280-771d-11ea-98ef-9f2d6eda951b.png)

White status bar icons on white background 

![image](https://user-images.githubusercontent.com/5154664/78463226-ac7f4400-771d-11ea-83d5-44a6be700f44.png)

**Comment by workerbee22** [comment]
Fix for this will resolve a few issues, but due today.

**Comment by workerbee22** [comment]
Done in PR https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/184

**Comment by sallychung** [comment]
✅ v1.0.114

![IMG_497FB1EE73B0-1](https://user-images.githubusercontent.com/12321678/78889088-5a844880-7aa6-11ea-88db-f0b51aa7446b.jpeg)
