### ISSUE TITLE
Disclaimer - Fix capitalisation in content

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#180]
Can we please verify that `anaesthetic`, `critical care` and `clinician` aren’t proper nouns and should be lower case?

![Image from iOS (2)](https://user-images.githubusercontent.com/12321678/78467598-94291c80-7751-11ea-8207-82e11f50c574.jpg)

![Image from iOS (1)](https://user-images.githubusercontent.com/12321678/78467601-97bca380-7751-11ea-9c5d-62aacc3edf05.jpg)

**Comment by lukesleeman** [comment]
@greggmiller are you able to have a look over the disclaimer and give us the 👍 if tweaks to capitalisation @sallychung is proposing are ok to make?

**Comment by greggmiller** [comment]
Yes agreed, they are common nouns and not titles etc. so can be lower case. My mistake, thanks for picking up @sallychung 👍 .

There will probably be some other modifications to disclaimer picked up by others a more medics review, should we wait to change in bulk? or is this a simple fix to flag and correct as an issue?

**Comment by lukesleeman** [comment]
I think this is a really simple one.  I'll assign it over to ready for dev, and somebody an probably knock it off in a few mins

**Comment by sallychung** [comment]
✅ v1.0.114

![IMG_AEA62C9EF3B3-1](https://user-images.githubusercontent.com/12321678/78888943-0d07db80-7aa6-11ea-968f-bfffd5a22d64.jpeg)
