### ISSUE TITLE
Lock android versions down to api 21 and above

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#183]
The app needs to be changed to only support android versions on API 21 and above

The app currently supports some really old versions of Android.  As we are using a lot of emoji this can be a problem (see issue #176 for the problems on the iOS side).  Locking the app to API 21 won't fully fix the issues, however it will mean that we don't have to worry about some of the very oldest devices.  We discussed the issues on this evenings hangouts call and decided that going API 21 and above would be reasonable.

**Comment by workerbee22** [comment]
Done in PR https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/184
