### ISSUE TITLE
Move away from emoji content and towards proper iconography

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#185]
The app currently uses a lot of emoji.  This lets us move really fast, however there are a few concerns that apple may be rejecting apps that use emoji in their UI.  For an example see:
https://blog.emojipedia.org/apples-emoji-crackdown/

In addition OS support for emojis and consistency is not great.  This is particularly an issue on Android where there are a lot of older versions around which don't support new emoji.  In addition a lot of manufactures include their own emoji set, which may have subtly different meanings for some emoji (eg the older samsung 😬 emoji sends a **very different** message to the apple or google one!)

An ideal solution would be to instead use icongraphy which we control.  This is a very, very low priority, and currently not worth worrying about - but perhaps one day we will get there.

**Comment by lukesleeman** [comment]
Issues #176 and #183  show some of the issues we are having with emoji

**Comment by workerbee22** [comment]
Ok the emoji problem I think needs a higher priority. Currently emojis fail because they are not present:
- iOS many emoji are iOS 13.x onwards only
- Android versions also do not have many emoji, and are showing up in the Google Play console reports:

![image](https://user-images.githubusercontent.com/5154664/79709884-b6509c00-8306-11ea-87c3-b6f34ea071c9.png)

**Comment by workerbee22** [comment]
So the core problem here is that by default in Text widgets Flutter uses the default emojis supported on the given os platform and its version at runtime. So for the emojis we use in code, they are shown on some devices and not on others.

There are a couple of solutions:
1. The title of this issue ie. move the designs away from emoji based (my personal preferred)
2. Use an emoji font, and change the code to only use that fonts available emojis
3. Use an emoji package like one of the best ones https://pub.dev/packages/flutter_emoji

**Comment by lukesleeman** [comment]
When chatting to the designers @marcedwards mentioned that the twitter emoji are open source and hopefully would solve the issue:

https://twemoji.twitter.com/

@workerbee22 and @greggmiller I'm unsure if we need this for the V1 release.  What are your thoughts?

**Comment by workerbee22** [comment]
@lukesleeman the open source emojis issues seems like lots of hard work. We can do the exact same thing with flutter emoji package much easier. See previous comments.

Why create emoji assets individually when we can just use a flutter package?

**Comment by lukesleeman** [comment]
Based on our discussions with @greggmiller on the weekend its sounding like this might be something required from WH for us to be able to ship version 1.

We agreed that Gregg would have a crack at moving a small part of a screen over to use icons, probably from font awesome.  Once thats done we should have a better idea of what dev and design work is involved and we can further spec out what needs doing and who will do it 🙂

**Comment by lukesleeman** [comment]
This has now been done - the app is using a new set of icons
