### ISSUE TITLE
Build out Ventilation Infographic screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#188]
In the ventilation screen there is a "PDF" button to link off to an infographic screen.  We need to build out the Ventilation Infographic Screen.  

image: sari_treatment_poster_1.png which is contained in PR #192 
left hand side button: X
Theme: Blue
Title: Ventilation Infographic

**Comment by lukesleeman** [comment]
@greggmiller or one of the @Western-Health-Covid19-Collaboration/medical  - are you able to let us know which documents to use for the 3 ICU infographic screens?

**Comment by greggmiller** [comment]
Hi @lukesleeman 

Ventilation should be this document from ICU: 
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/COVID-SARI%20Treatment%20Poster%202020.pdf

Daily screens won't need an infographic as it is summary of lengthy policies/documents

Cross-skilling - I will log some issues later regarding some of the information to go in there. 

Thanks 😄

**Comment by lukesleeman** [comment]
Awesome, assigning this one over to @marcedwards to get the PDF converted over and into the codebase.

**Comment by marcedwards** [comment]
Should I turn this into two images? If the answer is yes, do we have a plan for how to get to each page? Two buttons?

**Comment by greggmiller** [comment]
The first page should be fine for this @marcedwards 👍 

Some way down the line it might be good to try and build out the infographic screen so that it can slide between a few images but I don't know how challenging this would be.

**Comment by marcedwards** [comment]
Ok. I’ve added both for now (the images are as small as I could get them, so having the second page doesn‘t seem like a bad thing).

**Comment by lukesleeman** [comment]
Ok, I'm moving this over to ready for dev and hiding some old comments

**Comment by sallychung** [comment]
✅ v1.0.114

![IMG_5AD0E52A2290-1](https://user-images.githubusercontent.com/12321678/78888754-a08cdc80-7aa5-11ea-89cd-8a4b0836d084.jpeg)
