### ISSUE TITLE
Replace SVG icons with build in flutter icons

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#189]
Flutter has the ability to use built in icons, which are pre-rendered to a bunch of screen densities - it should be a pretty simple one line of code to use the built in icons.

We should start using the build in icons, and we can remove the SVG ones the designers have provided.

By using the flutter ones, we can also use platform appropriate icons on both the iOS and Android side.

**Comment by lukesleeman** [comment]
I'm moving this one over to @workerbee22 as he has a much better idea of what needs to be done.  Once your happy with it @workerbee22 just move it over to `Ready for dev`

**Comment by workerbee22** [comment]
Sounds good ... was just playing with the standard icon package for ios.

**Comment by kimngyn** [comment]
Yay! I mentioned this at the start of the project lol

**Comment by workerbee22** [comment]
Just so everyone is aware there are two core icon packages, one for material design icons and the other for cupertino icons (list of icons here: https://pub.dev/packages/cupertino_icons).

There are some places in the app where we use SVG and should continue to do so. Like the colors on Home screen background:

![image](https://user-images.githubusercontent.com/5154664/78472810-1bd95000-777f-11ea-9592-128c0e6e6a77.png)
 
But for iOS or Android standard icons, we simply use ONE widget to use each one, or for buttons etc. So this is the very standard approach we'll move to:

![image](https://user-images.githubusercontent.com/5154664/78472765-d583f100-777e-11ea-9e9b-4fa65b52d4b5.png)

**Comment by workerbee22** [comment]
So actions for me on this change is, for standard icons:

- convert to standard Icon widgets or IconButton etc.
- Remove SVG asset from the app and `pubspec.yaml`

At the moment I'll just replace like for like and no-one will be able to tell the difference.

**Comment by workerbee22** [comment]
Look to migrate away from custom SVG icons to Flutter standard icons. This is only for standard icons and not for larger images like the Home screen brand background (green/blue/purple shapes).

The following icons are custom but have iOS and Android standard versions in Flutter:

![image](https://user-images.githubusercontent.com/5154664/78628938-07a96600-78d9-11ea-889f-c09adae33d07.png)

Actions:
- Migrate to standard icon for each (unless one does not exist)
- remove SVG assets

Example of using Flutter standard Icon widgets is already present in the app for the Home screen 'i' information icon:

![image](https://user-images.githubusercontent.com/5154664/78629190-ab931180-78d9-11ea-94d3-b2cf958477c8.png)

Which is implemented in the standard Flutter icon on the IconButton widget:

![image](https://user-images.githubusercontent.com/5154664/78629325-075d9a80-78da-11ea-8ee5-8f47d313f875.png)

**Comment by workerbee22** [comment]
We do just need to confirm if we want to use the iOS standard icons on iOS and the MAterials Design ones on Android? I'm assuming yes?

**Comment by kimngyn** [comment]
I don’t mind Cupertino, but the documentation is already well written for material icons class. Maybe material and then we can get “fancy” later.

**Comment by workerbee22** [comment]
Yeah ... I'm keep to talk to designers tonight before I do this. Because I can just convert SVGs over to Icon() widgets and leave them as Material Design icons.

The other problem though ... when is 'later'? If we work to plan the app will be with many users over the weekend as a 'beta'. 

But things to discuss:
- Material Design icons appropriate for app where 80%+ are iOS?
- How well do we want to fit into each platform?

**Comment by workerbee22** [comment]
Agreed to keep the SVG icon approach.
