### ISSUE TITLE
App Publishing - iOS Apple App Store

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#19]
Setup CI/CD integrated publishing of Release and signed builds of the app for Beta to Test Flight and Apple App Store.

**Comment by workerbee22** [comment]
Once we have Apple Dev Account I can do this, as also includes wiring into codemagic CI/CD.

**Comment by workerbee22** [comment]
We have the Apple Developer account and configs setup with iOS code signing also completed and testing fine.

**Comment by workerbee22** [comment]
Setting up TestFlight and the App Store. We will use TestFlight for all iOS app distributions.

**Comment by workerbee22** [comment]
App Store Connect setup done initially. Waiting for Apple Beta review of the app. Due in 24 - 48h. In the meantime first 2 distributions via TestFlight tested successfully to iPhones 🎉

**Comment by workerbee22** [comment]
Apple App Store Connect Beta Review of iOS app failed. They want more app context. Will get and then re-submit. TestFlight distributions blocked until the BetaReview passes.

**Comment by workerbee22** [comment]
We provided answers to additional info question about intent and audience for the app. APple still reviewing, awaiting updated review result, no ETA at this stage.

**Comment by workerbee22** [comment]
Apple called me and they have things we need to do around the Disclaimer, the apps purpose and audience. But this is only for the production release. Until then we can push out via TestFlight as many Beta releases as we like.

**Comment by workerbee22** [comment]
Beta builds flowing into TestFlight fine and fully automated from codemagic.

**Comment by lukesleeman** [comment]
I'm wondering can we close this one off now?

**Comment by workerbee22** [comment]
@lukesleeman Prefer not to until we have done one full cycle up to the app stores. There is still quite a bit of work to do here before we have actually published to the App Store ... any many things can still get us rejected.

**Comment by workerbee22** [comment]
Currently preparing documentation so the @greggmiller and Western Health can confirm final app store listing information.

**Comment by lukesleeman** [comment]
Since it seems we wont be releasing, I'm closing this one down
