### ISSUE TITLE
Use of Strings class in strings.dart

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#197]
Already partially implemented, but this issue about cleaning up the code to FULLY support the use of a strings file.

### Proposal

Instead of embedding or 'hard coding' string constants in ui code, use a Strings class member instead. The benefits are 

- maintainability as key strings can then be easily changed in one place without touching the ui code itself.
- more readable code

For example for the app name `WHAC19` reference this in ui code as

```
return MaterialApp(
   title: Strings.appName,
```
The `Strings` class defined in `strings.dart` for example the current file:
![image](https://user-images.githubusercontent.com/5154664/78626202-666ae180-78d1-11ea-9ea9-fd09461a05b7.png)

### When to use Strings vs Content Data

In this WHAC19 app the 'data' is essentially the content displayed to the  app users. The content data we use in the app given the pandemic, approvals etc. may be MORE likely to change than Strings. Currently we have this data content embedded into widgets used either:

- in directly embedded in the ui code like this:

![image](https://user-images.githubusercontent.com/5154664/78625749-438bfd80-78d0-11ea-97bd-9afc81ecfff4.png)

- widgets referenced from `hard_data.dart` like this:

![image](https://user-images.githubusercontent.com/5154664/78625830-69190700-78d0-11ea-962d-4cb88236a572.png)

**Propose that the use of Strings does NOT impact on the content data, which is a separate issue. See background in decision [ADR-0002 ](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/master/docs/Architecture/ADR-0002%20Embed%20content%20in%20the%20app.md)**

Suggest using Strings references when:
- semi permanent ui elements like eg. AppBar titles, menu item text, app name etc.
- this may apply to the data in `hard_data.dart` as well
- but this is not a black &  white rule, just a guide.

**Comment by lukesleeman** [comment]
These sound like some sensible suggestions 👍

**Comment by joshcase** [comment]
Great idea. Is this up for grabs @workerbee22 or are you half way down the rabbit hole?

**Comment by workerbee22** [comment]
Almost finished @joshcase . See this PR https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/207

So this one nearly done. But check issues list, still many open.

**Comment by workerbee22** [comment]
Finished today.

**Comment by sallychung** [comment]
@workerbee22 would this require checking the text for every single screen?

**Comment by lukesleeman** [comment]
> @workerbee22 would this require checking the text for every single screen?

I 🤞 _think_ 🤞  it will be ok.  Basically its just a refactoring to pull stuff out from one place in and into another.  Hopefully it was mostly done by the the IDE.

It can't hurt to give things a quick once over, but I think the risk in this one should be low

**Comment by sallychung** [comment]
@kimngyn has found a few more minor copy issues. I think let’s wait till next week, do a final comb and capture the last remaining copy changes in one last issue

**Comment by lukesleeman** [comment]
Yep, that sounds like a really good plan!  Hopefully by then some more of the other ui polish issues will have been merged in as well
