### ISSUE TITLE
Topic in Cross-skilling Section C: ALS/BLS pandemic modifications

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#199]
There are modifications to how we perform Basic Life Support and Advanced Life Support during COVID pandemic.
The intention is that this page summarises those changes in Scrollable stab format.

Title Page: ALS/BLS pandemic modifications

4 scrollable Tabs:
**Principles
PPE
BLS
ALS**

**Principles:**
CPR is an Aerosol Generating Procedure (AGP)!
Your safety is a priority
DO not enter the bed space until appropriate PPE applied
Limit number of responders to essential staff only
Minimise interruptions to compressions
Rhythm check at appropriate times

**PPE**
For COVID-19 proven, suspected or unknown:
- Full PPE including N95 mask

For non-COVID
- please use universal precautions 
          -surgical mask, eye protection and gloves

If unsure:
- Full PPE

**BLS**

COMPRESSION ONLY CPR
DO NOT use airway adjuncts or ventilate with BMV
Apply Hudson mask at 10l O2.

**ALS**

Early Intubation
- Most experienced operator
- Use video laryngoscope
     - McGrath on Code Blue response trolley
    - Intubating anaesthetist will attend where possible
- Viral filter MUST be placed on circuit closest to airway device.
- Airway strategy as per Safe Airway Society/WH guidelines
- If BMV required: 2 handed Vice-like grip.
[BLS modifications v1.1 3rd April.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4442192/BLS.modifications.v1.1.3rd.April.pdf)

@fabiendade 

Infographic tertiary button PDF attached.

**Comment by kimngyn** [comment]
4 Scrollable Tabs:
**Principles**
**PPE**
**BLS**
**ALS**

**Principles:**

CPR is an Aerosol Generating Procedure (AGP)!
Your safety is a priority
Do NOT enter the bed space until appropriate PPE applied
Limit number of responders to essential staff only
Minimise interruptions to compressions
Rhythm check at appropriate times

**PPE**

For COVID-19 proven, suspected or unknown patients:

- Full PPE including N95 mask

For non-COVID-19 patients:

- Please use universal precautions
   - surgical mask, eye protection and gloves

If you are unsure:

- Full PPE

**BLS**

COMPRESSION ONLY CPR
Do NOT use airway adjuncts or ventilate with BMV
Apply Hudson mask at 10l O2.

**ALS**

Early Intubation

- The most experienced operator needs to be present
- Use video laryngoscope
   - McGrath on Code Blue response trolley
   - Intubating anaesthetist will attend where possible
- The viral filter MUST be placed on circuit closest to the airway device.
- Follow the airway strategy as per Safe Airway Society/WH guidelines
- If BMV required: 2 handed vice-like grip.

**Comment by cjmlgrto** [comment]
Before the designers dig into this piece of work— might need a bit of clarification here. Where should this content live inside the app? Will be a tab inside the original Cross-Skilling section described in #43?

Or is this a different screen altogether?

**Comment by greggmiller** [comment]
Hi @cjmlgrto, yes so the plan is that cross-skilling will be a list with various pages that might be an infographic/hyperlink or other scrollable tab feature.

This should live under subdivider C for circulation as it is regarding cardiac arrest.
It should be titled ALS/BLS pandemic modifications and once clicked on opens into scrollable tab described above with infographic on the tertiary button.
  
Hope that makes sense? 😄

**Comment by cjmlgrto** [comment]
Here are the designs for it:

![ALS BLS](https://user-images.githubusercontent.com/1712450/79099423-6d996000-7da7-11ea-883c-f94839610628.png)

Just like #43, these screens will be accessible from the ICU / Cross-Skilling screen:

![Cross-skilling](https://user-images.githubusercontent.com/1712450/79099449-80ac3000-7da7-11ea-9a42-1928d5be8017.png)

**Comment by kimngyn** [comment]
LGTM! only one suggestion

![Screenshot (148)_LI](https://user-images.githubusercontent.com/42886400/79104566-2fee0480-7db2-11ea-9bed-7724d14f0080.jpg)

**Comment by greggmiller** [comment]
@cjmlgrto Yeah this looks really great to me Carlos.
Thanks @kimngyn  for making that one recommendation, I would agree.

**Comment by cjmlgrto** [comment]
Was on the fence about this, but I've decided to remove them. Still the same intent, just a bit cleaner. Thanks @kimngyn!

**Comment by kimngyn** [comment]
@greggmiller  are you ok with this too? 

![Screenshot (164)_LI](https://user-images.githubusercontent.com/42886400/79107624-10f27100-7db8-11ea-9b4b-0bec98de3667.jpg)

**Comment by greggmiller** [comment]
Thanks @cjmlgrto .

This one looks ready for @Western-Health-Covid19-Collaboration/flutter-devs 
@lukesleeman

**Comment by sallychung** [comment]
✅ v.1.0.150
