### ISSUE TITLE
App Publishing - Android Google Play

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#20]
Setup CI/CD integrated publishing of Release and signed builds of the app for Beta to Google Play.

**Comment by workerbee22** [comment]
We have Google Play account and I can do this, as also includes wiring into codemagic CI/CD.

**Comment by workerbee22** [comment]
After discussion with @maks planning on a Google Play setup for 'Beta' versions of the app. Also considering 'Internal' builds of the Android app version, rather than Firebase App Distribution for Android, although that works well.

Need to be careful as Google seems to be much more strict on Covid19 content in Google Play than App is for the App Store.

**Comment by workerbee22** [comment]
Agreed new name as WHAC19 and initial Google Play submission started. Priority for iOS first.

**Comment by workerbee22** [comment]
Google Play Beta release submitted for review. Waiting on Google result, but warning in Google Play console warns of 7+ days review times. So 7 days would make the date expected around Mon 6th April.

**Comment by workerbee22** [comment]
Initial Beta review resulted in App Suspension. Since then @adamkoch talked to people and now it has been removed from Google Play.

Next step is to submit a new Beta release, which should get approved.

**Comment by workerbee22** [comment]
Google Play Beta release re-submited after initial Beta submission/suspension/removal.

Once this is approved, will look to moving 'Alpha' distributions away from Firebase App Distribution to Google Play Internal channel.

**Comment by workerbee22** [comment]
Resubmission in Google Play still no response, but checking that was only done last Sunday:

![image](https://user-images.githubusercontent.com/5154664/78982208-fd9b9780-7b64-11ea-86bc-782afe5a5fcb.png)

And Google Play times are being broadcast at 7+ days ... if that is calendar days, don't expect until Mon 12th April, or if business days thats Wed 14th April.

**Comment by adamkoch** [comment]
FYI, team said should be approved now

**Comment by maks** [comment]
Thanks @adamkoch yes the app is now published on Beta track :tada: Thanks for all your help!!

**Comment by workerbee22** [comment]
@maks We're not done, so prefer to keep this open for a bit longer.

**Comment by maks** [comment]
@workerbee22 what is still left to do?

**Comment by workerbee22** [comment]
Store listing fixups, actually do the Open Beta push of a release and other bits and pieces.

**Comment by workerbee22** [comment]
Fixed language of Store Listing and release notes uploading automatically for codemagic builds, as per [issue 253](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/253)

**Comment by lukesleeman** [comment]
I'm wondering can we close this one off now?

**Comment by workerbee22** [comment]
@lukesleeman Prefer not to until we have done one full cycle up to the app stores. There is still quite a bit of work to do here before we have actually published to Google Play ... any many things can still get us rejected.

**Comment by workerbee22** [comment]
Currently preparing documentation so the @greggmiller and Western Health can confirm final app store listing information.

**Comment by lukesleeman** [comment]
Since it seems we wont be publicly releaseing I'm closing this one down
