### ISSUE TITLE
Intubation - Inconsistent capitalisation

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#202]
**Updated from comments**

**Intubation Guide**
- [x] A Intervene Early -> Intervene early
- [x] B Allocate roles & Share airway -> Allocate roles & share airway plan
- [x] C Use COVID-019 Intubation tray -> Use COVID-019 intubation tray
- [x] D Ensure Viral filter and etCO2 in ventilation circuit -> Ensure viral filter and etCO2 in ventilation circuit
- [x] E use a Spotter -> use a spotter
- [x] F No changes
- [x] G No changes
- [x] H No changes
- [x] I Use Videolargynscope CMAC -> Use videolargyngoscope CMAC

**Intubation Checklist**
- [ ] J Problems Anticipated? -> Problems anticipated
- [x] K ECTO2 trace -> etCO2 trace

![Untitled 001](https://user-images.githubusercontent.com/12321678/78778550-cd29f100-79de-11ea-9b2e-0b6d686ae1be.jpeg)
![Untitled 002](https://user-images.githubusercontent.com/12321678/78778561-d1560e80-79de-11ea-9a42-07420b5e5fc7.jpeg)

**Comment by sallychung** [comment]
@greggmiller can you please review the capitalisation before we update it in Zeplin and assign it for dev?

**Comment by greggmiller** [comment]
A - agree
B- agree and addition of “plan” required. Should read:
“Allocate roles & share airway plan”
C- agree
D - agree V to v and keep etCO2 is best to be universal in app (it stands for end-tidal CO2 i.e. the partial pressure of carbon dioxide (CO2) unexpired breath)
E - agree
F - This is a tricky one, I would probably keep the capitals not as grammatically correct but we want to highlight those as the specific team roles that require PPE.
G - agree, we do want to draw attention to it being Best fitting though, so let’s keep the B unless there is another way to highlight the “Best” that you would recommend - the better masks fit, the better the seal, the less virus there is in the air for us :)
H - As above, etCO2 is the generally approved way.

Please let me know if anything else I can clarify.

Thank you @sallychung and @kimngyn 😄  for your peerless QA and attention to detail! These all make a difference. 🙌

**Comment by kimngyn** [comment]
Sorry @sallychung I forgot to give you this one too! 

![B404E3BF-9CF2-492F-B33E-4EC557B2854A](https://user-images.githubusercontent.com/42886400/78722167-450b0380-796c-11ea-82be-5a59b424f160.jpeg)

**Comment by sallychung** [comment]
**Intubation Guide**
- [x] A Intervene Early -> Intervene early
- [x] B Allocate roles & Share airway -> Allocate roles & share airway plan
- [x] C Use COVID-019 Intubation tray -> Use COVID-019 intubation tray
- [x] D Ensure Viral filter and etCO2 in ventilation circuit -> Ensure viral filter and etCO2 in ventilation circuit
- [x] E No changes
- [x] F No changes
- [x] G No changes
- [x] H No changes
- [x] I Use Videolargynscope CMAC -> Use videolargyngoscope CMAC

**Intubation Checklist**
- [ ] J Problems Anticipated? -> Problems anticipated
- [x] K ECTO2 trace -> etCO2 trace

![Untitled 001](https://user-images.githubusercontent.com/12321678/78778550-cd29f100-79de-11ea-9b2e-0b6d686ae1be.jpeg)
![Untitled 002](https://user-images.githubusercontent.com/12321678/78778561-d1560e80-79de-11ea-9a42-07420b5e5fc7.jpeg)

**Comment by greggmiller** [comment]
Hi @sallychung I was just passing some similar comments to this in #213 & #214 

Thanks! 😄

**Comment by sallychung** [comment]
✅ v.1.0.117

Only thing left is “Use Videolaryngoscope CMAC” -> “Use videolaryngoscope CMAC”
Closing this issue as this is minor and everything else is complete. There will be another comb through for the copy audit that can be captured there.

![IMG_0064](https://user-images.githubusercontent.com/12321678/78960476-88fb3580-7b31-11ea-866d-7da893693d74.PNG)
![IMG_0065](https://user-images.githubusercontent.com/12321678/78960481-8dbfe980-7b31-11ea-94ad-0d2b6b8d11c4.PNG)
![IMG_0066](https://user-images.githubusercontent.com/12321678/78960483-8ef11680-7b31-11ea-8b4f-25048d98a26d.PNG)
![IMG_0067](https://user-images.githubusercontent.com/12321678/78960485-90224380-7b31-11ea-95b4-8734d3c833e5.PNG)
![IMG_0068](https://user-images.githubusercontent.com/12321678/78960487-90bada00-7b31-11ea-87fe-b46041173361.PNG)
![IMG_0069](https://user-images.githubusercontent.com/12321678/78960488-91537080-7b31-11ea-9001-1f2a9434d78c.PNG)
