### ISSUE TITLE
Ventilation vs Daily Rounds - Capitalisation discrepancies

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#203]
Same words are presented different between Ventilation vs Daily Rounds screens

- [ ] **A** Capitalisation - PAO2 vs PaO2
- [ ] **B** Include units? are the values intended? - 55-60 vs 55-70mmHg 
- [ ] **C** Capitalisation - PPlat vs Pplat
- [ ] **D** Include units? Spacing? Capitalisation? Double digit after decimal? - pH > 7.20 vs Ph>7.2
- [ ] **E** Capitalisation - "Lung Protective" with capital p or lower case p? 
- [ ] **F** Capitalisation - "Volume" lower case v? 

![Untitled 003](https://user-images.githubusercontent.com/12321678/78666159-49a6cc00-791a-11ea-986f-7924be01da1d.jpeg)

**Comment by benblackman** [comment]
Thanks Sally

A- Pa please
B- PaO2 is in mmHg, SaO2 is in % (although this is pretty much inferred from context, so wouldn't include if it takes up too much room)
C- either, although actually Plat in subscript would be more accurate 
D- pH doesn't have an additional unit but 2 decimal places would be good. the CO2 is in mmHg
E/F- yes lower case better for both V and P


G- An additional point is that the section header in the daily round "Git" should be 'GIT' for gastrointestinal tract, or just 'Gastrointestinal' if there's enough room

Thanks Sally, really appreciate your eye for detail!

**Comment by sallychung** [comment]
Thanks Ben.
Closing this to spin off as two new issues with updated requirements #228 #230
