### ISSUE TITLE
PPE - UI Inconsistencies

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#206]
- [x] A Donning & Doffing Step by Step - Bullet points text colour should be #blackAlpha900
- [x] B Doffing - Both methods - Warning - Background color in warning should be 236 243 240, text color #blackAlpha900
- [x] C Doffing - Both methods - Warning - Margin between warning and Step 1 is too large
- [ ] D Doffing Method One - Step 5 and Step 3 reversed?
- [x] E Toolbar colours don't match zeplin - donning should be green, doffing should be purple

![image](https://user-images.githubusercontent.com/902252/78951634-29dbf780-7b16-11ea-86c3-c149b50b1916.png)

**Toolbars from zeplin**
![image](https://user-images.githubusercontent.com/902252/78951676-4c6e1080-7b16-11ea-9aef-5141aae0bd19.png)
![image](https://user-images.githubusercontent.com/902252/78951719-71628380-7b16-11ea-994c-5b2fb350276e.png)

**Comment by lukesleeman** [comment]
I'm moving this over to ready for dev.  It also looks like the toolbars on the screens are the wrong colour - over in zeplin they have purple toolbars.  I'll edit the issue description to include this

**Comment by yimingc2** [comment]
For issue D, Zeplin is outdated. The current order in the app is correct.

**Comment by lukesleeman** [comment]
> For issue D, Zeplin is outdated. The current order in the app is correct.

Yep, somehow it slipped between the cracks.  I've got issue #273 to update zeplin

**Comment by sallychung** [comment]
✅ v1.0.160

![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 36 36](https://user-images.githubusercontent.com/12321678/80368001-6017c600-88cf-11ea-91a7-24e8bc0d2a1a.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 37 05](https://user-images.githubusercontent.com/12321678/80368010-6443e380-88cf-11ea-8a37-fdc0fd00b049.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 37 10](https://user-images.githubusercontent.com/12321678/80368012-65751080-88cf-11ea-964f-6063e70fe5d2.png)
