### ISSUE TITLE
ventilation initial actions and adjuncts html pages no longer accessible

### ISSUE THREAD

**Issue by rockgecko-development** [Western-Health-Covid19-Collaboration/wh_covid19_app#210]
The screens created in #54  for #28  are orphaned and no longer accessible. The data is still there at https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/fc52cf761ad7c49f94b23234a442915411c2c3eb/assets/text/icu_ventilation_initial_actions_content.html#L4 and https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/master/assets/text/icu_ventilation_adjuncts_content.html

and https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/8f8eb90f3f4a70d94d86d894b109657a4bc4ab9d/lib/hard_data.dart#L84

and 
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/2fc4eabf5b69ce1e03d64aeaadd3ec6eb5bec743/lib/routes.dart#L23
If this is intentional, these should be cleaned up.

**Comment by lukesleeman** [comment]
Yep, I believe that this code should be cleaned up - now we have the properly designed screens, we no longer need the various placeholders 👍

**Comment by lukesleeman** [comment]
I've put this one over into ready for dev.  @rockgecko-development if you would like to take it just self-assign to the issue.  Otherwise we can let somebody else pick it up over the long weekend 🙂
