### ISSUE TITLE
Basic copy changes  - Intubation Guide

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#213]
On informal peer-review with a colleague we identified several copy changes required in the intubation guide.

**Prepare tab:**

"Allocate roles & share airway" changes to "Allocate roles & share airway plan"

**Pre-oxygenation tab:**

2nd section change "face mark" to face mask"

**Perform**
Change " Inflate cuff before ventilation"
to "Inflate cuff generously before ventilation
- 10ml air"
and remove bottom step "Generously inflate cuff"

**Post-ETT**
Change "Consider placing NG tube"
to "Consider NG tube & in-line suction"

Thanks
discussed with @lukesleeman 
@Western-Health-Covid19-Collaboration/flutter-devs

**Comment by lukesleeman** [comment]
Once this is in the app, we can bounce it back to the designers, to update zeplin

**Comment by joshcase** [comment]
I'll take this and #214 and then advocate for Design tag

**Comment by workerbee22** [comment]
Design tag because designs need updating to reflect this fix.

**Comment by sallychung** [comment]
✅ v1.0.114

![IMG_0054](https://user-images.githubusercontent.com/12321678/78891986-db920e80-7aab-11ea-8843-d2fd81c3b430.PNG)
![IMG_0055](https://user-images.githubusercontent.com/12321678/78891941-c61ce480-7aab-11ea-8033-78cf9031c45e.PNG)
![IMG_0056](https://user-images.githubusercontent.com/12321678/78891948-c9b06b80-7aab-11ea-82fb-068c7f8b0779.PNG)
![IMG_0057](https://user-images.githubusercontent.com/12321678/78891956-cb7a2f00-7aab-11ea-9280-80380d7b14c0.PNG)

**Comment by cjmlgrto** [comment]
Copy's now [synced with Zeplin](https://app.zeplin.io/project/5e7597a68651056664fb6e53/dashboard?seid=5e759b39c50f086fabc23305).
