### ISSUE TITLE
Basic copy changes  - Intubation checklist

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#214]
**Team**
Remove top item : "Anaesthesia contacted if difficulty anticipated"

**Patient**

Change IV access x 2 item to:
"IV access working
- Fluid running"

**Drugs:**
Below Rescue drugs remove "Sugannadex" otherwise remain the same.

**Equipment**
Change top item fro "2 Laryngoscopes (tested)
to "Videolaryngoscope
- blade available
- back-up laryngoscope available"

Change"Airway trolley/bronchoscope outside room" 
to "Difficult airway trolley available"

Change "ETCO2" to "etCO2"

discussed with @lukesleeman 
@Western-Health-Covid19-Collaboration/flutter-devs 

Thanks 😄

**Comment by joshcase** [comment]
Just to be clear, you want to remove Sugammadex as a rescue drug? Why's that? (Asking more as an intern keen on anaesthetics than a developer)

**Comment by workerbee22** [comment]
Design tag because designs need updating to reflect this fix.

**Comment by greggmiller** [comment]
Hi, can we just put this on Hold @joshcase I'm just going to write a significant update on this as our new intubation checklist has come out today.


Josh fair question on Sugammadex, I will answer you in email 😄

**Comment by greggmiller** [comment]
The following copy changes are in addition to above, in the event of a conflict, this information supersedes it...

There are several changes to our intubation checklist as per **WH guideline dated 9th April** (attached).
 
**Team**

Add item: "Communication device checked"

**Patient:**

Change "FIO2" to "FiO2"

Add ? to "Fluid bolus" so now reads "Fluid bolus?"
Add ? to "Pressor infusion" so now reads "Pressor infusion?"

**Drugs:**

Change top item to:
"RSI drugs prepared & doses chosen"

Change "Rescue drugs" to
"Rescue drugs
- Metaraminol
- Adrenaline"

**Equipment:**

Change top item from
 "2 Laryngoscopes (tested)
to 
" 2 Laryngoscopes (1 VL, 1 Mac)"

Remove "Lubricant"

Change "Difficult airway trolley available" 
to "Airway trolley with 3 backup boxes (LMA, Facemask, CICO)"

**Final**

Directly underneath "Suction working"
Add items:
"Tube tie under neck"
"Ventilator +/- BVM functional"

Change "O2 running at 15l/min" to "O2 at 6l/min"

Remove "Oropharyngeal/nasal airways" and
replace with "Clinical waste bin & Mayo table/dirty tray" 

@joshcase Might be ideal if you are able to pick this up?
@Western-Health-Covid19-Collaboration/flutter-devs otherwise someone else can 😄 

The below infographic should replace the intubation checklist infographic available through PDF tertiary button (I will log this as a separate issue).

[9thAprSAS COVID 19 Intubaiton Checklist WH version 1 (1).pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4454169/9thAprSAS.COVID.19.Intubaiton.Checklist.WH.version.1.1.pdf)

**Comment by lukesleeman** [comment]
Ok, I have re-opened this and moved it over to design, for one of our designers to update zeplin

**Comment by sallychung** [comment]
✅ v1.0.114

![IMG_0046](https://user-images.githubusercontent.com/12321678/78891706-66bed480-7aab-11ea-88af-a9f8838aa148.PNG)
![IMG_0048](https://user-images.githubusercontent.com/12321678/78891713-69b9c500-7aab-11ea-86f6-ab6715e8ee17.PNG)
![IMG_0049](https://user-images.githubusercontent.com/12321678/78891717-6a525b80-7aab-11ea-869f-029c8d85bd8c.PNG)
![IMG_0050](https://user-images.githubusercontent.com/12321678/78891720-6aeaf200-7aab-11ea-9e3e-b6e82dcd498a.PNG)
![IMG_0051 2](https://user-images.githubusercontent.com/12321678/78891724-6c1c1f00-7aab-11ea-98b3-011ec233e6b9.PNG)
![IMG_0053](https://user-images.githubusercontent.com/12321678/78891725-6cb4b580-7aab-11ea-8509-06b5c2e11915.PNG)

**Comment by cjmlgrto** [comment]
Done and done. [Zeplin synchronised](https://app.zeplin.io/project/5e7597a68651056664fb6e53/dashboard?seid=5e8b06178874b0220dd36892).
