### ISSUE TITLE
Your Welfare - UI Inconsistencies

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#215]
- [ ] A More spacing between heading and body
- [ ] B Emoji should align to top of each point

![PPE 002](https://user-images.githubusercontent.com/12321678/78782844-fc902c00-79e5-11ea-907c-a9c2bc5171c5.jpeg)

**Comment by lukesleeman** [comment]
I've moved this one over into ready for dev

**Comment by lukesleeman** [comment]
👋 If anybody is thinking of picking this up, be aware that there is a major change for the screen as part of #36  - whoever is doing #36 should also take this issue at the same time
