### ISSUE TITLE
Information - Icon out of date

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#217]
- [ ] **C** Icon needs to be updated to the new red icon ✨ 

![Screenshot (121)](https://user-images.githubusercontent.com/12321678/78783364-dcad3800-79e6-11ea-93ea-9ba66d72ef79.png)

**Comment by workerbee22** [comment]
Working on this today along with other icon fixes.

**Comment by sallychung** [comment]
✅ v1.0.114

![IMG_2ED4A7BD0750-1](https://user-images.githubusercontent.com/12321678/78888248-97e7d680-7aa4-11ea-9c39-72d74ebce9d2.jpeg)
