### ISSUE TITLE
Change intubation checklist infographic

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#221]
The intubation checklist infographic (accessible through tertiary PDF button) requires updating to reflect changes in guidelines form 9th April.

Attached is new infographic.
@lukesleeman @Western-Health-Covid19-Collaboration/designers This might have to go through design first of all prior to devs?

[9thAprSAS COVID 19 Intubaiton Checklist WH version 1 (1).pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4454181/9thAprSAS.COVID.19.Intubaiton.Checklist.WH.version.1.1.pdf)

**Comment by lukesleeman** [comment]
I'll ping @marcedwards on slack and see if he can do the export

**Comment by marcedwards** [comment]
Doing this _right now_.

**Comment by sallychung** [comment]
✅ v1.0.115

![IMG_580A3B581563-1](https://user-images.githubusercontent.com/12321678/78952686-c05de800-7b19-11ea-99dc-db78e6a5e297.jpeg)
