### ISSUE TITLE
Change extubation graphic

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#222]
Attached is updated COVID19 extubation infographic. This should replace extubation infographic as accessible through extubation PDF tertiary button
[8thAprASCAR COVID extubation sequence.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4454189/8thAprASCAR.COVID.extubation.sequence.pdf)

**Comment by lukesleeman** [comment]
I'm assigning this one over to @marcedwards to do his magic 🙂

**Comment by greggmiller** [comment]
This seems to have been resolved in #259 thanks to @marcedwards 👍 
I'll close this one down @lukesleeman
