### ISSUE TITLE
Daily Round - Copy changes

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#229]
B - Breathing/Assessment
- [ ] **A** Fix casing - PAO2? -> PaO2?

B - Breathing/Plan
- [ ] **B** Fix casing, add units - "PA02 > 55-60" -> "PaO2 > 55-60mmHg"
- [ ] **C** Add whitespace - "SaO2 > 88-92" -> "SaO2 > 88-92%
- [ ] **D** Fix casing - "PPlat < 30" -> "Pplat < 30"

G - Git
- [ ] **E** Fix title casing - "G - Git" -> "G - GIT”

![Copy-changes 002](https://user-images.githubusercontent.com/12321678/78954480-b17a3400-7b1f-11ea-933d-170b02294bb7.jpeg)

**Comment by yimingc2** [comment]
Hi @sallychung , in the app, sometimes we use `PaO₂` with subscript 2 and sometimes `PaO2` with simply a `2` besides it. What should we be consistent with?

**Comment by sallychung** [comment]
✅ v1.0.146

Broken emoji will be created as a separate issue

![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 47 00](https://user-images.githubusercontent.com/12321678/79636862-3d462d00-81be-11ea-8ed1-df2fca1d980e.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 47 16](https://user-images.githubusercontent.com/12321678/79636864-3e775a00-81be-11ea-8689-7bbb81b3419d.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 46 09](https://user-images.githubusercontent.com/12321678/79636859-3a4b3c80-81be-11ea-94f9-90a227dd0296.png)
