### ISSUE TITLE
Ventilation - Move title outside of cell

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#233]
Ventilation screens have section headings inside the cell instead out outside it.
This is inconsistent to Daily Rounds and Your Welfare

Note: Recommend doing this task together with #230 if it’s still open

Headings affected
- [ ] **A** Initial Steps - Lung protection
- [ ] **B** Initial Steps - Aims
- [ ] **C** Initial Steps - If deterioritating
- [ ] **D** Adjuncts - If initial stepwise approach fails try

![Screenshot (132)](https://user-images.githubusercontent.com/12321678/78958943-e771e500-7b2c-11ea-947f-b807fd980721.png)

Example
![IMG_B96A6315D47D-1](https://user-images.githubusercontent.com/12321678/78959056-24d67280-7b2d-11ea-973a-94a1a083850a.jpeg)

**Comment by sallychung** [comment]
👋 designers, please let me know if you’re happy to apply this design change

**Comment by cjmlgrto** [comment]
That's a great idea. Keeps it consistent too. I've [updated the design on Zeplin](https://app.zeplin.io/project/5e7597a68651056664fb6e53/dashboard?seid=5e759b3382d3c56689bfe78a) to match.

![Slice](https://user-images.githubusercontent.com/1712450/79037261-a6540080-7c12-11ea-8f67-8710f3666d49.png)

**Comment by kimngyn** [comment]
Title looks nicer, I’m glad you made those changes and decided to capitalise every letter. Honestly wasn’t sure what was best. Great job!

**Comment by greggmiller** [comment]
This looks great @cjmlgrto 👍 

Only suggestion would be after neuromuscular blockade just having:
"NOT first-line management - discuss with ICU consultant" as a bullet point maybe in a lighter font. 
Brevity is the winner here and it's good to reassure staff there is always senior help around 😄

**Comment by cjmlgrto** [comment]
Updated accordingly. Thanks folks! 🙏 

The new set of screens [are on Zeplin now](https://app.zeplin.io/project/5e7597a68651056664fb6e53/dashboard?seid=5e759b3382d3c56689bfe78a).

**Comment by sallychung** [comment]
✅ v1.0.146

![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 43 32](https://user-images.githubusercontent.com/12321678/79636793-ab3e2480-81bd-11ea-8f9c-7c1ddfc41710.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 43 34](https://user-images.githubusercontent.com/12321678/79636795-aed1ab80-81bd-11ea-8d86-9b7b07c78492.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 43 35](https://user-images.githubusercontent.com/12321678/79636796-af6a4200-81bd-11ea-82d9-3662f5e8af0d.png)
