### ISSUE TITLE
UI classes need to be removed from data layer

### ISSUE THREAD

**Issue by maks** [Western-Health-Covid19-Collaboration/wh_covid19_app#238]
For now `hard_data.dart` and the classes within it are our data layer so UI classes like `ReusableCard` have no business being there and needed to be refactored into separate datamodels holding the data, which is displayed by the `ReusabelCard` widgets

**Comment by workerbee22** [comment]
@maks @lukesleeman Yeah agree, this has been out problem of hard coding from the start. I'd prefer data classes, standard UI widget classes and raw data in json or similar.

But timeframe wise this will delay the Beta significantly.

**Comment by lukesleeman** [comment]
Yeah, this is definitely an "after beta 1" thing

**Comment by maks** [comment]
Yeah sorry I should have been more clear, I don't expect this to go into the beta. I'll make a label to make that clear.
