### ISSUE TITLE
Fix flicker with app bar on iOS

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#242]
On iOS the app bar flickers in and out as you scroll up and down

**iOS app bar flicker**
![Screen-Recording-2020-04-10-at-5 43 12-pm](https://user-images.githubusercontent.com/902252/78975945-8e1fab00-7b58-11ea-8205-0cd9fcb3f4bf.gif)

Meanwhile on android the situation is a little bit better, however you still get an un-naturally dark background behind the app bar as you scroll:

**Android app bar black background**

![android app bar 2](https://user-images.githubusercontent.com/902252/78976262-261d9480-7b59-11ea-8633-5f784f22076e.gif)

I _strongly suspect_ this all has something to do with the elevation of the app bar.  It seems to automatically set its self to have a elevation of 0 when it has a transparent background, then once the colour changes as we scroll it jumps to having an elevation of 4dp

I tried to create a PR which fixes the issue:
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/239

However it doesn't seem to solve the problem on iOS.  I'm guessing we will need a more experienced flutter developer to look at the issue.

**Comment by yimingc2** [comment]
I look at the code for this issue. I think the main reason for "Flickering" is because of how we calculate the navi bar background color based on the scroll position.
`AppColors.dynamicAppBarBackground(percentage)`

A quick solution is to disable the bouncing scroll. It can stop the flickering but the navi bar color transition is still not smooth. It starts out too dark. Something wrong with the color calculation.

**Comment by yimingc2** [comment]
Also, I'm not sure if we want to have the iOS Large Title effect here in the first place. If so, we can use `CupertinoSliverNavigationBar` to achieve that which looks more native.

**Comment by workerbee22** [comment]
So we can definitely fix the flicker issue as it is not a flutter bug or constraint. But I just haven't had time to have a closer look. 

So this starts to get us to a key question. Do we want to start having two designs at run time; one for iOS and the other for Android. I've been looking at this generally, but I think we should discuss it as a team before we start doing it in the code.

Flutter can definitely support this very well. But do we want to do this? Designers will have to be onboard. Also related to this [Issue 185 - Move away from emoji content and towards proper iconography](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/185)

**Comment by yimingc2** [comment]
Yeah good point. And also the same for platform icons.

**Comment by yimingc2** [comment]
This is how it usually looks like using Large Title navi bar on iOS. Hope it will help to determine the design.

![LargeTitle](https://user-images.githubusercontent.com/14011195/79101152-4cd30980-7dab-11ea-9cee-7140f06d5207.gif)

**Comment by workerbee22** [comment]
@yimingc2 Yep much more iOS native 👍 ... I think this design discussion is getting much more urgent.

**Comment by workerbee22** [comment]
Fixed !

**Comment by sallychung** [comment]
✅ v1.0.146

![flicker_fix](https://user-images.githubusercontent.com/12321678/79636775-7e8a0d00-81bd-11ea-900c-0c0eb5803c1d.gif)
