### ISSUE TITLE
Enhance flutter section of Readme.md

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#26]
The Readme.md has a section for flutter specific documentation.  Somebody needs to fill it out with some info - as a flutter dev, what do people need to know to checkout and build the project?  

Is it as straightforward as just checking out and clicking run?  Are there any settings or flutter specific things to be aware off.

We will also have a lot fo people who may not be familiar with flutter helping out with this project.  Are there some links and references we can point them at to get started?  How do they downloaded what they need to get started developing our flutter app?

**Comment by lukesleeman** [comment]
Note, we currently have a branch and PR with a few changes to the readme.  You might want to stack on top of that: https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/24

**Comment by ericjiang97** [comment]
Part of #27
