### ISSUE TITLE
Basic Copy Change on Extubation guide

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#260]
In perform tab change: 
"Switch to surgical mask with Hudson or nasal prongs over the top"
to:
"Switch to Hudson or nasal prongs O2 with a surgical mask over the top"

This should be ready for dev.
@Western-Health-Covid19-Collaboration/flutter-devs

**Comment by sallychung** [comment]
✅ v1.0.146

![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 40 09](https://user-images.githubusercontent.com/12321678/79636739-31a63680-81bd-11ea-97df-7f6c1d8a2624.png)
