### ISSUE TITLE
Vertical scroll position of guide items is not maintained when switching tabs

### ISSUE THREAD

**Issue by rockgecko-development** [Western-Health-Covid19-Collaboration/wh_covid19_app#264]
Steps to reproduce:
1. Open any tabbed guide screen with content longer than your screen, eg Proning-> Staff Pre-Manoeuvre
2. scroll down
3. change tab
4. change back

#### Expected:
Staff Pre-Manoeuvre tab should maintain scroll position
#### Actual:
Scroll is reset to top

Related to #204

**Comment by workerbee22** [comment]
Also add analytics tracking of users landing on each tab.

**Comment by sallychung** [comment]
✅ v1.0.160
