### ISSUE TITLE
ICU Cross-skilling/Daily Round: Broken emojis on iOS 12, Android 9

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#268]
Emojis are either displayed as a question mark, incorrectly rendered or different to Zeplin

- [x] **A** Proning/Indication/Contraindications/Haemodynamic instability 🩸-> ⚖️
- [x] **B** Proning/Staff Pre-Manoeuvre/Team - 6x staff available 6️⃣ -> 6
- [x] **C** Proning/Patient Pre-Manoeuvre/Circulation - Check adequate vascular ♥ -> ❤️
- [ ] **D** Proning/Patient Pre-Manoeuvre/Other - Apply padding to bony prominences 🩹 -> TBC
- [ ] **E** Daily Round/B - Breathing/Assessment PAO2? 🩸-> TBC
- [ ] **F** Daily Round/C - Circulation/Assessment Lactate? 🩸-> TBC

![Copy changes 006](https://user-images.githubusercontent.com/12321678/79451849-92513a00-802a-11ea-994e-64fcbd9964df.jpeg)

![Copy changes 007](https://user-images.githubusercontent.com/12321678/79637068-6ca96980-81bf-11ea-8c4a-7ba02c6a97b8.jpeg)

**Comment by lukesleeman** [comment]
Question for @sallychung ... or possibly @greggmiller - can you suggest any alternate emojis we could use for A, B, and D?

**Comment by rockgecko-development** [comment]
I have all 3/4 broken on Samsung S8 Android 9 too.
Emojis in question are:
🩸 6️⃣ ❤️(ok on mine) 🩹
Alternatives might be:
⚖️ 6 ❤️ 
?

**Comment by sallychung** [comment]
yeah should work.

🩸🩹 are only available on Emoji v12 released 2019 https://emojipedia.org/emoji-12.0/

I’ve updated the title and first comment to reflect the changes. 

Not sure what’s a suitable substitute for 🩹... 🤕 doesn’t seem right

**Comment by sallychung** [comment]
Added additional bugs from Daily Round.

**Comment by greggmiller** [comment]
I would say:
Agree with A-B

C could be a syringe as it is about having adequate intravenous access 💉

 D Proning/Patient Pre-Manoeuvre/Other - Apply padding to bony prominences 🩹 -> TBC
could be a bed emoji 🛏️

 E Daily Round/B - Breathing/Assessment PAO2? 🩸-> Could both by syringes too as is blood test
 Round/C - Circulation/Assessment Lactate? 🩸-> Same as above syringe would be adequate if allowed.

Thanks! 😄

**Comment by lukesleeman** [comment]
Thanks for that!  Moving to ready for dev

**Comment by yimingc2** [comment]
> Emojis are either displayed as a question mark, incorrectly rendered or different to Zeplin
> 
> * [x]  **A** Proning/Indication/Contraindications/Haemodynamic instability 🩸-> ⚖️
> * [x]  **B** Proning/Staff Pre-Manoeuvre/Team - 6x staff available 6️⃣ -> 6
> * [x]  **C** Proning/Patient Pre-Manoeuvre/Circulation - Check adequate vascular ♥ -> ❤️
> * [ ]  **D** Proning/Patient Pre-Manoeuvre/Other - Apply padding to bony prominences 🩹 -> TBC
> * [ ]  **E** Daily Round/B - Breathing/Assessment PAO2? 🩸-> TBC
> * [ ]  **F** Daily Round/C - Circulation/Assessment Lactate? 🩸-> TBC
> 
> ![Copy changes 006](https://user-images.githubusercontent.com/12321678/79451849-92513a00-802a-11ea-994e-64fcbd9964df.jpeg)
> 
> ![Copy changes 007](https://user-images.githubusercontent.com/12321678/79637068-6ca96980-81bf-11ea-8c4a-7ba02c6a97b8.jpeg)

Based on the comments above, 
A => ⚖️
B => 6 (which is a plain number)
D => 🛏️
C, E, F =>  💉
Is that confirmed? Thanks!

**Comment by workerbee22** [comment]
Hey team, are we also checking Android version support for these? Because older Android versions have issues still:

See issue [185](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/185) for screenshots of other Android versions with major issues.

Not specifically ICU Cross-skilling/Daily Round, but are we not checking Android prior to version 9?

**Comment by lukesleeman** [comment]
Yeah, I think we are putting older android versions in the "to hard" basket - it sounds like only a small number of our users will be on android, and some of the older ones have _really_ bad emoji support.

For this issue lets just make the suggested substations, but it seems we do need to find a more permanent solution to the emoji problems

**Comment by joshcase** [comment]
Happy to patch this one

**Comment by sallychung** [comment]
✅ v1.0.150

![Simulator Screen Shot - iPhone 5s - 2020-04-25 at 09 52 33](https://user-images.githubusercontent.com/12321678/80265360-ac4de500-86da-11ea-9781-69c722e10127.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-25 at 09 52 38](https://user-images.githubusercontent.com/12321678/80265366-b07a0280-86da-11ea-9b84-dd0ccee24dc2.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-25 at 09 52 48](https://user-images.githubusercontent.com/12321678/80265368-b1129900-86da-11ea-8145-f767ba419954.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-25 at 09 52 58](https://user-images.githubusercontent.com/12321678/80265369-b1ab2f80-86da-11ea-8590-70afb2d75c78.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-25 at 09 53 11](https://user-images.githubusercontent.com/12321678/80265370-b243c600-86da-11ea-9d17-2a715c5279a0.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-25 at 09 53 13](https://user-images.githubusercontent.com/12321678/80265372-b2dc5c80-86da-11ea-90fe-cf2d2e594439.png)
