### ISSUE TITLE
Unresponsive button in Acknowledgements

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#269]
When tapping on “Western Health Department of Anaesthesia”, nothing happens.

It appears the route was not configured to a URL.

![Link](https://user-images.githubusercontent.com/12321678/79452656-d264ec80-802b-11ea-875d-b67d77a17c69.jpg)

![Screenshot (171)_LI](https://user-images.githubusercontent.com/12321678/79452662-d3961980-802b-11ea-841e-3501ebd21247.jpg)

**Comment by lukesleeman** [comment]
@greggmiller can you let us know what the URL is, and then move this over to `Ready for dev` ?

**Comment by greggmiller** [comment]
These are only available on the hospital intranet which would not be accessible externally. 
So the best way might be to link to the microsite which has them: https://whcovid19.wixsite.com/covid19

And amend the subtext from "Policies and procedures" to "Policies and procedures available on the microsite"

**Comment by lukesleeman** [comment]
Moving over into ready for dev

**Comment by sallychung** [comment]
✅ v.1.0.146

![Simulator Screen Shot - iPhone 5s - 2020-04-18 at 21 38 37](https://user-images.githubusercontent.com/12321678/79636719-0f141d80-81bd-11ea-8eda-06139735c173.png)
