### ISSUE TITLE
Update Zeplin PPE screens to match app

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#273]
A while ago a new versions of the PPE Donning and doffing guides were released which re-order some of the steps and add in extra steps for hand hygiene.

We integrated these into the app, however it seems like the zeplin designs never got brought into sync.  One of the @Western-Health-Covid19-Collaboration/designers needs to go through the app, and then update the steps in the PPE screens in zeplin to match what we have in the designs.

**Comment by cjmlgrto** [comment]
Done and done.

![Updated PPE](https://user-images.githubusercontent.com/1712450/80293938-73c80d00-87a7-11ea-8eff-a123795e80bd.png)

**Comment by lukesleeman** [comment]
Great stuff 😄
