### ISSUE TITLE
ALS/BLS Modifications Infographic

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#277]
Under the ALS/BLS Modifications screen, there is a link to an infographic.  We need to add in the infographic.

It should be this PDF: https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/BLS.modifications.v1.1.3rd.April.pdf

**Comment by lukesleeman** [comment]
I've moved this over to @marcedwards in design - @marcedwards can you do your magic and convert the PDF into a PNG.  Once thats done, you can move it over to ready for dev

**Comment by lukesleeman** [comment]
My bad, I didn't realise this one was ready to go!  @rockgecko-development or @yimingc2 do you want to take this one?

**Comment by yimingc2** [comment]
I'll pick it up if nobody does after finish my current one.

**Comment by sallychung** [comment]
✅ v1.0.160

![IMG_9DFC7F9F0301-1](https://user-images.githubusercontent.com/12321678/80368744-8be77b80-88d0-11ea-887a-07399547f417.jpeg)
