### ISSUE TITLE
Build out Subscreens

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#28]
We want to very rapidly build out the sub-screens, and then iteratively enhance them.  To do this we first need sub screens in the app.

As a temporary place holder, we need each of the following screens added in just using a `PageView`.  Sometimes there will be text that just says "TODO" on the sub screen, sometimes there will be an image, with pinch to zoom enabled using a gesture controller.

### Intubation screens

All of these screens have header with the page title, and a green background like this:

<img width="263" alt="image" src="https://user-images.githubusercontent.com/902252/77293399-56ca9500-6d36-11ea-9e5e-f61a34ab5841.png">

I believe this is `backgroundGreen` in `styles.dart`

 **"Intubation Steps" screen**
Text which just says TODO

 **"Intubation Checklist" screen**
Use the file COVID-19_Emergency_Intubation_Checklist.png from the https://github.com/Western-Health-Covid19-Collaboration/source-documents repo
Pinch to zoom on the image.

**"Intubation Algorithm" screen**
Text which just says TODO

### ICU Non Interventionist screens

All of these screens have header with the page title, and a blue background like this:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/902252/77293700-f6882300-6d36-11ea-9055-4d7e0556f693.png">

I believe this is `backgroundBlue`  in `styles.dart` 

**"Ventilation" screen** 
Build screen with two buttons which say:
- Suggested initial actions
- Adjuncts

Style them like this:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/902252/77293820-318a5680-6d37-11ea-9f01-d1b0f51f4890.png">

They will link off to subscreens

**Ventilation - "Suggested initial actions" screen**
A screen with a white card with the folowing text in it:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/902252/77293982-84fca480-6d37-11ea-838a-678669bb3170.png">

This text is taken from COVID-SARI Treatment Poster 2020.pdf in our source documents repo. Please copy and paste from the PDF so you dont make a typo.

**Ventilation - "Adjuncts" screen**
A screen with a white card with the following text in it:

<img width="932" alt="image" src="https://user-images.githubusercontent.com/902252/77294077-aeb5cb80-6d37-11ea-9e8c-ca986a8a6be5.png">

This text is taken from COVID-SARI Treatment Poster 2020.pdf in our source documents repo.  Please copy and paste from the PDF so you dont make a typo.

**"General Care" screen**
Text which just says TODO

**"Tips for junior staffers" screen**
Text which just says TODO

**Comment by suesitran** [comment]
do we have a different design for **"Intubation Checklist" screen**? the image from https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/COVID-19_Emergency_Intubation_Checklist.png can be used in app, but it will not fit nicely in mobile screen

**Comment by lukesleeman** [comment]
Yeah, the designers are working on building out more detailed designs.  This issue is just to rough things in.  I think @DylanLange has already added in that particular image to the app, with pinch to zoom 😁

Proper designs and building a good version of the screen is being tracked in #38

**Comment by lukesleeman** [comment]
👏👏👏👏👏👏👏 I know it looks ugly as all hell, as it hasn't been properly designed yet, but its amazing seeing this in the app.

So excited 😁

Great job everyone!
