### ISSUE TITLE
Emoji’s cut off on the bottom

### ISSUE THREAD

**Issue by sallychung** [Western-Health-Covid19-Collaboration/wh_covid19_app#281]
Emoji’s on the bottom are cut off for some screens. 
Looks like it only happens to the last item of the first section if the text doesn’t wrap multiple lines.

Note: Separate issue raised on emoji alignment #282

Affected:
- [ ] **A** Your welfare/The basics 🗞 Limit new Intake
- [ ] **B** Your welfare//Pre-phase 🔥 "Readiness" burnout
- [ ] **C** Your welfare//Core pahse 😵 Distress
- [ ] **D** Your welfare/End phase 😖 Post-traumatic stress
- [ ] **E** Your welfare/Long term 😖 Post-traumatic stress
- [ ] **F** Cross Skilling/Proning/Staff Pre-Manoeuvre 😮 Able to reintubate?
- [ ] **G** Cross Skilling/ALS/BLS/PPE ☣️ Full PPE

![Copy changes 008](https://user-images.githubusercontent.com/12321678/80266410-1072a800-86df-11ea-9811-8516271bb846.jpeg)

![Copy changes 009](https://user-images.githubusercontent.com/12321678/80266414-149ec580-86df-11ea-83a6-a0964f416e15.jpeg)

**Comment by lukesleeman** [comment]
Wow, good catch!  @sallychung is this on on specific devices or font sizes?   I'm looking at it on my pixel 2, with normal font sizes and it looks ok

**Comment by sallychung** [comment]
Both on iPhone 6 (iOS 12) and iPhone 8+ (iOS 13)

**Comment by workerbee22** [comment]
Need to move away from emojis as per [issue 185](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/185)

**Comment by yimingc2** [comment]
This might also relate to 
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/282

When I press the phone icon and then navigate back, the bottom is not cut off. Also when I'm in Dart dev tool "select widget mode", it displays properly.

@workerbee22 , I don't know if this is a flutter bug. Thinking if it can be an easy fix, we go for it otherwise leave it as it is, as it will be removed in the future anyway.

**Comment by workerbee22** [comment]
@yimingc2 Yep seeing the same behaviour ie. it does render correctly for a given emoji sometimes but not others. 

So yep on iPhone 6 with iOS v12.4.6 (latest v12 release) emoji cut off:

![image](https://user-images.githubusercontent.com/5154664/80294631-197e7a80-87ae-11ea-9b53-427928168323.png)

But does render correctly in a debug paint, with the containing widget allowing for the height of the emoji being greater than the Text:

![image](https://user-images.githubusercontent.com/5154664/80294687-62363380-87ae-11ea-94f1-d92d0c611188.png)

**Comment by workerbee22** [comment]
@yimingc2 My guess is it is a flutter bug. Perhaps upgrade you flutter locally to say v1.17 (latest beta channel) and see if we still have the issue on iOS with emojis cut off.

**Comment by yimingc2** [comment]
> @yimingc2 My guess is it is a flutter bug. Perhaps upgrade you flutter locally to say v1.17 (latest beta channel) and see if we still have the issue on iOS with emojis cut off.

Hi @workerbee22 , I've tried v1.17 but it still doesn't help. One way to "dirty" fix it is to increase the font size from 17 to 22 so that the emoji bottom will not bu cut off.

Also, after increase the title size, the issue of alignment is not that obvious......I know this bit hacky

<img width="410" alt="Screen Shot 2020-04-26 at 1 13 56 pm" src="https://user-images.githubusercontent.com/14011195/80296659-4cca0500-87c0-11ea-9fc9-eb8f826734d2.png">

**Comment by sallychung** [comment]
✅ v1.0.160

![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 46 49](https://user-images.githubusercontent.com/12321678/80368845-b89b9300-88d0-11ea-92d3-ad55ebb8e0b0.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 46 52](https://user-images.githubusercontent.com/12321678/80368854-bc2f1a00-88d0-11ea-9ecf-440f5aa7d21e.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 46 56](https://user-images.githubusercontent.com/12321678/80368861-bcc7b080-88d0-11ea-87af-bf148a32b0c1.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 46 58](https://user-images.githubusercontent.com/12321678/80368865-bdf8dd80-88d0-11ea-9bff-8e07cdcc0d4e.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 46 59](https://user-images.githubusercontent.com/12321678/80368872-be917400-88d0-11ea-9278-626b0ea1cfbb.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 47 12](https://user-images.githubusercontent.com/12321678/80368874-bf2a0a80-88d0-11ea-90f1-e2e686001006.png)
![Simulator Screen Shot - iPhone 5s - 2020-04-27 at 21 47 18](https://user-images.githubusercontent.com/12321678/80368877-bf2a0a80-88d0-11ea-9e0b-20d889b1eae8.png)
