### ISSUE TITLE
Update infographics for Version 1

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#284]
@greggmiller Has some updated infographics which need integrating into the app for version 1.

**Comment by lukesleeman** [comment]
@greggmiller can you provide the updated infographics, and then we will get them integrated into the app

**Comment by lukesleeman** [comment]
Just FYI, whoever takes this will need to work on dealing with multiple page infographics - during the call we decided to handle them like a normal PDF viewer - eg, page 2 just appears vertically after page1, etc

**Comment by greggmiller** [comment]
For Intubation Guide PDF tertiary button
[Intubation_Guide_Infographics_Multipage.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4569501/Intubation_Guide_Infographics_Multipage.pdf)

@Western-Health-Covid19-Collaboration/designers I think maybe @marcedwards was going to take a look?

**Comment by greggmiller** [comment]
Similar for extubation...

[Extubation_Guide_Infographics_Multipage_3rdMay.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4569506/Extubation_Guide_Infographics_Multipage_3rdMay.pdf)

**Comment by lukesleeman** [comment]
@greggmiller I assume you want all the pages from these PDFs?

**Comment by greggmiller** [comment]
Yes please 👍

**Comment by lukesleeman** [comment]
@marcedwards - during tonights call we had some discussion about the current PNGs we are embedding in the app - we have had a lot of trouble trying to get multiple pages ( see all the comments on this PR: https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/302 )

@rockgecko-development managed to find a way to embed PDFs directly in the app, do it turns out we no longer need to convert the PDFs to PNGs! 

I'll un-assign you from this issue 🙂

**Comment by marcedwards** [comment]
Ok, great!

**Comment by marcedwards** [comment]
If we want to trim the PDFs down to remove unneeded pages, or crop out certain details, I can help with that.

**Comment by greggmiller** [comment]
Sorry I have had to reopen this for 2 final updates for infographics (intubation guide and ALS/BLS modifications to ensure they are up to date at time of release.)

Both located in source documents:

https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/08052020_Intubation_Guide_Infographics_Multipage.pdf

https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/08052020_BLS_ALS__PPE_Infographic.pdf

Wondered if @rockgecko-development had time to do this or any other @Western-Health-Covid19-Collaboration/flutter-devs 

(I tried to do this myself while updating other copy but I managed to break the local build 😞).

[08052020_Intubation_Guide_Infographics_Multipage.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4597501/08052020_Intubation_Guide_Infographics_Multipage.pdf)
[08052020_BLS_ALS__PPE_Infographic.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4597505/08052020_BLS_ALS__PPE_Infographic.pdf)

**Comment by lukesleeman** [comment]
I think that the PPE screens just currently have single PNG pages in them, so whoever picks up this task will need to convert them over to using the PDF viewer that @bramt built up for the inbutation and extubation screens

**Comment by marcedwards** [comment]
Just to confirm, I think there’s two changes we’re after.

### 1. Update `airway_management.png`

Update `airway_management.png`, using page 1 from  `08052020_Intubation_Guide_Infographics_Multipage.pdf`.

I can see differences between what we have now, and the new version in the PDF.

- Do we want the “High risk patient and high risk AGP” legend?
- Do we want the “Piror to entering intubation…” text?

### 2. Update `bls-modifications.png`

Update `bls-modifications.png`, using page 1 from  `08052020_BLS_ALS__PPE_Infographic.pdf`.

- These look identical to me. Am I missing something?

**Comment by lukesleeman** [comment]
> Just to confirm, I think there’s two changes we’re after.
> 
> ### 1. Update `airway_management.png`
> Update `airway_management.png`, using page 1 from `08052020_Intubation_Guide_Infographics_Multipage.pdf`.
> 
> I can see differences between what we have now, and the new version in the PDF.
> 
> * Do we want the “High risk patient and high risk AGP” legend?
> * Do we want the “Piror to entering intubation…” text?
> 
> ### 2. Update `bls-modifications.png`
> Update `bls-modifications.png`, using page 1 from `08052020_BLS_ALS__PPE_Infographic.pdf`.
> 
> * These look identical to me. Am I missing something?

Ok, sorry for the misunderstanding there @marcedwards  - In both of those screens we will replacing the PNGs with PDFs - so we don't need any PNGs updating.

In our call tonight @greggmiller said he will try and make the changes and PR them tommorow

**Comment by marcedwards** [comment]
Ok, sounds great! Those PDFs are 4.8 MB and 2.3 MB though. We’ll need to be a little careful with bundle size, I think?

**Comment by lukesleeman** [comment]
> Ok, sounds great! Those PDFs are 4.8 MB and 2.3 MB though. We’ll need to be a little careful with bundle size, I think?

Good point.  Is there any magic you are able to do in terms of optimising PDF size?

**Comment by greggmiller** [comment]
I'm just about done with making the changes, current issue is some that are landscape orientation are reverting to portrait... So I may need to fiddle a bit more when clear-headed in the morning prior to submitting PR.

Happy to be advised on file size 😄

**Comment by greggmiller** [comment]
Updated in #335

**Comment by greggmiller** [comment]
There was a slight issue with aspect ratios and sizing for PDF pages in landscape other than portrait but it should be fine for current version. There was nothing in source documents related to package online that seemed to offer a solution 😕 .
