### ISSUE TITLE
Home and information screen changes

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#288]
There are some modifications that need to be made to the home and information screens to better surface information:

- [x] Add new information section to home screen
- [x] Add phone icon to home screen
- [x] Update information screen, removing items
- [x] Add "last updated date" to the information screen
- [x] Add contributors under the Acknowledgements and references

# Add new information section to home screen
A new "information" section needs to be added to the home screen, after the ICU section.  It should contain two new buttons

**WH Definitive resources**
This needs to lead to a subscreen which has the first 3 buttons from the current information page.  These are:

1. WH Novel coronavirus website
2. WH anaesthetic microsite
3. WH ICU microsite

**Additional resources**
This is the screen which the existing "Additional resource" button in the existing information screen leads to

# Add phone icon to home screen
On the home screen, we need to add a new phone icon to the right of the current "information" icon.  The phone icon should take you to the website which the existing "Contact numbers" button in the existing information screen leads to ( http://wh.cyphix.net/ )

# Update information screen
The first 5 buttons in the information screen can now be removed.  The only items remaining on the information screen should be:

- App feedback
- Disclaimer and conditions of use
- Acknowledgements and references
- Third party licenses
- WHAC19 Icon to remain present

# Add "last updated date" to the information screen
So that users can gauge how up to date the information in the app is we need to show the date their build was created.  Hopefully this should be prominently displayed close to the app icon, in the information screen.  Given the info screen has been re-ordered it might even be nice to give it a little more ✨  by moving the icon around or otherwise shuffling around things.

From a coding point of view, ideally this date should be based off the build time, so we don't have to update a string every time we do a release.

# Add contributors under the Acknowledgements and references
We want to add a new section to the Acknowledgements and references screen which lists all the contributors ❤️

**Comment by lukesleeman** [comment]
@greggmiller Do you just want to double check I got all this correct, then we can move it over to design?

**Comment by cjmlgrto** [comment]
Here's a pass at the design based on the requirements for now — can update after @greggmiller double-checks the info above.

## Updated - Main Screen

![Main](https://user-images.githubusercontent.com/1712450/80293479-1336d100-87a3-11ea-9e54-bd3a0fcfab7a.png)

* A new section called "Resources" is added under "ICU"
* A phone button has been added in the app's top Navigation/App Bar

## Added - Resources section

![Resources](https://user-images.githubusercontent.com/1712450/80293491-234eb080-87a3-11ea-8139-c04425e7d9c5.png)

* Purple500 has been updated in the Style Guide (for this section's new background color)
* Tile colors updated

## Updated - Information Screen

![Info](https://user-images.githubusercontent.com/1712450/80293511-5a24c680-87a3-11ea-9cae-31774b86e5fe.png)

* Much more condensed Information screen
* Added "Last Updated Date" under the app version number
* Contributors now added inside the "Acknowledgement and References" screen

~P.S. I'll add these screens to Zeplin only after these designs get reviewed.~ They're on Zeplin now.

**Comment by greggmiller** [comment]
This looks great Carlos 👍 💯

**Comment by kimngyn** [comment]
It looks very nice @cjmlgrto 🤩 great work!

**Comment by lukesleeman** [comment]
Amazing!  I've moved this over to ready for dev!

**Comment by workerbee22** [comment]
Looks good @cjmlgrto ...very on brand 👍But can I suggest separate Acknowledgemets and References into separate screens ? It seems a bit long and is mixing the content types when combined?

**Comment by cjmlgrto** [comment]
You’re right @workerbee22 — I might break out References into its own screen

**Comment by yimingc2** [comment]
Hey @cjmlgrto, the background color of the WH Definitive Resource is #purple500 (158 118 161) as described in Zeplin while in the codebase our purple500 is (139, 81, 144) which is much darker than Zeplin. Well I think I'll just update the codebase to be the correct rgb.

**Comment by yimingc2** [comment]
And also, regarding to the new Additional Resources Page, we don't have Header Text style with **white color** at the moment in the design and codebase so I'll leave it as black which is `textH4` in the codebase.

**Comment by cjmlgrto** [comment]
@yimingc2 yeah, I’ve decided to change purple500 to be a much lighter color. Please change it theme color in the code base so it updates everywhere 😄

Also, is there no way to override textH4 to be white just for this screen? 🤔

**Comment by yimingc2** [comment]
> @yimingc2 yeah, I’ve decided to change purple500 to be a much lighter color. Please change it theme color in the code base so it updates everywhere 😄
> 
> Also, is there no way to override textH4 to be white just for this screen? 🤔

Technically this is not difficult. Do you think we should make this as a style or put it inline in the code? Something like `textH4Dark` and `textH4Light`

**Comment by lukesleeman** [comment]
> > @yimingc2 yeah, I’ve decided to change purple500 to be a much lighter color. Please change it theme color in the code base so it updates everywhere 😄
> > Also, is there no way to override textH4 to be white just for this screen? 🤔
> 
> Technically this is not difficult. Do you think we should make this as a style or put it inline in the code? Something like `textH4Dark` and `textH4Light`

I'm not a flutter expert, but good software engineering say:  Make it a style so we can reference it everywhere and change it in one place 🙂

@cjmlgrto With splitting the "References" and "Acknowledgements" into two difference screens, is this something you wanted to do in zeplin?  Or should we just go ahead and develop it, then you can update zeplin later?

**Comment by lukesleeman** [comment]
Also @yimingc2 when you implement this, be aware that @greggmiller has already make some copy changes to the homescreen as part of:

https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/292
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/296

Don't overwrite Greggs work :-)

**Comment by lukesleeman** [comment]
> ~P.S. I'll add these screens to Zeplin only after these designs get reviewed.~ They're on Zeplin now.

@cjmlgrto I'm looking and I can see the resources section, but not the updated main screen - am I missing something?

**Comment by lukesleeman** [comment]
Looks like we still have to put a "last updated date" on the information screen.  This can be the time the build was produced.  @yimingc2 do you know how to implement this, or will you need some help from @workerbee22  ?

**Comment by lukesleeman** [comment]
Just recording some implementation hints we got:

![image](https://user-images.githubusercontent.com/902252/81168622-af9a7800-8fda-11ea-873d-de83660d5a7e.png)

**Comment by sallychung** [comment]
✅ v1.0.184
