### ISSUE TITLE
Update app copy

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#290]
@greggmiller Needs to go through and do a bunch of minor copy updates to most of the screens in the app.  As Gregg can write Flutter code, this will be a DIY job 🙂

This issue is to track his progress:

- [x] Home screen button text
- [x] PPE Technique
- [x] Your welfare
- [x] Airway intubation guide
- [x] Intubation guide (including updating emoji)
- [x] Intubation checklist
- [x] Extubation guide 
- [x] Ventilation
- [x] Daily round
- [x] Cross skilling

There is a lot of checking that needs to be done, and changes that we don't yet have written down, but the areas that we know about are:

**Home screen button text**
- PPE technique button change subtext copy to “Basic ICU technique"
- Your welfare change subtext copy to “Info for mental well-being"
- Change "Step by step guide" to "WH Step by step guide"
- Ventilation subtitle to be "Basic ARDS strategy"
- Daily Round to “Daily Ward Round" and change subtext to “Basic A-G template" 
- Change Cross-skilling to “Quick ICU tips” and change Subtext “for COVID-19"

**Intubation guide**
  - Update emojis to something better than the ☑️ - Perhaps we could take some inspiration from the other sections which have good emoji choice
  - Copy changes, Gregg knows what to do
 - Update infographic - this is tracked by issue #284 

**Intubation checklist**
  - Copy changes, Gregg knows what to do
 - Update infographic - this is tracked by issue #284 

**Extubation guide**
- Copy changes, Gregg knows what to do

**Ventilation**
- Needs peer review

**Daily round**
- Needs peer review

**Cross skilling**
- Needs peer review

**Comment by greggmiller** [comment]
First part of this patched in #296 

More to follow for changes to Intubation guideline later/tomorrow. 👍

**Comment by greggmiller** [comment]
#320 for new items to ICU quick training

**Comment by greggmiller** [comment]
All changes completed in #334
