### ISSUE TITLE
Updated infographic for Intubation checklist

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#297]
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/WHIntubationTeamGuidelinesv6.pdf

Hi @Western-Health-Covid19-Collaboration/designers 
Page 9 (Appendix 2) is new image required required for Intubation Checklist.

**Comment by sallychung** [comment]
✅ v1.0.160

![IMG_9DFC7F9F0301-1](https://user-images.githubusercontent.com/12321678/80369005-ebde2200-88d0-11ea-8692-dfb7b10031e8.jpeg)
