### ISSUE TITLE
Fill out the GDPR section in the firebase project and the DPA section in sentry.

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#300]
In the firebase project there is a GDPR section, where we need to nominate a data protection officer

![image](https://user-images.githubusercontent.com/5154664/80454958-39f53300-896e-11ea-8b47-80612abae315.png)

Sentry somebody needs to login and accept something called the DPA:
https://sentry.io/security/

> If you are a Sentry user, you can find the DPA under the Legal & Compliance section of your home page within the Sentry app. Complete it by:
>
> 
> - Reviewing and accepting the DPA itself
> - Adding your designated EU Representative’s info
> - Adding your designated Data Protection Officer’s information
> - Double-checking your company details (specifically, the legal name of your business)

Unless Western Health has an existing Privacy Officer, we suggest @greggmiller is best placed to be the nominated person

**Comment by lukesleeman** [comment]
I've assigned this issue over for @greggmiller and @workerbee22 to complete - it should only be 10 min to log into the two websites and click the buttons

**Comment by workerbee22** [comment]
@greggmiller can you please confirm the detail for you as the **Data Protection Officer** ? That is these fields:

![image](https://user-images.githubusercontent.com/5154664/81042215-f90f9800-8ef2-11ea-80da-ad7481d13363.png)


@maks Not sure I have the Sentry console access, are yuo able to do same for Sentry?

**Comment by greggmiller** [comment]
@workerbee22 has all the relevant information, so we can close this one now? @lukesleeman

**Comment by workerbee22** [comment]
@greggmiller Firebase project Data Privacy setup with the details you sent. But i still can't get to the Shared vault in 1Password. So perhaps @maks can do the Sentry console similar.

**Comment by lukesleeman** [comment]
😅I've filled in the sentry details and can confirm this is also setup correctly in firebase ✅
