### ISSUE TITLE
Build settings screen which explains what data we gather and allows opt out

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#301]
As part of our push to Make app GDPR compliant + better inform our users about what data is gathered  ( #241 ) we need to build a settings screen, under the info icon, that clearly explains what data we gather, what its used for and provides a switch to opt out.   The opt out switch will disables analytics and Sentry.

In terms of what we gather and why:

- Analytics on how the users are using the app with, gathered with google analytics
- Crash reports gathered with Sentry
- We gather this information to help is improve the app.  We hope to understanding what our users are using the app for, as well as proactively address any crashes that come up.

When users opt out, we can disable analytics by calling [setAnalyticsCollectionEnabled](https://pub.dev/documentation/firebase_analytics/latest/firebase_analytics/FirebaseAnalytics/setAnalyticsCollectionEnabled.html) 

With sentry @workerbee22 has some ideas on how we can disable crash reports

**Comment by cjmlgrto** [comment]
And here's the design for that [on Zeplin](https://app.zeplin.io/project/5e7597a68651056664fb6e53/dashboard?seid=5e759a2469655666b6e39917) 😄 

![Privacy](https://user-images.githubusercontent.com/1712450/80593762-1660e400-8a65-11ea-8118-707402c1f204.png)

Also heads up, the spacing between the tiles on the parent Information screen on the left has been updated to be `8pts` so it's consistent with the rest of the app.

And another thing— it'd be great if the controls (like the toggle on the screen on the right) was tinted to use `green500` as the accent for it all throughout the app.

**Comment by workerbee22** [comment]
Just a thought .... if we are going to call the page Privacy we should really provide all of the privacy information. At the moment we are using the following link on the app stores as the Privacy Policy:

http://www.westernhealth.org.au/PatientsandVisitors/Medical_Records/Pages/default.aspx

So it just seems we should add that to the page? Because without it ... seems 'incomplete' ?

**Comment by workerbee22** [comment]
Suggest we should tweak the wording a bit too to future proof it and make it shorter and more direct, something like:

The app gathers general usage information to help improve the app via analytics and crash & error reporting. No personal identifiable information is gathered and you can opt out of analytics and error & crash reporting at any time.

Analytics, crash & error reporting collection BUTTON

Thoughts?

**Comment by workerbee22** [comment]
Also thinking .... title of the switch and the switch at the top of a card? With explanatory text underneath it (but on the same card) in grey? Seems weird to have just text on a separate card?

This would match @rockgecko-development s subtitle for Page x of y o the infographic screens and the sub titles at the bottom of the cards on the home screen.

Something like this:

![image](https://user-images.githubusercontent.com/5154664/80666289-20272d80-8adf-11ea-9a7a-c98643b048ab.png)


Thoughts?

**Comment by lukesleeman** [comment]
👋 Hey, just wanted to get @cjmlgrto's thoughts on the design changes proposed by @workerbee22 

With the copy that mike suggested:


> The app gathers general usage information to help improve the app via analytics and crash & error reporting. No personal identifiable information is gathered and you can opt out of analytics and error & crash reporting at any time.

I'm generally happy with that, though I would like to specifically mention that we use google analytics and sentry, with links off to them, so that people can make up their own minds.  Some people may have strong feelings about google as a company for example, where as they would be happy with another analytics provider - dito for sentry.  So its probably important to mention specifically who they are

With the Re-jigging the screen to have the switch at the top, then text below outside of a card, thats actually what I originally mocked up in keynote:

![image](https://user-images.githubusercontent.com/902252/80667662-1d2e3c00-8ae3-11ea-95ac-644efd8de1ed.png)

However @cjmlgrto altered it into the current design - I'm guessing there were some reasons why he made these alterations?

**Comment by workerbee22** [comment]
To be honest I disagree. I think the specific product being used is an unnecessary distraction ... and I don't see any other apps doing that? But if we decide to keep them, we have analytics events for all links used throughout the app (unless turned off with this switch 🤣) so we'll know if anyone clicks on them.

**Comment by cjmlgrto** [comment]
@lukesleeman / @workerbee22 — updated based on the above discussion:

![Simpler](https://user-images.githubusercontent.com/1712450/80690657-7792c100-8b12-11ea-97b3-87f22bc5a43d.png)

Much simpler.

**Comment by lukesleeman** [comment]
I see @workerbee22 has given the 👍   - does this mean we are good to go?

**Comment by workerbee22** [comment]
Yep ok let's go with that ... is Ready for Dev. Because it is also a little tricky as the setting needs to be stored, but read from storage before the app starts and we assign sentry to trap Flutter errors ... so there is a bit of app restructuring to do for app startup.

**Comment by lukesleeman** [comment]
Moving over to ready for dev!  As discussed in tonights call we will assign this one over to @workerbee22 as its actually got a few tricky architectural things to disable sentry.

**Comment by workerbee22** [comment]
So this is done and working. Feel free to checkout this PR branch. and test.

Still WIP because discussing implementation details with @maks and @rockgecko-development because it sets a kind of precedent for future changes. So want their agreement before I finish it.
