### ISSUE TITLE
Stores Image Assets

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#303]
We need some Apple App Store and Google Play store listing assets for the app. Would be nice to have a perspective view of app o device frame, but either way need some design work on there. For example, COVIDSafe app image assets:

- Google Play - 3 x Android phone assets in portrait, with the option for more
- App Store - 3 app previews + 10 screenshots in portrait, with the option for more

![image](https://user-images.githubusercontent.com/5154664/80668693-db52c500-8ae5-11ea-82d3-4cb528a11541.png)

**Comment by lukesleeman** [comment]
Is this something one of the @Western-Health-Covid19-Collaboration/designers can pick up?

**Comment by lukesleeman** [comment]
Its sounds like @marcedwards is handling this one, so I'm assigning to him 🙂. Thanks Marc!

**Comment by marcedwards** [comment]
Not a problem. I can do it. I think the first step might be to decide which screens should be featured, and work out the accompanying text.

**Comment by lukesleeman** [comment]
> Not a problem. I can do it. I think the first step might be to decide which screens should be featured, and work out the accompanying text.

Yeah, happy to go with both your and @workerbee22 suggestions on which screens are the best ones to feature and what has the most ✨

**Comment by workerbee22** [comment]
Perhaps these screens screens 'look' the best/most interesting? But really @greggmiller should decide.

- Home
- PPE step-by-step
- Your Welfare
- Ventilation
- Additional Resources

**Comment by marcedwards** [comment]
That list looks great, and I agree the final call should be @greggmiller’s!

**Comment by lukesleeman** [comment]
Just an update on time frames @marcedwards  - we are thinking we will have screenshots with final copy in them for you sometime this weekend

**Comment by lukesleeman** [comment]
@marcedwards here are the screenshots:

# Home
![image](https://user-images.githubusercontent.com/902252/81472201-d0143d80-9239-11ea-8283-46f5fff31807.png)

# PPE step-by-step
![image](https://user-images.githubusercontent.com/902252/81472227-ea4e1b80-9239-11ea-8897-dbc6fde7403a.png)

# Your Welfare
![image](https://user-images.githubusercontent.com/902252/81472232-f508b080-9239-11ea-9e36-1a3ee962cdba.png)

# Ventilation
![image](https://user-images.githubusercontent.com/902252/81472236-fe921880-9239-11ea-9be7-b807c659ce56.png)

# Additional Resources
![image](https://user-images.githubusercontent.com/902252/81472242-0a7dda80-923a-11ea-91e5-28686a2ca4f8.png)

**Comment by yimingc2** [comment]
@marcedwards Here is the iOS end

![Simulator Screen Shot - iPhone 11 Pro - 2020-05-09 at 21 50 27](https://user-images.githubusercontent.com/14011195/81473279-a579b300-9240-11ea-8ebd-eb669dcd154d.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-05-09 at 21 50 39](https://user-images.githubusercontent.com/14011195/81473286-b1657500-9240-11ea-89c4-8beea224b11a.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-05-09 at 21 50 55](https://user-images.githubusercontent.com/14011195/81473287-b4f8fc00-9240-11ea-841e-77e1d2c9ad13.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-05-09 at 21 51 05](https://user-images.githubusercontent.com/14011195/81473289-b75b5600-9240-11ea-9a00-a635ab013431.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-05-09 at 21 51 15](https://user-images.githubusercontent.com/14011195/81473290-b9bdb000-9240-11ea-9583-66298ff64852.png)

**Comment by marcedwards** [comment]
Great, thank you!

**Comment by greggmiller** [comment]
Hi @marcedwards @lukesleeman they look great, but if I could just make a couple of comments...

I'd remove the PPE one (guidance changes a lot and people are very particular about it so might take the slightest issue if there is something they see not to be to their standards.)
This could potentially be replaced by the PPE technique home screen if one of the videos has a visual as if it has been played.
Or something separate like the final page of ALS/BLS modifications (ALS tab) in quick ICU training. This one would probably be  best.


I'd also replace the ventilation one with one from intubation checklist for a couple of reasons.
Mainly the checklist is part of WHs standardised protocol, the ventilation is more of a "rough guide".

Defs keep the home screen, welfare and additional resources.

**Comment by lukesleeman** [comment]
Ok @greggmiller here are the screens you have asked for:

# PPE Home screen (with video)

![image](https://user-images.githubusercontent.com/902252/81487468-65e2b380-92a0-11ea-885c-008690552239.png)

# ALS/BLS modifications (ALS tab) 

![image](https://user-images.githubusercontent.com/902252/81487471-709d4880-92a0-11ea-80a4-8070db6019e9.png)

# Intubation checklist

![image](https://user-images.githubusercontent.com/902252/81487477-785ced00-92a0-11ea-9a7c-db74d9e33e1f.png)

**Comment by lukesleeman** [comment]
@yimingc2 are you able to take screenshots that match mine ☝️ We need the

- PPE Home screen (with video)
- ALS/BLS modifications (ALS tab)
- Intubation checklist

**Comment by greggmiller** [comment]
Awesome @lukesleeman 🚀 🎉  Thanks

**Comment by greggmiller** [comment]
@lukesleeman   I can screenshot on my iPhone X those images? Coming up...

**Comment by lukesleeman** [comment]
> @lukesleeman I can screenshot on my iPhone X those images? Coming up...

You could, but you will have to make sure your device screen resolution exactly matches what June used for her screenshots, otherwise they won't match up with what she has provided.  Not sure what resolution hers are, and if its different to your iPhone X

**Comment by greggmiller** [comment]
Ah ok, no worries.

**Comment by greggmiller** [comment]
![IMG_9963](https://user-images.githubusercontent.com/54889183/81487617-2a48e900-92a2-11ea-81cf-ed5072dd42fe.PNG)
![IMG_9962](https://user-images.githubusercontent.com/54889183/81487620-316ff700-92a2-11ea-9d05-5bff401bd2dd.PNG)
![IMG_9961](https://user-images.githubusercontent.com/54889183/81487621-33d25100-92a2-11ea-803b-2519795c9d2c.PNG)
![IMG_9960](https://user-images.githubusercontent.com/54889183/81487623-359c1480-92a2-11ea-9a89-ca54d0b00984.PNG)
![IMG_9959](https://user-images.githubusercontent.com/54889183/81487624-36cd4180-92a2-11ea-9dbb-c540eafe33af.PNG)

**Comment by greggmiller** [comment]
![IMG_9965](https://user-images.githubusercontent.com/54889183/81487649-8ad82600-92a2-11ea-9bfb-872e7fc0bcd3.PNG)

**Comment by greggmiller** [comment]
Yeah might be better with Junes, that last one looks like cardiac arrest is underlined which we don't want. Feel free to comment mine out if they are more of a hindrance than a help 😄 .

**Comment by yimingc2** [comment]
![IMG_3271](https://user-images.githubusercontent.com/14011195/81490535-f03e0e00-92c6-11ea-8079-6b9cbfad0b3e.PNG)
![Simulator Screen Shot - iPhone 11 Pro - 2020-05-10 at 11 16 09](https://user-images.githubusercontent.com/14011195/81488714-cd542f80-92af-11ea-81a4-e6b9dade5d15.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-05-10 at 11 15 41](https://user-images.githubusercontent.com/14011195/81488719-d1804d00-92af-11ea-92aa-6590c5790fdd.png)

**Comment by yimingc2** [comment]
@greggmiller , I've uploaded 2 more screenshots (+5 from yesterday). But failed to have the PPE tech one with video visual because it's just an audio on my end. My screenshot specification is 1242 x 2688 pixels (portrait).

**Comment by greggmiller** [comment]
Thanks @yimingc2 they look great 😄

**Comment by greggmiller** [comment]
This won't need to be complete for Beta 3 @lukesleeman I think as we can get beat out and then have this finalised for when the app goes on the store?

**Comment by workerbee22** [comment]
@marcedwards Beta 4 is out and being tested, but note that it did have some Home screen changes. Where are you at with the images? @greggmiller will hopefully get confirmation that Beta 4 is ok to be the production release in the next day or two.

**Comment by greggmiller** [comment]
@marcedwards @workerbee22 Of note 2 of the images have changed due to copy changes. I have attached the updated versions.


![Updated_homepage](https://user-images.githubusercontent.com/54889183/82271266-ac2fc500-99ba-11ea-90a9-343261d4e684.PNG)
. 
![ALS:BLSmod_2](https://user-images.githubusercontent.com/54889183/82271256-a76b1100-99ba-11ea-8045-1997f4279792.PNG)

**Comment by lukesleeman** [comment]
Since it seems we wont be shipping, I'm closing this one down
