### ISSUE TITLE
Stores Support web page

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#304]
App Store and Google Play require  a webite / support page. We could just provide the WH web site, but that seems unhelpful for users.

http://www.westernhealth.org.au/

Commonly these basic support webssites have a list of FAQ type questions and answers about the app.

**Comment by lukesleeman** [comment]
I think perhaps just hosting using github pages might be a good idea.  Josh Case has said he is interested in taking this on.  I think the main thing will just to be to get the URL in time for V1 with _something_ at that address, then we can build it out and enhance it.

**Comment by lukesleeman** [comment]
@joshcase I've assigned you to this issue - I'll create the basic repo tonight with a "hello world" file in it, then you can take over.

We can use github pages https://pages.github.com

**Comment by lukesleeman** [comment]
Our URL is now https://western-health-covid19-collaboration.github.io 

@joshcase I'll add you to the repository - you can take things from here 🙂

**Comment by joshcase** [comment]
Thank you Luke, I'm on this now.

**Comment by joshcase** [comment]
Happy with where this is at for now. Link: https://western-health-covid19-collaboration.github.io

@greggmiller Are you happy to double check the answer to the "Are you credible?" question? Any further comments you want to add?

Welcome content additions or phrasing changes from anyone.

Also happy for @Western-Health-Covid19-Collaboration/designers to get involved if they want however I expect this to be a very low traffic page to start with so it should **not** be a priority, in my opinion.

Screens:

![Screen Shot 2020-05-03 at 12 41 02 pm](https://user-images.githubusercontent.com/52585280/80897402-6c6ea980-8d3b-11ea-9c27-0176bb5e0b67.png)
![Screen Shot 2020-05-03 at 12 41 09 pm](https://user-images.githubusercontent.com/52585280/80897404-709ac700-8d3b-11ea-9e4f-5fe4a1dd1374.png)

**Comment by lukesleeman** [comment]
Wow @joshcase , it looks amazing!

**Comment by marcedwards** [comment]
@joshcase Awesome stuff!

**Comment by workerbee22** [comment]
@joshcase  looks really nice ... def on brand. 

Perhaps check on a mobile screen to make sure it is readable? Because its mostly going to be viewed on mobile. So thinking those white content cards can be wider to allow bigger fonts?

**Comment by lukesleeman** [comment]
Looks great, we are closing down this issue 👍👏

**Comment by greggmiller** [comment]
Hi @joshcase this looks great. Thanks for dedicating the time to this. Could I recommend a couple of copy changes? In the credible section could you add something along the lines of "Each section is informally peer-reviewed by other specialists within anaesthesia and intensive care to ensure at the time of writing they comply with both Western Health guidelines and nationally recognized standards".
Does that sound alright?

**Comment by greggmiller** [comment]
Also @joshcase maybe change "brainchild" to "The idea of WHAC19 was conceived by..."
Hope that's alright 👍

**Comment by lukesleeman** [comment]
I've re-opened this issue so we can address @greggmiller's comments

**Comment by joshcase** [comment]
Thanks all!

Sounds reasonable @greggmiller. Have pushed the changes as per Gregg's comments. Will close this issue now - but am happy to be contacted if people want me to make content changes on their behalf.
