### ISSUE TITLE
Button Behaviour Inconsistencies

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#305]
Behaviour on tap varies and is not consistent across the app. Key example are home screen shere call icon shows a ripple on pressed, but information has no on pressed feedback at all.

![image](https://user-images.githubusercontent.com/5154664/80670221-a9436200-8ae9-11ea-9750-bd8f204e3c4f.png)

**Comment by lukesleeman** [comment]
I checked out all our toolbar buttons and its only the info icon which doesn't have the ripple - everywhere else seems to have it properly.

Since it seemed simple, I produced a small fix!

**Comment by lukesleeman** [comment]
Based off what @workerbee22 has said, we can close this one off now

**Comment by sallychung** [comment]
✅ v1.0.168

Seeing the ripple effect on both buttons
