### ISSUE TITLE
Update title on home screen for ICU

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#31]
At the moment the app says "ICU Non-Intensivist"

![image](https://user-images.githubusercontent.com/902252/77297734-d6a82d80-6d3d-11ea-8de0-0bdbd45f8b0d.png)

As per the information architecture in our readme it needs to say "ICU for new starters"

https://files.slack.com/files-pri/T2H965QFM-F0105MNNF34/image.png

**Comment by greggmiller** [comment]
@Marc @Matt This can be changed to "ICU"... An intensivist is a specialist intensive care physician. It is likely with COVID-19 pandemic that non-intensive care specialists "non-intensivists" e.g. anaesthetists and others will be looking after ICU patients... Just having ICU simplifies things

**Comment by alessandrofavero** [comment]
I'll fix this one with #44
