### ISSUE TITLE
Additional ICU screens

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#313]
@greggmiller has a few new ICU screens which need to be added.  Apparently they are fairly straightforward to create so @greggmiller will just have a crack at creating them himself.

This issue is to track the creation and testing of the new screens.

**Comment by greggmiller** [comment]
PR in for this #320

**Comment by lukesleeman** [comment]
As gregs PR is now merged, I'm closing this out and moving over to QA

**Comment by sallychung** [comment]
This isn’t on Zeplin so I’m comparing I purely against the PR
✅ v1.0.173
