### ISSUE TITLE
Discoverability of PDF button

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#319]
Where there is an associated infographic, its is usually accessed by a PDF button in the right of the screens toolbar

<img width="376" alt="image" src="https://user-images.githubusercontent.com/902252/80913360-643c5b80-8d87-11ea-8e45-e37463bb6a00.png">

Unfortunately the PDF button is not very discoverable - a lot of users miss it.  We should look at approaches to make the infographics more discoverable.

**Comment by workerbee22** [comment]
@lukesleeman Has been partially addressed via the new PDF icon that @marcedwards replaced. 

Should we close this one or leave it open do you think?

**Comment by marcedwards** [comment]
My vote would be to close the issue — we can make improvements, but I think they’ll require a larger rethink.
