### ISSUE TITLE
Padding in various pages broken

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#325]
There are a number of pages where the padding seems broken:

![image](https://user-images.githubusercontent.com/902252/80968723-cb2b4480-8e5b-11ea-9075-34f60387f19e.png)

![image](https://user-images.githubusercontent.com/902252/80968776-e1d19b80-8e5b-11ea-8ae7-e2e4d9b0e2b6.png)

![image](https://user-images.githubusercontent.com/902252/80968787-e72ee600-8e5b-11ea-8ba0-ee29b4a8591c.png)

![image](https://user-images.githubusercontent.com/902252/80968795-eb5b0380-8e5b-11ea-8b39-21036e8e0084.png)

I suspect that this may have had something to do with the changes @yimingc2 made to the home screen, though I'm not sure.  The issues appeared sometime this evening.

**Comment by sallychung** [comment]
Additional screens affected which I’ve starred

- [ ] Information *
- [ ] References *
- [ ] PPE
- [ ] WH resources
- [ ] Additional resources
- [ ] Quick ICU training

**Comment by sallychung** [comment]
✅ v.1.0.177
