### ISSUE TITLE
Build out the PPE putting on personal protective equipment infographic

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#33]
Inside the PPE section there is a button which should link off to a "Putting on Personal Protective Equipment" "Infographic"

<img width="404" alt="image" src="https://user-images.githubusercontent.com/902252/77301946-9d26f080-6d44-11ea-9347-1ae9e5c8d6bb.png">

**We need to build build out putting on infographic**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by greggmiller** [comment]
Please refer to Source doc: Western Health donning and doffing PPE.pdf

@marcedwards The infographic on 2nd page is the one we need: "Putting ON PPE"

**Comment by marcedwards** [comment]
@Mattro And I have come up with some plans on how to handle these screens, and are ready to start committing temporary assets, so the dev side can progress.

We’ve opted for 1200×600px images, which should mean the images can be pretty good quality on a range of devices (we won’t have different images for the different pixel densities, given what this is showing).

The one concern we have is that the images in the PDFs are very low resolution and quality. That won’t stop us now, because we can add them to the project immediately, but it would be good if there was a way to get higher quality images.

**Comment by lukesleeman** [comment]
Just some clarification - perhaps @greggmiller can help out - We have the step by step guide over in issue #32 .  How is the infographic different?  Is this just the complete page 2 from the PDF, totally un-altered?  Perhaps with some pinch to zoom or something?

**Comment by greggmiller** [comment]
Yes, this is page 2 of PDF @marc @luke

**Comment by lukesleeman** [comment]
Ok, awesome!  From a design POV then, I think is pretty easy @marcedwards  - I'm guessing just a view of the image with pinch to zoom?

Based on what the flutter devs are saying in GDG slack, its easy to pull up the OS share sheet thing.  I think it would be a nice idea to add a share button, so they can send the image wherever they need to.

@Western-Health-Covid19-Collaboration/designers are you able to get this one ready for the devs?

**Comment by marcedwards** [comment]
This should be ready for some dev work. The related image is now here:

`/assets/images/infographics/putting_on_ppe.png`

**Comment by lukesleeman** [comment]
@Western-Health-Covid19-Collaboration/medical  I discussed this issue on a call with @Mattro  tonight - He quite accurately pointed out, that with the step by step guide currently going into the app, there is probably no need to display the original infographic in the app.  

And if there is a need, the priority is probably quite low, since it just has the same information as the existing step by step guide.

Given that I've bumped the priority down to #3 and assigned it over to `Medic` - can you confirm if we even need this at all?  Is it something we should be focusing on now or can we put it all off for a later day, as the fundamental info we want to communicate to people is in the app?

**Comment by greggmiller** [comment]
Unfortunately, I still think we need to include it as although it is a low pixellated mess, it is the "official" ICU and anaesthetics technique.
Is the issue the low-quality and difficulty in cleaning it up?
Maybe @galtaforce knows where we could find a higher quality of the same image?
@Fabiendade do you know from ICU where or how we can get a better quality image of the document below? 

PDF in question is attached. 

[Western Health donning and doffing PPE.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4386923/Western.Health.donning.and.doffing.PPE.pdf)

**Comment by greggmiller** [comment]
Agree, though priority 3 is fine for this

**Comment by lukesleeman** [comment]
Awesome got it 👍 - as I said in the other issue, I think for version 1 the pixellated mess will be fine.  We can always include a higher resolution version when we find it.

I'm re-assigning this over to design.  As I mentioned above, I think just a pinch to zoom version of the image should be fine.  A button to bring up the OS share sheet would be nice.

**Comment by marcedwards** [comment]
We can build as is, then swap in higher quality images, if we get them.

**Comment by lukesleeman** [comment]
Based on advice from the flutter devs, we are going to build a single re-usable infographic widget, then just configure it to display the different images used all over the app.

As such this issue has been rolled into issue #112 and I'm closing it.
