### ISSUE TITLE
Update P1 of Infographic in intubation Guide

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#331]
After peer review, page 1 of 8 page infographics for intubation guideline requires to be changed. 
I have attached a screenshot of image to replace it with.
This image is a section of Page 5 of attached source document
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/WHIntubationTeamGuidelinesV9.pdf

I can make this change through screenshotting and then amending PDF in preview. However it might look more polished if @Western-Health-Covid19-Collaboration/designers have a look? 
Otherwise I am happy to do it. @lukesleeman can maybe suggest advice on this one?
<img width="1263" alt="Screen Shot 2020-05-07 at 1 04 34 pm" src="https://user-images.githubusercontent.com/54889183/81250786-2d0aca80-9065-11ea-9934-efaac349924b.png">

**Comment by lukesleeman** [comment]
Intresting.  Is there not just an updated version of the PDF that contains the new image?

**Comment by greggmiller** [comment]
No, its a bizarre situation where the society that makes the infographic has it different to our guidelines so we have hacked at it to change the colour of runner 1.

Anyway I think @marcedwards is on it 👍

**Comment by marcedwards** [comment]
So far, I’m not having much luck wrangling the PDF. Is it possible whoever created the original could make the changes needed? If that’s not an option, we’ll find another way.

![pdf](https://user-images.githubusercontent.com/1121547/81282285-4bd98300-909e-11ea-9087-fc9cae959224.png)

**Comment by workerbee22** [comment]
Ditto ... as yet un-able to extract this diagram from the PDF either.

**Comment by workerbee22** [comment]
@marcedwards ... did some magic .... diagram now as a vector in a sketch file I'll send to you on Slack 👍

**Comment by greggmiller** [comment]
@workerbee22 @marcedwards Sorry I was also working on this. I have just updated the document with required section. It will probbaly be of lower quality than your solution but should be fine for V1.
I was going to create an issue for this and one other infographic PDF to be replaced for V1 due to peer review process.
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/08052020_Intubation_Guide_Infographics_Multipage.pdf

**Comment by lukesleeman** [comment]
Ok, cool!  Now we have the PDF over in issue #284 are we able to close this one?

**Comment by greggmiller** [comment]
Yes, sorry for the confusion, extra work and changing plan.

**Comment by lukesleeman** [comment]
Closing this issue
