### ISSUE TITLE
Home page and copy changes

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#337]
Multiple changes to make.

- [x]  "Remove Staff welfare banner"

- [x] Make basic PPE technique top.

- [x] Move Your welfare to within Quick ICU training. 

 Copy changes:
Correct spelling rhythm in ALS/BLS modification

**Comment by greggmiller** [comment]
#338

**Comment by workerbee22** [comment]
@greggmiller Can we close this one now?

**Comment by greggmiller** [comment]
Yes @workerbee22. Closed.
