### ISSUE TITLE
Build out the PPE taking off personal protective equipment step by step guides 1 & 2

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#34]
Inside the PPE section there is a button which should link off to a "Taking Off Personal Protective Equipment" "Step By Step Guide"

<img width="404" alt="image" src="https://user-images.githubusercontent.com/902252/77302471-79b07580-6d45-11ea-985e-dc63f4a4b326.png">

**We need to build build taking off guide.**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by greggmiller** [comment]
This is slightly more challenging than the putting ON PPE section!

Please refer to source document

https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/Western%20Health%20donning%20and%20doffing%20PPE.pdf

Putting on PPE = Donning.
Taking off PPE = Doffing

The step by step guide for Putting OFF (doffing)

Taking off PPE Has 2 methods! This is where the complexity lies. How we display the 2. We might need to have 2 pages that we slide between. Unfortunately, I didn't consider this when drew up hierarchy with @Mattro ...

Method 1 has 8 steps:
1. Gloves
2. Hand hygiene
3. Gown
4. Hand hygiene
5. Eye protection
6. Hand hygiene
7. Mask
8. Hand hygiene

Method 2:
Has 6 steps:
1. Gown and Gloves
2. Hand hygiene
3. Eye protection
4. Hand hygiene
5. Mask
6. Hand hygiene

Each has accompanying image.

Same question applies as per Putting ON PPE... Step-by-step vs Carousel?
@marcedwards

**Comment by Mattro** [comment]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/1920449/77312731-ab7e0800-6d56-11ea-8fa1-a5582bdb464e.png">
We could break the buttons in to two like this. (I already added it like this to Zeplin too)

**Comment by lukesleeman** [comment]
@Mattro FYI, I've created a issue to update the PPE techniques page buttons and a few other things in #72

**Comment by lukesleeman** [comment]
@Mattro has put some designs in zeplin:

**Method 1**
![image](https://user-images.githubusercontent.com/902252/77474819-e0c84a00-6e6b-11ea-9b07-bce3ae2e473b.png)

**Method 2**
![image](https://user-images.githubusercontent.com/902252/77474841-e9b91b80-6e6b-11ea-82d0-452cd9ff430c.png)

@greggmiller Is this all correct?

In slack @greggmiller said:
> We need to highlight the importance of Hand Hygiene in each step. This is one of the most crucial things as it is something which makes a difference which is easy for us to neglect when tired/distracted.

I've put some potential suggestions for this over in #32 
>  Perhaps hand hygene gets its own colour? Red? Or an ⚠️ icon?

**Comment by greggmiller** [comment]
A ⚠️ icon might be useful to reinforce things.

As long as order matches the source document we are good!

https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/Western%20Health%20donning%20and%20doffing%20PPE.pdf

**Comment by marcedwards** [comment]
We have one of those already built and on the repo (`icon_warning.svg`) that might suffice. Here’s a quick mockup with it in place. Is this good enough, or does it need to be stronger?

![alert](https://user-images.githubusercontent.com/1121547/77494974-64e5f600-6e9b-11ea-815c-c953b445c2dd.png)

**Comment by greggmiller** [comment]
That’s fine. Thanks
