### ISSUE TITLE
Subtitles Capitalisation Inconsistencies

### ISSUE THREAD

**Issue by kimngyn** [Western-Health-Covid19-Collaboration/wh_covid19_app#343]
I noticed a few inconsistencies with capitalisation found in subtitles.

On the Home Screen, [G] has capitalisation in the subtitles but there's no capitalisation found in [F], [H], [I], [J] and [K]. 

- [x] **F**  Please change to 'WH Videos and Step by Step Guide'.
- [x] **H**  Please change to 'Guidelines', with a capital G for 'Guidelines'
- [x] **I**  Please change to 'Strategy', with a capital S for 'Strategy'
- [x] **J**  Please change to 'Template', with a capital T for 'Template'.
- [x] **K**  Please change to 'Simple Guide for JMS', with a capital G for 'Guide'

![Screenshot (44)](https://user-images.githubusercontent.com/42886400/82393071-c6d06f80-9a88-11ea-91e5-17679cfddfe9.png)

**Comment by lukesleeman** [comment]
Tested and this seems to be fixed now
