### ISSUE TITLE
Capitalisation Inconsistencies in Titles

### ISSUE THREAD

**Issue by kimngyn** [Western-Health-Covid19-Collaboration/wh_covid19_app#344]
I have found inconsistencies in the titles above the cells. As found in [L] the letters are all capitalised. However, [M] and [N] have not been capitalised. Also, the titles from [N] have a colon. Would it be better to remove them?

- [x] **M** Please change to 'Condition and Example Behaviours'.
- [x] **N** Please change to 'Choice of Sedative', 'Consider Daily Sedation If' and 'Commonly Used Drugs'

![Screenshot (46)](https://user-images.githubusercontent.com/42886400/82393889-f1bbc300-9a8a-11ea-87a8-366b70f890a7.png)

**Comment by lukesleeman** [comment]
Tested and this now appears to be fixed
