### ISSUE TITLE
Unzoomable PDF 

### ISSUE THREAD

**Issue by kimngyn** [Western-Health-Covid19-Collaboration/wh_covid19_app#345]
I was not able to zoom in some of the pages. Please investigate further before making significant changes as I just quickly checked. There is a possibility that I may have missed a few more.

- [ ] **O** Please fix the zoomable feature from pages 1/8 to 8/8 from the 'Intubation Infographic' screen
- [ ] **P** Please fix the zoomable feature from pages 1/2 to 2/2 from the 'Extubation Infographic' screen 
- [ ] **Q** Please fix the zoomable feature from page 2/3 to 3/3 from the 'ALS/BLS Modifications Infographic' screen

![Screenshot (48)](https://user-images.githubusercontent.com/42886400/82394477-7eb34c00-9a8c-11ea-9c71-28c4b4eac7bf.png)

**Comment by workerbee22** [comment]
Related to this [issue 321](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/321) which is to implement the **native_pdf_view** for these screens and utilise the PDF files themselves, rather than images.

**Comment by lukesleeman** [comment]
Yeah, I think the best solution for this is just to move the screens over to actual PDFs

**Comment by lukesleeman** [comment]
I tested and this seems to be fixed now - seems that these screens are now PDFs
