### ISSUE TITLE
Cell Contents

### ISSUE THREAD

**Issue by kimngyn** [Western-Health-Covid19-Collaboration/wh_covid19_app#348]
I was not able to find the design in Zeplin but I noticed that the contents of [W] could have been neatly laid out like [V]

- [ ] **W** Please change the layout and space out "When:"

![Screenshot (54)](https://user-images.githubusercontent.com/42886400/82395466-f71b0c80-9a8e-11ea-8485-10400e6b7968.png)

**Comment by sallychung** [comment]
Could we also tighten the padding between the last bullet point and the greyed text? 

Looks neater if the padding for the footer was like Neuro Basics

![IMG_455D39EFD3FB-1](https://user-images.githubusercontent.com/12321678/82442687-7afee400-9ae3-11ea-8976-27c92a806b9d.jpeg)

**Comment by lukesleeman** [comment]
I just checked this out - now the update of the icons, etc is done, this is fixed
