### ISSUE TITLE
Build out the PPE taking off personal protective equipment infographic

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#35]
Inside the PPE section there is a button which should link off to a "Taking off Personal Protective Equipment" "Infographic"

<img width="404" alt="image" src="https://user-images.githubusercontent.com/902252/77301946-9d26f080-6d44-11ea-9347-1ae9e5c8d6bb.png">

**We need to build build out taking off infographic.**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by greggmiller** [comment]
Please refer to source doc WH donning and doffing PPE. 

The infographic is page 1.

**Comment by marcedwards** [comment]
Is it possible to provide higher quality images for these, or do we have to work with what we have? Even a photo of a printed page may be better than the PDFs.

This is the quality of most of the images:

![screenshot](https://user-images.githubusercontent.com/1121547/77391451-df0b7180-6dec-11ea-8aa2-9f0433658135.png)

Please note that this won’t hold us up. We can get the assets in as is, and improve them later.

**Comment by lukesleeman** [comment]
Yeah, I believe greg should be able to chase up better images, though it will take a little while.  I think run with the pixelated ones for the time being 😬

**Comment by marcedwards** [comment]
Absolutely. Images coming to the repo soon!

**Comment by lukesleeman** [comment]
Just some clarification - perhaps @greggmiller can help out - We have the step by step guide for _taking OFF_ over in issue #34 . How is the infographic different? Is this just the complete page 1 from the PDF, totally un-altered? Perhaps with some pinch to zoom or something?

**Comment by greggmiller** [comment]
Yes this is page 1 of PDFs @marc @luke

**Comment by marcedwards** [comment]
Devs: Will we just want this as an image? If so, I can add those to the repo.

**Comment by lukesleeman** [comment]
Ok, awesome! From a design POV then, I think is pretty easy @marcedwards - I'm guessing just a view of the image with pinch to zoom?

Based on what the flutter devs are saying in GDG slack, its easy to pull up the OS share sheet thing. I think it would be a nice idea to add a share button, so they can send the image wherever they need to.

@Western-Health-Covid19-Collaboration/designers are you able to get this one ready for the devs?

**Comment by lukesleeman** [comment]
> Devs: Will we just want this as an image? If so, I can add those to the repo.

Yep, just an image will be best

**Comment by marcedwards** [comment]
This should be ready for some dev work. The related images are now here:

`/assets/images/infographics/taking_off_ppe_1.png`
`/assets/images/infographics/taking_off_ppe_2.png`

**Comment by greggmiller** [comment]
@Western-Health-Covid19-Collaboration/flutter-devs  Anyone free to help Marc with the above?

**Comment by lukesleeman** [comment]
@Western-Health-Covid19-Collaboration/medical  I discussed this issue on a call with @Mattro  tonight - He quite accurately pointed out, that with the step by step guide currently going into the app, there is probably no need to display the original infographic in the app.  

And if there is a need, the priority is probably quite low, since it just has the same information as the existing step by step guide.

Given that I've bumped the priority down to #3 and assigned it over to `Medic` - can you confirm if we even need this at all?  Is it something we should be focusing on now or can we put it all off for a later day, as the fundamental info we want to communicate to people is in the app?

**Comment by greggmiller** [comment]
Unfortunately, I still think we need to include it as although it is a low pixellated mess, it is the "official" ICU and anaesthetics technique.
Is the issue the low-quality and difficulty in cleaning it up?
Maybe @galtaforce knows where we could find a higher quality of the same image?
@Fabiendade do you know from ICU where or how we can get a better quality image of the document below? 

PDF in question is attached. 

[Western Health donning and doffing PPE.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4386923/Western.Health.donning.and.doffing.PPE.pdf)

**Comment by lukesleeman** [comment]
Ahhh, ok, I understand.  I think for version 1 the pixellated mess will be fine.  We can always include a higher resolution version when we find it.

I'm re-assigning this over to design.  As I mentioned above, I think just a pinch to zoom version of the image should be fine.  A button to bring up the OS share sheet would be nice.

**Comment by fabiendade** [comment]
I will contact the department who created the poster tomorrow and see if they have higher resolution images.

**Comment by fabiendade** [comment]
The person who created the poster (Maureen Canning) is not in today. She is working on a newer version of the PPE poster with better quality images. She will get in touch with me again on Monday with hopefully less pixelated images. May have to make do with the current version for now

**Comment by galtaforce** [comment]
They appear to have stolen some images from the CDC: https://www.cdc.gov/hai/pdfs/ppe/PPE-Sequence.pdf

It's not a one-to-one though. I'll have a look around. This is what happens when you have Infection Control people doing graphic design. "What's a vector?"

There is also https://coronavirus.wh.org.au/wp-content/uploads/2020/02/9.-Donning-PPE-Poster-DHHS-Poster.pdf but it's also full of compression artefacts.

**Comment by lukesleeman** [comment]
I would suggest for the designers:

1. Lets design and build it with just the crappy version of the image right now :-) 
2. When the good image comes through its super easy to just drop it in.

**Comment by lukesleeman** [comment]
Based on advice from the flutter devs, we are going to build a single re-usable infographic widget, then just configure it to display the different images used all over the app.

As such this issue has been rolled into issue #112 and I'm closing it.

@fabiendade don't let that stop you chasing down high resolution versions of the images.  Once you have them provide the to @marcedwards and he can drop the nicer versions into the app for us :-)
