### ISSUE TITLE
Build out Phases of Pandemic and suggestions for self-care screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#36]
At the bottom of the staff welfare screen, there is a button which links off to a "Phases of Pandemic and suggestions for self-care" screen

**We need to build build out the Build out Phases of Pandemic and suggestions for self-care screen**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by greggmiller** [comment]
Please refer to source document Sustaining wellbeing COVID19_ICS.pdf

This is the table that takes up page 1 of the document.

This can then be broken up into a step-by step guide as suggested by @alessandrofavero or as a carousel perhaps? Open to suggestions. 

It has 4 stages:
1. Pre-phase: No cases on unit
2. Initial Phase: Case 1
3. Core Phase: Full scale - multiple cases
4. End phase: Immediate aftermath and Long term

The simplest (alternative) option is leaving this as the table and can just zoom in/out?

**Comment by greggmiller** [comment]
The main thing is for the phases to be aligned to "Issues and likely impact" and those ligned to "Needs and recommended approach"
Maybe an appear function so you tap the screen and the next phase comes up?

**Comment by greggmiller** [comment]
But if that is too much for what its worth, the table alone is fine

**Comment by lukesleeman** [comment]
[Sustaining wellbeing COVID19_ICS.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4386325/Sustaining.wellbeing.COVID19_ICS.pdf)

**Comment by lukesleeman** [comment]
Went through and this one is definitely ready for the design team 👍 👨‍🎨

**Comment by greggmiller** [comment]
As the user, our intention would be that this page outlines the phases of the pandemic (as illustrated on page 1 of PDF) and impact it may have at that time on our mental health, then the recommended approach to minimise harm and appropriately self-care.
This would not need to be an exhaustive list of the bullet points but more an over all feeling.

**Comment by greggmiller** [comment]
As described above, the intention is that this provides some insight into psychological impact of each phase of the COVID-19 pandemic and recommendations to help mental well-being during each phase.

This correlates with source document:

Page 1:
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/Sustaining%20wellbeing%20COVID19_ICS.pdf

and also some reference to;
https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/ASA_Staff_Welfare.pdf

The information could be best represented by the scrollable tab function as discussed with @design.

Each page split into 3 sections

**No of cases: 

Impact of each phase


Preparation and Recommendations**

1st Tab: Pre-phase
2nd Tab: Initial Phase
3rd Tab: Core Phase
4th Tab: End phase
5th Tab: Long term


One suggested outline for @design would be below:
(However @mattro feel free to design as you please, you always get the message across perfectly 😄 )

**1st Tab: Pre-phase**


**No of cases:** 0

**Impact of each phase:**

Anticipation and anxiety
Overwhelmed
Tension in working relationships 

**Preparation and Recommendations:**

Reassure colleagues
Family and personal planning
Communication updates
Employee wellbeing officer


**2nd Tab: Initial phase**


**No of cases:** 1

**Impact of each phase:**


Experimentation
Lost time
Repetition
Frustration

**Preparation and Recommendations:**

Battlefield central plan
Centralised communication
It’s OK to say you’re not OK!
Pre-brief and de-bfrief each day
Sleep Hygiene!


**3rd Tab: Core Phase**


**No of cases:** Full scale - Multiple

**Impact of each phase:**

*Greatest risk period psychologically*
Fear infection and implications for families
Overwhelming workload
Adrenaline and auto-pilot
Exhaustion
Distress 


**Preparation and Recommendations:**
As phase 2 and
Promote peer support
Management are visible and available
Regular comm bulletins
Small pre-brief and debrief
Psychological first-aid 
Ensure the basics (as per previous page)



**4th Tab: End phase: Immediate aftermath**

**No of cases:** Few

Impact of each phase:
Lookout for each other!
Exhaustion
Stress
Post-traumatic stress


**Preparation and Recommendations:**
Debriefing
Staff and 1:1 group sessions
Gratitude and thanks to all our colleagues

**5th Tab: Long-term**

**No of cases:** 0 (or very low)

**Impact of each phase:**
Lookout for each other!
Reflection and Learning
Post-traumatic stress


**Preparation and Recommendations:**
Debriefing  (Staff and 1:1 group sessions)
Look out for signs of PTSD:
* Edgy
* Poor sleep
* Avoid reminders
Learning and preparing for future
Gratitude and thanks to all our colleagues

**Comment by lukesleeman** [comment]
Looking good for design to go!  I've hidden a bunch of older comments to make the issue a bit clearer to read for the designers

**Comment by lukesleeman** [comment]
Looks like @jinjubread has done some pretty amazing designs, which are now in zeplin!

<img width="1593" alt="Screen Shot 2020-04-09 at 10 13 12 pm" src="https://user-images.githubusercontent.com/902252/78950693-e0d67400-7b12-11ea-9b31-683d59e046c0.png">

I'm moving this over to the @Western-Health-Covid19-Collaboration/medical to review and give us a final tick before we can start development.

One small suggestion from me:  Rename the first tab from "The basic" to "The basics"

**Comment by kimngyn** [comment]
I agree with you, on “The basics”. 

I suggested “self-care” instead of “self-case”. 

“debrief” needs to be spelt correctly x 1

I’m not sure about “comm”? Can we have “communication” if it fits?

**Comment by kimngyn** [comment]
And I’m not sure about capitalisation, and dot points at the end. 😊

![2FF0430B-873A-43D5-82C8-089F4343E159](https://user-images.githubusercontent.com/42886400/78951118-4f680180-7b14-11ea-9609-7dc5dad45c70.jpeg)

**Comment by kimngyn** [comment]
I’m also not sure if there’s going to be infographics with this...? Also, do hospital staff need counselling services or phone numbers to those services?

**Comment by greggmiller** [comment]
@jinjubread This is excellent thank you for all the time, effort and expertise put into this 🙌 💯 

@kimngyn Thank you for your attention to detail and picking up for the minor copy changes.
Yes, access to counselling resources or infographics through a tertiary button in top right is planned for later versions. In current iteration, it has access to the hospital phone numbers which is good for time being.

My only comment would be, I think it would benefit the user if Yourself/Welfare/0 continues to have the "Phases of Pandemic and suggestions" button at the bottom that then accesses the scrollable tabs pages (pre-phase/initial phase/ core phase/ end phase/Long-term).

The main reason for this is that those basic tips are the absolute core of welfare and well-being that apply through any stage of pandemic. If the user then wishes to consider how things may unfold as we go through phases of the pandemic they can access through the subsection at bottom.
Does that sound alright @jinjubread @lukesleeman ?

If so, we can move this on to next stage 😄

**Comment by lukesleeman** [comment]
> My only comment would be, I think it would benefit the user if Yourself/Welfare/0 continues to have the "Phases of Pandemic and suggestions" button at the bottom that then accesses the scrollable tabs pages (pre-phase/initial phase/ core phase/ end phase/Long-term).
> 
> The main reason for this is that those basic tips are the absolute core of welfare and well-being that apply through any stage of pandemic. If the user then wishes to consider how things may unfold as we go through phases of the pandemic they can access through the subsection at bottom.
> Does that sound alright @jinjubread @lukesleeman ?
> 
> If so, we can move this on to next stage 😄

I'm not so sure moving the various stages out to a sub-screen is the best way to go.  Unfortunately there is loads of research that shows users just don't click buttons or navigate through apps 😬 - so if we have it behind a button at the bottom of the "Your welfare" screen, it's likely that a lot of users will never find their way through to it.  Having it in tabs means that the basics are still the first thing in front of users eyes, but they are more likely to explore and find the other information.

Ultimately though I guess its probably best to leave the decision to the designers and medics - I'm just an amateur when it comes to these things 😁

**Comment by greggmiller** [comment]
Yeah fair points @lukesleeman

The reason I think it would be good for user if this isn't too accessible is although it provides plenty of insight, it will be a  little anxiety-inducing for some to easily access the latter stages of pandemics effects (potential PTSD! etc)... So I think having it at the bottom provides the ability to access that but also means its only really the inquisitive user who seeks it out.

**Comment by greggmiller** [comment]
However, in saying that I am happy to follow your lead on this @lukesleeman @kimngyn @jinjubread  😄 
We can always amend at a later date if that is the feedback we get 😄 

And just to be absolutely clear @jinjubread , I think the work on it and its appearance is Exceptional 🎉  💯

**Comment by jinjubread** [comment]
Thanks for the feedback @kimngyn @greggmiller @lukesleeman I've revised and corrected the typos. 

Regards to the conversation between Gregg and Luke.... As a user, I felt it's helpful to read the _Phases of Pandemic and suggestions  for self-care_ before you go to the content. (Also agree with Luke's point of avoiding adding depth to reach the content. 

![image](https://user-images.githubusercontent.com/8220376/78961474-ef358780-7b34-11ea-8060-d994a89d3569.png)

What about using it as the subtitle of the page? I think you'll understand what's coming up as you start reading through. I'll update the screens on Zeplin shortly.

**Comment by greggmiller** [comment]
Thanks @jinjubread I think we are maybe better to just remove the subtitle and leave the tab as The basics? 
If the user only reads one thing it should be the top line and then basic tips as they are true whatever stage we are in.
Then they can decide whether to flick through stages of pandemic.
How does that sound?

**Comment by jinjubread** [comment]
@greggmiller Alright! Here we go... :) design for #36 is ready to go on dev. I've merged the final change on Zeplin. 
<img width="1236" alt="Screen Shot 2020-04-10 at 9 18 13 pm" src="https://user-images.githubusercontent.com/8220376/78987236-cfbc5000-7b70-11ea-96a9-ba3bca3e621f.png">

**Comment by kimngyn** [comment]
@sallychung  do we still need to keep #215 open?

**Comment by lukesleeman** [comment]
> @sallychung do we still need to keep #215 open?

I think whoeever does this one should also pick up #215 at the same time 🙂

**Comment by sallychung** [comment]
✅ v1.0.150
