### ISSUE TITLE
Build out the intubations checklist screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#38]
From the main menu there is a button which takes you to the intubation checklist screen.  That screen is currently **really** basic.

**We need to build build out a detailed version of the intubation checklist screen**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by lukesleeman** [comment]
Just noting that @greggmiller has mentioned that he would like there to be actual check boxes users can tick off on this screen. So we will have to give some thought to interactivity.

A question for @greggmiller - do we have to save the screens state?  As in - if the user ticks three 3 things, goes out of the screen then comes back in, should the 3 items still be ticked?

Its possible remembering which boxes were ticked will take longer to code, so perhaps this is only a "Nice have" feature?

**Comment by greggmiller** [comment]
Please refer to source doc: COVID-19_Emergency_Intubation_Checklist.png
--
No @lukesleeman state does not have to be saved. Thanks for asking though.

**Comment by kimngyn** [comment]
![COVID-19_Emergency_Intubation_Checklist](https://user-images.githubusercontent.com/42886400/77622195-eae46880-6f91-11ea-8f0e-74e5732adecc.png)

**Comment by Mattro** [comment]
> No @lukesleeman state does not have to be saved. Thanks for asking though.

Should the state be reset, ever? 
IF the state isn't saved, I assume it will be discarded on either:
 - Page load ?
 - App exit/launch ?

(Do I need to account for a reset button?)

**Comment by lukesleeman** [comment]
I think on page load.  Basically if you go in, its all fresh, with 0 tickboxes ticked.

**Comment by greggmiller** [comment]
Agree with @lukesleeman, if you go in having gone out it should be all fresh

**Comment by Mattro** [comment]
<img width="1978" alt="image" src="https://user-images.githubusercontent.com/1920449/77820204-95948c80-7134-11ea-95b2-80e56e450762.png">

**Ziplen**
Web: https://zpl.io/V478mgz
App: zpl://project?pid=5e7597a68651056664fb6e53&tags=Checklist

**Comment by Mattro** [comment]
A note: One of the checklist items uses superscript. My design tool doesn't allow me to use superscript, so I've used ^-1 on the design. **Please use a superscript -1** when implementing.

**Comment by rockgecko-development** [comment]
Re not saving state. There's one other scenario in addition to @Mattro 's list: app is pushed out of memory, eg because user gets a phone call. When user switches back to the app, the flutter engine will load again from scratch - so back to the main home screen, checklists all reset. This _could_ be dangerous, if user really needs to know what step they were up to. BUT, it is better than resuming to the checklist screen with everything suddenly unchecked.

**Comment by lukesleeman** [comment]
Ok, thats a really good catch.  Perhaps saving state (plus a clear button or something) is a feature we can look at for a later version of the app

**Comment by sallychung** [comment]
For future when we’re saving state, please also consider option to reset. Maybe also confirm to reset as it’s destructive?
