### ISSUE TITLE
Build out the ICU ventilation screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#40]
From the main menu there is a button which takes you to the ICU ventilation screen.  That screen is currently **really** basic.

**We need to build build out a detailed version of the ICU ventilation screen**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by lukesleeman** [comment]
Based on the plan, its looking like there are two screens or sub-sections:  

<img width="218" alt="image" src="https://user-images.githubusercontent.com/902252/77306074-378a3280-6d4b-11ea-864a-280c240709b0.png">

I think @greggmiller and @marcedwards will need to figure out exactly what these are (screens?  Expanding sections in one page?)

**Comment by marcedwards** [comment]
Yep, can do! My initial thought is that if there’s not too much info, we could just stack it. A little bit of scrolling is okay! If it gets longer, we can work out if it’s best to have expanding sections on the one screen, or separate screens. I’ll wait to see what info we end up needing to fit in.

**Comment by greggmiller** [comment]
Please refer to source document https://github.com/Western-Health-Covid19-Collaboration/source-documents/blob/master/COVID-SARI%20Treatment%20Poster%202020.pdf

Suggested Initial Actions subsection:

_Page titled:_ Suggested Initial Ventilator Settings

(then bullet point list, at your and devs discretion as to whether these points appear in bulk or sequentially)

- SIMV/VC
- Vt 4-8ml/kg (ideal body weight)
    - Commence with 6ml/kg
    - Go up to 8ml/kg if dyssynchrony or pH <7.15
    - Go down to 4 if Pplat > 30mmHg
- PEEP
     - Two PEEP regimes in table at bottom of page (_can we paste the table at bottom of page 1 doc. on to page?_)
     - Higher PEEP for most severe cases
- RR 15-20
- Aims:
     - PO2 55-70
     - SpO2 88-92%
     - Pplat <30  
     - Driving Pressure  ΔP ≤ 15mmHg 
- Permissive hypercapnea is OK: PaCO2 ≥ 7.2

**Comment by greggmiller** [comment]
Adjuncts page change to Adjuncts to Ventilation

_Titled:_  Adjuncts to Ventilation

_(then bullet point list, at your and devs discretion as to whether these points appear in bulk or sequentially)_
- Deep sedation
- Prone Positioning
  - Strong recommendation for patients with severe ARDS
  - 12-18 hours  per day
  - May need contiguous days of proning
- Restrictive fluid regime
  - Strong recommendation from experience to date
  - These patients are prone to volume-induced pulmonary oedema
  - Use vasopressors in preference to IV fluids once initial (modest) fluid resus has occured
- Neuromuscular blockade
  - NOT first line management
  - Consider infusion of cisatracurium in patients with refractory hypoxia
- Routine use of recuirtment maneuvers is not recommended
- Steroids are NOT recommended
  - No evidence of benefit, and probably harm
  - Higher rate of HAP/VAP
- Anti-viral therapies are NOT recommended
- Antibiotics
  - Abx should be given, as routine, in intiial empiric management of any patient with acute resp. failure.
  - There seems to be a moderate rate of secondary bacterial infection
- Inhaled NO and prostacyclin
   - There is no evidence of benefit of patient with either of those.

**Comment by rockgecko-development** [comment]
The bullet point content is already included in #54 , merged this morning.

**Comment by lukesleeman** [comment]
> The bullet point content is already included in #54 , merged this morning.

Yep!  This issue is to build out a more nicely designed version of that screen

**Comment by greggmiller** [comment]
@Western-Health-Covid19-Collaboration/designers  beside text "Prone positioning" on "Adjuncts" section could we provide this link https://www.youtube.com/watch?v=YFrA1cCuDnY&feature=youtu.be

**Comment by benblackman** [comment]
Not wishing to add a lot of complexity, but knowing that low tidal volume ventilation has some of the best evidence for mortality benefit in ARDS, do you think it'd be possible to add a section with a calculator with inputs of Sex (m/f) and Height (cm), and outputs of Ideal Body Weight, 4mL/kg, 6ml/kg, 8ml/kg?

The ARDSNet formulas are:
IBW (kg) in men = 50 + (0.91 × [height in centimeters − 152.4]) 
IBW (kg) in women = 45.5 + (0.91 × [height in centimeters − 152.4])

Is this asking too much @greggmiller? Other apps do exist that can do this, although it's always nice to keep functionality in one place and I would have thought this would be pretty simple to program?

**Comment by greggmiller** [comment]
Yes this is a greta thought @benblackman I was planning this and a whole section on PEEP/FiO2 ratios and calculations but I thought that might be best left to 2nd iteration once we are up and running so as not to overload the team (any more than already). Sound fair?

**Comment by benblackman** [comment]
Sounds very fair- really impressed with the amount of hard work going into this already. Is it easier to build sections into the architecture now with an 'under construction' flag or just as easy to add them later? @Western-Health-Covid19-Collaboration/designers

**Comment by lukesleeman** [comment]
IMHO it may be best to add "under construction" or TODO to sections.  

However - we are moving super, super quick and iterating.  Perhaps a good way of building this is:

Step 1:
@Western-Health-Covid19-Collaboration/medical  gives us some super simple text or pictures we can add in right now.  Just think:  What is the simplest most helpful message for the staff that we can give them _today_

Perhaps just add a section that says:
>  Low tidal volume ventilation has some of the best evidence for mortality benefit in ARDS
>
> **The ARDSNet formulas are:**
> IBW (kg) in men = 50 + (0.91 × [height in centimeters − 152.4])
> IBW (kg) in women = 45.5 + (0.91 × [height in centimeters − 152.4])

Is something we can do simply right now.

Step 2:
We can build out a calculator sometime next week

**Comment by benblackman** [comment]
Sounds great @lukesleeman 

Only thing I'd change is to add the recommended tidal volume to your wording

> Low tidal volume ventilation (4-8mL/kg of Ideal Body Weight (IBW)) confers mortality benefit in ARDS
> 
> The ARDSNet formulas are:
> IBW (kg) in men = 50 + (0.91 × [height in centimeters − 152.4])
> IBW (kg) in women = 45.5 + (0.91 × [height in centimeters − 152.4])

No rush to change it for a calculator.

**Comment by greggmiller** [comment]
@Luke @Western-Health-Covid19-Collaboration/designers @benblackman 

I have put a fair bit more thought into this section to try and simplify things and present the info better.

**The intention is that the user feels safe, they do the simple things well, and have a clear idea of a stepwise approach to basic troubleshooting ventilation in COVID.** 
This page and subsections can both be used as an aide-memoire and a bedside reminder. This list is not exhaustive - if the attending doctor wishes for that there are other resources on the resources page.

![Screen Shot 2020-03-28 at 8 42 35 am](https://user-images.githubusercontent.com/54889183/77803291-e1ade580-70d0-11ea-9385-d9654064cf8a.png)

I have attached a mock-up from draw.io . The intention is kind of similar to the excellent job @Mattro did for basic welfare page. There are key principles to follow:
1. Do the simple things well!
2. Follow a stepwise approach!
3. Balance the risks of organ support
4. Minimise the risks of cross-infection (see PPE)

**Suggested initial actions page**

_Intention is for a stepwise approach to follow consisting of Lung protective ventilation, Aims, what to do if patient deteriorating_

1. Initial Stepwise approach:
    1. Lung Protective ventilation:
        1. Ventilator setting: SIMV/VC
        2. Low tidal Volume commence with 6ml/kg body weight (if hover over this step this further information could appear: Range: 4-8ml/kg Body Weight: ↑ to 8ml/kg if vent. dyssynchrony or Ph <7.15, ↓ 4ml/kg if Pplat >30mmHg)
        3. RR 20 (Hover over Range 15-20)
        4. PEEP: aim high, start 10cmH20, see table!
    2. Aims:
        1. SpO2 88-92%
        2. PaO2 55-70mmHg
        3. Pplat <30
        4. Ph>7.2 (Permissive hypercapnia is ok)
    3. If deteriorating: 
        1. ICU consultant review!
        2. Proceed to Adjuncts page (adjuncts page linked by devs)

Adjuncts page:


**If initial stepwise approach fails try:**

1. Deep sedation
2. Restrictive fluid regime
    1. (Aim for Negative fluid balance)
3. Ensure senior ICU review
4. Neuromuscular blockade
    1. NOT first-line management
    2. Consider infusion of cisatracurium in a patient with refractory hypoxia
5. Prone positioning (On hover/click links to resources on Proning - Under construction)



If all of the above is clear with @lukesleeman @Western-Health-Covid19-Collaboration/designers 
Then it is over to you @Mattro @marcedwards

**Comment by greggmiller** [comment]
After seeing @mattro really impressive work on intubation checklist and guide by creating the scrollable tabs screen for those pages, I think Ventilation would also suit this same design layout (reasoning below). Checkboxes would not be necessary for the ventilation seciton.

![Uploading Intubation_step_by_step.png…]()

I think adapting the above layout may be of benefit if used across different sections as it:
- Provides a similar layout for the user seen elsewhere in the app (this could be recurring through the app for multiple aspects of information) so does not overcomplicate things.
- The natural sequence that the bedside attending doctor should follow as slides from left to right lateral navigation
- Saves challenges of linking in other pages (I discussed this with @Mattro )
-Saves design time for our overworked @Western-Health-Covid19-Collaboration/designers 
- Might mean it is possible to fit in version 1 (this is probably the most important aspect of ventilation).

One possible and hopefully simple solution for this for ventilation would be:

_1st tab:_ 
**Principles:**
Do the simple things well!
Follow a stepwise approach!
Balance the risks of organ support
Minimise the risks of cross-infection (see PPE)

_2nd tab ( 3 sections on same tab)_
**Initial Steps**
Lung Protective ventilation:
Ventilator setting: SIMV/VC
Low tidal Volume commence with 6ml/kg body weight (if hover over this step this further information could appear: Range: 4-8ml/kg Body Weight: ↑ to 8ml/kg if vent. dyssynchrony or Ph <7.15, ↓ 4ml/kg if Pplat >30mmHg)
RR 20 (Hover over Range 15-20)
PEEP: aim high, start 10cmH20, see table!

Aims:
SpO2 88-92%
PaO2 55-70mmHg
Pplat <30
Ph>7.2 (Permissive hypercapnia is ok)

If deteriorating:
ICU consultant review! 
Consider ventilation Adjuncts 

_3rd tab this could do with numbering as is stepwise_
**Adjuncts**
1. Deep sedation
2. Restrictive fluid regime
- (Aim for Negative fluid balance)
4. Ensure senior ICU review
5. Neuromuscular blockade
- NOT first-line management
7. Consider infusion of cisatracurium in a patient with refractory hypoxia
8. Prone positioning 
- (see cross-skilling section)


Keen for thoughts @luke and @Western-Health-Covid19-Collaboration/designers  😄

**Comment by greggmiller** [comment]
As discussed with @Mattro 
![intubation guide step-by-step](https://user-images.githubusercontent.com/54889183/78127941-cb9d7d80-7460-11ea-87c0-99e2e2d47ef4.png)

**Comment by kimngyn** [comment]
@greggmiller  will you be adding the peep chart, general observation, cardiomyopathy, low tidal volume formulas and prone positioning on another screen? I read the pdf and watched the video

**Comment by greggmiller** [comment]
good points. We will probably add them into the ICU cross-skilling section @kimngyn  Thanks for reminding me 😄

**Comment by Mattro** [comment]
> (if hover over this step this further information could appear: Range: 4-8ml/kg Body Weight: ↑ to 8ml/kg if vent. dyssynchrony or Ph <7.15, ↓ 4ml/kg if Pplat >30mmHg)

@greggmiller how essential is this information? Unfortunately, we can't detect hover on a touch screen because there's no mouse cursor! Should I find a different way to display it, or leave it out?

**Comment by lukesleeman** [comment]
👋 Just FYI everybody, I hid a bunch of older comments, just so its easier to see the final request from greg, etc on this issue

**Comment by Mattro** [comment]
Ventilation is Ready to go. 

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/1920449/78194144-18686f00-74c8-11ea-9bf2-ec2f97e930a3.png">


https://zpl.io/ad0QLXR
