### ISSUE TITLE
Build out the ICU Daily Round Screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#42]
From the main menu there is a button which takes you to the ICU General Care screen.  That screen is currently **really** basic.

**We need to build build out a detailed version of the  ICU General Care screen**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by galtaforce** [comment]
Hi all. Jonathan here, another anaesthetist helping Gregg out.

ICU General Care will contain a daily checklist for managing patients similar to this: 
[ICU daily checklist.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4378666/ICU.daily.checklist.pdf)

Probably would work with collapsable sections for each heading. Excuse any Github _faux pas_ as new to using it!

**Comment by lukesleeman** [comment]
Wow, I had a look at the PDF and there is a lot in there to put into one mobile app screen.

@galtaforce is there anything that they should prioritise or should remove?  Do we want this checklist with tick boxes that users can tick?

**Comment by galtaforce** [comment]
Yeah, it's a really long checklist - I've been told there is likely to be an updated version soon too. As for mobile display, could it perhaps present a single screen of related questions at a time? Although probably not good UI principles another option for displaying a single question where the user selects YES or NO and is presented with a scrollable summary at the end?

**Comment by greggmiller** [comment]
@galtaforce I was thinking we could maybe have two subsections here.

One titled: **Daily ward round ICU**
An accordion or carousel with: 
[MAKING A PLAN for THE ICU PATIENT-FM.docx](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4383670/MAKING.A.PLAN.for.THE.ICU.PATIENT-FM.docx)
This could be A - G for each page on a carousel with final page maybe the FASTHUGS checklist 
It would be interesting to hear @Western-Health-Covid19-Collaboration/designers  perspective on this?

Then another subsection with 
ICU daily checklist which could be as you described in previous comment @galtaforce 

However, there may be a better way to collate/summarise this?

@BenBlackman might provide some useful insight from the registrar perspective?

**Comment by greggmiller** [comment]
We also have the option to keep it very simple in the beginning and develop as time goes on.
Low-hanging fruit and efficiency is probably best for first iteration?

**Comment by benblackman** [comment]
All sounds good. 

I think the aims of the Daily Checklist and Plan documents are slightly different and we probably need to ask the question of who this section of the app is aimed at and what we're hoping to achieve with it. It might be possible to put the two together, but I'd definitely want to seek ICU's input on that.

From a registrar perspective, (especially if working on paper) I'd use the app as an aide memoir of which data points to note and then what plan to consider when writing the notes in an A-G format for a daily review. 

I'm not sure about the need to enter data into the app and have an output at the end; I think this would only really save work if it can print or sync to an EMR, although I could see how this might serve to keep paperwork away from the bedside if copied out after.

**Comment by greggmiller** [comment]
This section of the app is aimed at the non-intensive care consultant or senior reg (people like me or you). Mainly as a memory aid as it may be %+ years since we did ICU ward rounds etc.

Agree on the other points. Will wait for @galtaforce opinion and then we can give @Western-Health-Covid19-Collaboration/designers  some clearer direction

**Comment by galtaforce** [comment]
Yeah, I agree might be best separated out. The daily checklist is just an _aide memoire_ for ward rounds which has a different goal from more general tips for managing these patients.

**Comment by greggmiller** [comment]
Good @galtaforce and @benblackman do you think we should have both this and #43 as listviews? 

In the first instance, I think the lists would include <5-10 topics for each category with a button/gesturedetector to proceed to the information (one page summary). 

For this section topics would be:
**Making a plan on daily ward round
Daily checklist
Proning**

For #43 ICU for Junior staffers, topics would be:
**Assessment of the ICU patient
Daily protocols/investigations etc.
Ventilation in ARDS/COVID19
Management of the deteriorating patient**

Feel free to add or remove as you see fit.

I am sure it will be flagged in app feedback which topics we should add as time goes on. 
Then as more topics come we can revise how to order them?

I think this would be a nice, easy way for @Western-Health-Covid19-Collaboration/designers  to start designing both these sections. They could also then be designed with a common architecture pending what design think?

**Comment by benblackman** [comment]
@greggmiller I've had a go at putting it in one document (before I saw your last post admittedly, but might as well show it), in order to cover assessment and planning in one place.

You could have a carousel that displays

A (status), A (planning), B (status), B (planning)..... etc.

or

A (status), B (status), C (status)..... A (planning), B (planning), C (planning).... etc.

and that would keep this information in one place? I guess the status is more for the juniors performing an assessment and the planning is more for the seniors, although you can't really do the latter without the former, and it's probably useful for juniors to get involved in where their assessment is going.

Would definitely have to run past ICU as I've taken bits of both of their documents and bits of my own thoughts as well.

**Edit: Updated document (a couple of small extra thoughts I had)**

[Combined ICU Checklist:Planning.docx](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4384753/Combined.ICU.Checklist.Planning.docx)

**Comment by benblackman** [comment]
Thinking about it, I think there's a lot of crossover between the information that a senior and junior doc want to access. Would it make more sense just to split up the ICU section by topic rather than seniority? 

I also reckon it might be better to divide A-x into one status carousel called Daily Assessment, and one called Targets and Planning, corresponding to the two main columns of the document I just posted, and the FLATCHUGS checklist as a separate section. The treatment protocol could be based on the ICU daily checklist posted by @galtaforce https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/42#issuecomment-603603515 and the deteriorating patient could include some things to think about for each type of organ dysfunction.

What do you reckon @greggmiller @galtaforce of organising the ICU section like this?

ICU >
- General Care
                 - Daily Assessment [A-CPR (status)]
                 - Targets and Planning [A-CPR (planning)]
                 - Daily Care Checklist [FLATCHUGS]
                 - COVID-19 Treatment Protocol [Based on [ICU.daily.checklist.pdf](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4384593/ICU.daily.checklist.pdf)]
                 - Management of the Deteriorating Patient [optional, could include things like DOPES, more aimed at the Juniors to temporise until senior help arrives]

- Ventilation
                 - Ventilation in COVID-19/ARDS
                 - Proning
                 - Tidal Volume calculator
                 - PEEP Chart

**Comment by greggmiller** [comment]
w/r/t 1st Q: Yes it probably would. The issue is ICU cons have approached me about content for senior medical staff (non-intensivist) and ICU regs about advice for the JMS. The concern with the second topic is that we will end up with medics with almost no critical care experience manning ventilators etc. 

However, I think your suggestions make sense.
How about for the 3 boxes below ICU section:

Ventilation = Ventilation
General care change to Daily Management
Tips for junior staffers changes to "Additional ICU Guidance"

"Daily management" can be the carousel

and
"Additional ICU Guidance" can be more extensive probably in a list view split into 2 categories Senior medical staff and Junior medical staff. Or just all together.

Thoughts?

@benblackman @galtaforce 



<img width="245" alt="Screen Shot 2020-03-26 at 2 03 28 pm" src="https://user-images.githubusercontent.com/54889183/77606182-ee182e00-6f6a-11ea-81b6-80d2fba8af4f.png">

**Comment by greggmiller** [comment]
Really like the ventilation suggestions. We could have those 4 subsections as list or as recommended by @Western-Health-Covid19-Collaboration/designers

**Comment by benblackman** [comment]
Thanks Gregg. So is what you're saying the following?


ICU >

Daily Management
- Daily Assessment [A-CPR (status)]
- Targets and Planning [A-CPR (planning)]
- Daily Care Checklist [FLATCHUGS]


Ventilation
- Ventilation in COVID-19/ARDS
- Proning
- Tidal Volume calculator
- PEEP Chart

Additional ICU Guidance
- COVID-19 Treatment Protocol 
- Management of the Deteriorating Patient

**Comment by fabiendade** [comment]
Hey all, I’m Fabien - ICU reg. 

Re “splitting ICU guidance” between junior and senior medical staff, it may be simpler to include both sets of information in one list, but insert prompts to escalate/ discuss with ICU reg / Anaesthetic reg at an appropriate point in the pathway. 

For things which require senior discussion e.g introducing an inotrope - a prompt to inform a senior medical staff member prior to commencing should be displayed

**Comment by benblackman** [comment]
Sounds good to me Fabien.

**Comment by greggmiller** [comment]
Great insights Fabs. James Douglas (ICU consultant) will look over this and get back to us.

The intention here is we want to get the broad strokes in management right and not worry over the minutiae of every aspect.

**Comment by greggmiller** [comment]
This section is now titled **Daily round** as per # 96

@fabiendade Once we have content from James Douglas and ICU streamlined we will discuss with @Western-Health-Covid19-Collaboration/designers our intention to have prompts for pathway (e.g. escalate/discuss with senior) who will come up with a great solution I'm sure.

**Comment by benblackman** [comment]
@fabiendade has done some great work formatting this document
[COVID DAILY ASSESSMENT AND PLAN.docx](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4406707/COVID.DAILY.ASSESSMENT.AND.PLAN.docx)

**Comment by benblackman** [comment]
@greggmiller and I have had a discussion and we think the best format for the daily round section would be (and correct me if I'm not using the right dev terms) a ribbon of tabs (as per @Mattro 's beautiful [intubation guide](https://user-images.githubusercontent.com/902252/77847281-c4c7fe00-7207-11ea-9a22-f140f355aa6e.png) build) across the top denoting sections:

A, B, C, D, E, F, G, ☑️

These could be selected either by tapping on them or swiping left and right
Each of these to bring up a screen with the top half for assessment, and the bottom half for plan.

The content of these should be as per @fabiendade 's document as above

> A>
> AIRWAY
> _Assessment_ 
> ETT:
> •	size  
> •	position
> •	confirmed with CXR
> •	are all connections secured with sleek
> _Plan_
> If planned for extubation:
> •	When
> •	Where
> •	How (see airway resources)
> •	Does ETT need advancing / withdrawing?
> 
> B>
> BREATHING 
> _Assessment_ 
> SPO2 / PaO2
> 
> CXR reviewed
> ABG reviewed
> Current ventilator settings reviewed
> _Plan_
> Standard targets
> •	PaO2 > 55-60 / SaO2 > 88-92
> •	pH > 7.20 (or CO2 35 – 45 if pH normal)
> •	VTe 4-8ml/kg with PPlat < 30
> •	PEEP: According to PEEP Table
> Also check ETT lines NG ICC
> 
> If Fio2 > 0.6 and PEEP > 15
> •	Specialist review + see resources
> 
> C>
> CIRCULATION
> _Assessment_
> HR / rhythm / MAP
> ECG + ? echocardiogram
> Lactate / signs of end organ perfusion (? Mottled / cool peripheries / cap refill time)
> _Plan_
> Aims
> •	MAP > 65
> •	[Hb] > 70
> If haemodyamically unstable / MAP <65: commence noradrenaline, see resources
> ? echocardiogram 
> 
> D>
> NEUROLOGICAL 
> _Assessment_
> Riker score & Pain assessment
> Current sedation / analgesic infusions
> neuromuscular blockers?
> _Plan_
> Analgesia / sedation plan and target (see resources)
> Consider sedation break (see resources)
> ? cessation of neuromuscular blocker
> 
> E>
> INFECTION / EXPOSURE
> _Assessment_
> Temperature
> Culture results 
> Current antibiotics
> Invasive lines
> Pressure areas / wounds / cellulitis
> _Plan_
> Antimicrobials (see resources)
> If patient deteriorating: ? septic workup (see resources)
> 
> Appropriate?
> ? lines can be removed.
> 
> 
> F>
> RENAL
> _Assessment_
> Current urine output / fluid balance last 24 hours
> 
> Electrolytes
> Acid-base status
> _Plan_
> Fluid balance target for the next 24 hours + diuretics (aim for negative fluid balance around 1L/d stable)
> Electrolyte supplementation / goals
> 
> G>
> GIT
> _Assessment_ 
> NGT confirmed correctly positioned
> Abdominal examination
> LFTs checked
> Absorbing feeds?
> _Plan_
> Nutrition (resources)
> 
> Any surgical issues?
> Any liver issues?
> 
> ?change meds ng -> iv or vice versa
> 
> ☑️>
> FINAL CHECK
> 	Resuscitation status: goals of care determined
> 	Feeds charted / considered
> 	Lines - ? can they be removed
> 	Aperients – when were bowels last open? Regular laxatives and early insertion of faecal containment device
> 	Thromboprophylaxis – in general enoxaparin 40mg/d (20mg/d with severe renal failure)
> 	Communication / Family – is patient aware of what is happening? Is family aware of what is happening?
> 	Head up – head of the bead elevated to 30 degrees in the intubated patient
> 	Ulcer prophylaxis – esomeprazole 20mg iv d in the intubated patient.
> 	Glucose target – 6 – 12 (start actrapid if 2 X BSL > 12, titrate to BSL)

Most of them wouldn't require checkboxes, but for the last section it would be good to have them.

How does this sound? Hope I've represented our conversation accurately @greggmiller !

B

**Comment by greggmiller** [comment]
Discussed above with Ben and we feel this represents intention of medics to give user required information while using format across app for both consistency and clarity.
(While also hopefully saving time for design).

Ready for @Western-Health-Covid19-Collaboration/designers 
Feel free to clarify or question any aspects of above 👍

**Comment by lukesleeman** [comment]
Awesome work everybody in getting this specified 👏 
Just to make it clear for @Mattro and @marcedwards what needs to be done, I've gone and hidden a bunch of comments, so there is one clear description of what needs to be built 🙂

**Comment by cjmlgrto** [comment]
Alright, I've got a first draft of some screens here ready for a review.

Keen to get the eyes off @Western-Health-Covid19-Collaboration/medical and the @Western-Health-Covid19-Collaboration/designers on this.

![Slice](https://user-images.githubusercontent.com/1712450/78452210-b3826400-76d5-11ea-822f-ca0dc0b2676b.png)

**Comment by kimngyn** [comment]
Great work @cjmlgrto ! 

Can we please make it blue ? Preferably the same blue as the app bar. Thanks 
![6393A746-41AB-4769-A7EF-806535437E73](https://user-images.githubusercontent.com/42886400/78460924-74b9d180-7708-11ea-8737-656be26a3ad9.jpeg)

**Comment by greggmiller** [comment]
This looks Fantastic 👏 😄  Incredible work 🔥 

I'm sure @benblackman will also be appreciative after the work he has put in here. 

Thanks!

**Comment by lukesleeman** [comment]
Wow!  This looks incredible!  Just wanted to check with @greggmiller to see if this is ready for dev?  In particular are we happy with the text and emoji?

**Comment by cjmlgrto** [comment]
Thanks folks!

I’ll update the designs and make those changes. Will let you all know once they’re up on Zeplin.

**Comment by greggmiller** [comment]
Thanks @lukesleeman , ready for @Western-Health-Covid19-Collaboration/flutter-devs 👍

**Comment by lukesleeman** [comment]
Screens are in zeplin
https://app.zeplin.io/project/5e7597a68651056664fb6e53/dashboard?seid=5e893e64976918bc585f8f8e
zpl://project?pid=5e7597a68651056664fb6e53&seid=5e893e64976918bc585f8f8e

**Comment by benblackman** [comment]
Looking great!  🔥 

Thanks for all the hard work all  😃
