### ISSUE TITLE
Build out the Cross-skilling screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#43]
From the main menu there is a button which takes you to the ICU Tips for junior staffers screen.  That screen is currently **really** basic.

**We need to build build out a detailed version of the ICU Tips for junior staffers screen**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by greggmiller** [comment]
This may be a work in progress as waiting for more information being compiled by ICU for this.

**Comment by greggmiller** [comment]
Hopefully in next couple of days, but otherwise put this on backburner.

**Comment by greggmiller** [comment]
We can always just add Page under construction for this one for time being. This will probably be the last one to fill as we are still waiting for the ICU to provide us with what they wish to do.

**Comment by lukesleeman** [comment]
Yeah, it currently just says "TODO" in that screen

**Comment by greggmiller** [comment]
I have been in touch with one of the ICU consultants (James Douglas)

He is going to draw up 1-page summaries for us for this to start with. 
Initial topics are:

Assessment of the ICU patient
Daily protocols/investigations etc.
Ventilation in ARDS/COVID19
Management of the deteriorating patient
(Management and diagnosis of septic shock and ARF _This may come later as will be a bit further down the track_  )

There is likely to be some overlap from the general ICU section which is probably alright.

@lukesleeman I probably won't have these documents until tomorrow at the earliest.
@Western-Health-Covid19-Collaboration/designers We can consider how the "ICU tips for junior staffers" section opens up. This will likely to be a growing list of topics over time so instead of separate boxes it may to open into a list. This list might have subcategories.
Daily routine
Deteriorating patient
Airway
Breathing
Circulation
Disability/Sedation protocols
Investigations


@galtaforce @benblackman thoughts?

**Comment by benblackman** [comment]
Sounds good. The first two on the list of topics may have a lot of crossover with  #42 I think?

**Comment by greggmiller** [comment]
This section of app is now titled **Cross-skilling** as per discussions in #96 .
After discussions with ICU today, content is unlikely to be ready until Monday, I will update then.

**Comment by greggmiller** [comment]
Still awaiting further content for this section from ICU.

We can begin to build this out though when @Western-Health-Covid19-Collaboration/designers  get an opportunity.

The consensus is that this would be best to be a list with subheaders.

The subheaders would reflect the categories of #42.

Airway
Breathing
Circulation
Disability/Neurological
Exposure/Infection
Fluids/Renal
GIT
Haem/blood

Under each subheader, we would eventually be building up a number of topics (this is likely to be over several versions)

Each item on the list would then open up to a PDF/Infographic/link, a quick reference card or other content.

In the first instance, we have a few items to put under subheaders on this list.

e.g. 
Breathing (_subheader_)
Prone positioning (- links to video https://www.youtube.com/watch?v=YFrA1cCuDnY&feature=youtu.be) (_This is from #88_)


Please feel free to ask for clarification @Western-Health-Covid19-Collaboration/designers  

I will discuss with @fabiendade about what content this section would best contain.

**Comment by lukesleeman** [comment]
Awesome - I've hidden a lot of chatter on this issue to make it clear to the designers what to look at.  @Mattro or @marcedwards either of you want to pick it up?

**Comment by cjmlgrto** [comment]
Is something like this what you're after @greggmiller? I'll hold off on this until we get the first round of content in.

![Tips](https://user-images.githubusercontent.com/1712450/78467453-655e7680-7750-11ea-8b82-f99e5d6ddd06.png)

**Comment by greggmiller** [comment]
@cjmlgrto 🙌 💯  Yes that looks excellent. This will probably be the aspect that fills out most over time.
At the moment there are only a few infographics/videos to put in this section, but this is likely to grow to total of 20-30.
It shouldn't end up much more than this as we have other means for the more comprehensive stuff (we now have separate anaesthetic and ICU microsites).
Mainly items that are referenced elsewhere in-app and ones that are useful for quick access.
😄 👍

**Comment by lukesleeman** [comment]
👋 Hey @greggmiller with this one, should I leave it with design, or remove the designers from it until you get more resources to add into this screen?

**Comment by greggmiller** [comment]
I think @fabiendade was going to start putting together some content for this.
So he might come back to us in the next couple of days.

In the meantime if it was built out like above with each A,B.C... etc..
Saying something like content pending or blank underneath. 
This would give users the chance to see the intention for the app.
From what @Mattro said on the call this should be ok?

**Comment by fabiendade** [comment]
I have been compiling a list of useful topics to include in this section and should have something back to you by Wednesday morning. Will Liase with Ben and some other Reg’s to make sure it is relevant.

**Comment by lukesleeman** [comment]
I think in this case, its probably best to just wait for @fabiendade info on wednesday, then move it back to design then

**Comment by fabiendade** [comment]
Under Breathing Section of the cross skilling instructions and a checklist for proning a patient is required - a complex process not often performed - and a checklist would be ideal

Format proposed is a button labelled “Proning” which opens into scrollable Tab format detailed below.

It would be useful if each bullet point (except those under indications and contraindications section) to be check boxes like intubation checklist

For each heading within a Tab it would be useful to split into boxes. 

Proning 

(Tab 1) – Indication 

Indications
•	Severe ARDS with hypoxia 
•	Posterior wounds / skin flaps

Contraindications
•	Lack of staff 
•	Untrained staff
•	Out of hours 
•	Open abdomen
•	C spine precautions 
•	Haemodynamic instability  

TAB 2 (Pre-Manoeuvre) 

Pre-Manoevre  

Team 
•	ICU consultant aware 
•	Specialised proning team on site? – contact ICU physio 
•	Adequate staffing on unit?
•	Staff trained in proning procedure
•	6 x Staff available for proning 
•	Allocate roles – Airway x 1, Trunk and limbs x 4, Lines and equipment x 1 
•	Able to reintubate? 

Equipment and Preparation 
•	Crash trolley
•	ECG dots
•	Fresh sheet x 2
•	Slide sheet x 2
•	Foldable Pillows x 3
•	Clear bed area

Patient

General consideration
•	Review indications and contraindications
•	Check ROM of neck – 90ᵒ 
•	Explain procedure to patient / family  

Airway
•	Check ETT position on CXR – document lip level
•	Check patient airway grade 
•	Secure ETT 
•	Sleek connections 
•	Check for cuff leak
•	Suction mouth and nasal passages 

Breathing 
•	Pre-oxygenate
•	Confirm ventilator settings
•	Check capnography 

Circulation
•	Check adequate vascular access + secure 
•	Confirm haemodynamically stable
•	Confirm plan if patient becomes unstable
•	identify drug access point and metaraminol accessible 

Disability 
•	Sedated 
•	Plan for further sedation discussed 

Equipment and lines 
•	Secure all tubes and lines 
•	Consider disconnecting unnecessary infusions 
•	Remove uneccessary indwelling devices
•	Consider disconnecting RRT
•	NGT – aspirate and spigot 

Other
•	Assess for device potential for pressure injury
•	Apply padding to bony prominences 
•	Mouth care 
•	Dress anterior wounds

(TAB 3) Manoeuvre 

Manoeuvre 

Prepare
•	Position team – team leader at head of bed
•	Brief team on steps – turning direction 
•	Position ETT on opposite side 
•	Remove patient pillow and set air mattress to firm 

Horizontal move
•	Move patient to edge of bed
•	Tuck original sheet + new slide sheet under patient 
•	Tuck new sheet and slide sheet on side patient turning towards

Side lying position
•	Tuck lower arm under buttock with palm up 
•	Turn patient into lateral position 
•	Untangle lines and remove ECG leads from anterior thorax
•	Place ECG leads on posterior thorax 
•	Remove old sheet
•	Pull new sheet + slide sheet through
•	Slide patient to end of bed – away from ventilator 
•	Fold pillows by 1/3 and place under chest and pelvis

Complete Prone
•	Turn patient onto stomach
•	Pull pillows through position in swimmer position 
•	Place pillow under lower legs 


TAB 4  - Post manoeuvre 

Post manoeuvre 

Checks
Position 
•	One arm above head, other by side. Shoulder in neutral position 
•	Reposition patient in centre of bed 
•	Adjust position to ensure abdomen is hanging freely 
•	Postion head to reduce pressure on eyes and enable access to airway 
•	Readjust lines for comfort and NG on free drainage 

Airway 
•	Check ETT lip level and ventilator circuit for kinks 
•	Suction if indicated 
•	Cuff pressure

Breathing 
•	Auscultate for bilateral breath sounds 
•	Respiratory parameters 
•	Check Peak inspiratory pressurs and Minute ventilation 

Circulation 
•	Check haemodynamics
•	ABG – 30 minute post proning 

Pressure area care
•	Air mattress to usual setting – ensure functioning 
•	Reposition head hourly – frequent eye toilets may be necessary
•	Ensure tongue in mouth 
•	Document skin assessment 
•	Lateral Tilt patient 2 hourly 


Video – separate embedded section in Cross link section  
Demonstration of proning technique 
https://www.youtube.com/watch?v=YFrA1cCuDnY&feature=youtu.be


Infographic – top right 
2 power point slides

**Comment by fabiendade** [comment]
[prone_checklist_september_2018.pptx](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4448571/prone_checklist_september_2018.pptx)

**Comment by cjmlgrto** [comment]
Alright, here are the designs for the "Proning" screens. I've decided to split the "Pre-Manoeuvre" screens into two separate ones ("Staff" and "Patient") because they were getting quite long.

![Slice](https://user-images.githubusercontent.com/1712450/79097949-4beaa980-7da4-11ea-82d1-69bc54471b03.png)

Users will find these screens (and the linked demonstration video) by going into the Cross-Skilling section of the app here:

![ Cross-skilling](https://user-images.githubusercontent.com/1712450/79097985-5a38c580-7da4-11ea-9d72-a8a407092644.png)

Keen to get a content review, and thoughts from the @Western-Health-Covid19-Collaboration/medical 😄

**Comment by kimngyn** [comment]
I thought it would be cool to have a trolley emoji:


![Screenshot (156)_LI](https://user-images.githubusercontent.com/42886400/79105984-fff43080-7db4-11ea-8eab-017ddea7641c.jpg)

**Comment by kimngyn** [comment]
I'm not sure if there were changes to this section: 

![Screenshot (157)_LI](https://user-images.githubusercontent.com/42886400/79106055-1d28ff00-7db5-11ea-8d63-38e7b953666c.jpg)

**Comment by kimngyn** [comment]
Disability section was missing? : 

![Screenshot (158)](https://user-images.githubusercontent.com/42886400/79106115-3631b000-7db5-11ea-9fe3-e5f8ce049a91.png)

**Comment by kimngyn** [comment]
Is the last tab meant to be a checklist? 
Also the double title of "circulation".
Capitalisation for "peak" and "minute". 
Typo for "pressures".

![Screenshot (161)_LI](https://user-images.githubusercontent.com/42886400/79106147-46498f80-7db5-11ea-8116-b592cf80ed6e.jpg)

**Comment by kimngyn** [comment]
Capitalisation issue for "tilt". 
![Screenshot (160)_LI](https://user-images.githubusercontent.com/42886400/79106251-7bee7880-7db5-11ea-9c26-3eb4353db38f.jpg)

**Comment by greggmiller** [comment]
Looks really good @cjmlgrto.
 Agree with Kim's changes. Probably best to have @fabiendade have a look at this as he drafted this one 😄

**Comment by cjmlgrto** [comment]
Great attention to detail. Changes made. Thanks folks!

**Comment by fabiendade** [comment]
Looks amazing @cjmlgrto and agree with all the changes proposed by Kim. Thanks!

**Comment by sallychung** [comment]
Looks like this is ready for dev 🤘

**Comment by sallychung** [comment]
✅ v.1.0.150
