### ISSUE TITLE
Build out the Society & College Recommendations screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#45]
Inside the information screen there is a button which takes you to the Society & College Recommendations screen.  That screen is currently **really** basic / possibly doesn't exist.

**We need to build build out a detailed version of the Society & College Recommendations screen**

@greggmiller Can you please provide some information in this issue on what should be in this section?  Once that is done assign the issue to Marc Edwards.

@marcedwards Once greg has provided info, can you provide some design guidance in this issue in on how it should look.  Once this is done, can you label this issue as "Ready for Dev" so that one of the devs can pick it up.

**Comment by greggmiller** [comment]
_I think this should be retitled Additional Resources:_

_The intention is that this screen provides links to other commonly used resources for our department and critical care workers_

_Then Screen should have various subheadings/sections..._

_ The link can be built into the title_


**Western Health**

Novel Coronavirus Information
https://coronavirus.wh.org.au/

Western Health COVID-19 Daily Bulletin
https://coronavirus.wh.org.au/message-from-the-executive/

WH Anaesthesia Microsite
https://whcovid19.wixsite.com/covid19

WH ICU Microsite
https://whicu2020.wixsite.com/icuquickguide

**College and Society Links**

ANZCA COVID-19 daily updates
http://www.anzca.edu.au/front-page-news/covid-19-impact-on-anzca#

ANZICS COVID-19 Resources
https://www.anzics.com.au/coronavirus/

ASA COVID-19 response page
https://asa.org.au/covid-19-updates/?_zs=hmOdk

**Other resources**

https://coronavirus.jhu.edu/map.html
John Hopkins Inforgraphic map and tabulated daily update of COVID-19 cases worldwide


WHO
https://www.who.int/westernpacific/emergencies/covid-19

Indexed collection of articles on various aspects of anaesthesia and ICU for patients with COVID-19
https://www.covid19repository.com/


In terms of layout and design, @Western-Health-Covid19-Collaboration/designers will provide an excellent solution I am sure as I am sure it is a commonly encountered style of page.
It might be best as a list divided by subheaders. Perhaps a similar format to the cross-linking page would work well and save time?

In the interests of time, it might be best to have a very simple design with links, but I will leave that the discretion of @Mattro @marcedwards 😄

**Comment by cjmlgrto** [comment]
Here's a first pass. Decided to remove the links to the microsite since they're already in the screen before it ([Information](https://app.zeplin.io/project/5e7597a68651056664fb6e53/screen/5e75996c5f1e2a6dd0200cc1/)).

I've also made the titles more terse, but we have an opportunity to add subtitles, much like the links at the bottom of the list. Thoughts?

![Additional Resources](https://user-images.githubusercontent.com/1712450/78468798-6c8c8100-775e-11ea-853d-a16f470ca5aa.png)

**Comment by kimngyn** [comment]
Capital needed? To make it consistent? 

![8605B667-84C0-4E2D-B363-54682205C715](https://user-images.githubusercontent.com/42886400/78469373-eb37ed00-7763-11ea-97a1-e6b2cc6940c9.jpeg)

**Comment by lukesleeman** [comment]
> I've also made the titles more terse, but we have an opportunity to add subtitles, much like the links at the bottom of the list. Thoughts?

Yeah, I think subtitles might be nice, just describing what people will find on that page

**Comment by cjmlgrto** [comment]
Here's the updated design, with subtitles. [They're also available on Zeplin](https://app.zeplin.io/project/5e7597a68651056664fb6e53/screen/5e89b517c64be91fb3d24898/).

Keen to get a quick re-review @Western-Health-Covid19-Collaboration/medical + QA folks.

![Additional Resources](https://user-images.githubusercontent.com/1712450/79037147-e2d32c80-7c11-11ea-816b-172c11410cf7.png)

**Comment by greggmiller** [comment]
This looks great @cjmlgrto 👍 

Only copy change I would suggest is changing "Resource dashboard for critical care professionals" to "Resource dashboard for Intensive Care society"

Thanks for looking at this 🙌 😄

**Comment by cjmlgrto** [comment]
Easy! Made the change on Zeplin now for the devs. I'll remove the design tag since this should be ready for dev now! 🎉

**Comment by kimngyn** [comment]
This one looks really good! 😊

**Comment by sallychung** [comment]
✅ v1.0.146
