### ISSUE TITLE
Update home screen branding

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#48]
There are some new colours and branding from @marcedwards 

![image](https://user-images.githubusercontent.com/902252/77310610-b9ca2500-6d52-11ea-8ab5-a64de450bac6.png)

This needs to be integrated into the app

**Comment by lukesleeman** [comment]
@marcedwards Is it safe to say this is ready for dev?  If so tag as `ready for dev`

**Comment by marcedwards** [comment]
@lukesleeman Yep, but @Mattro and I are just sorting out that header image now. That’ll be needed.

**Comment by ericjiang97** [comment]
Will be happy to tackle this once this is ready

**Comment by lukesleeman** [comment]
☝️ just as soon as @marcedwards SVG is in, can we mark this ready for dev?  It will be great to get @ericjiang97 working on it :-)

Design looks so awesome, can't wait to see it in a build!

**Comment by marcedwards** [comment]
FYI: 

`/assets/images/main_logo.svg` = the logo.
`/assets/images/main_header.svg` = the background for the header.

**Comment by lukesleeman** [comment]
@ericjiang97 just to be super clear on when you need to start work on this:

Once PR #64 #65 and #66 are merged you will have everything you need to do this work.  Those PRs should be _very, very_ easy to review and merge as they are just adding some assets.  In fact I think @ericjiang97 you can review and merge them yourself, some already have ✅ 

Once those PR's are merged, please tag this issue as `Ready for dev` and get onto it right away 😁

**Comment by ericjiang97** [comment]
Resolved in #82
