### ISSUE TITLE
Embedded video to change in Putting on Personal Protective Equipment

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#53]
Hi Adam,

Minor (hopefully) amendment required. 
The video/link currently embedded in putting on PPE is the one for taking it off.

Could you switch to video from this link please: 
https://www.youtube.com/watch?v=jZyR0S8FKIY&feature=youtu.be

Let me know if any queries. Cheers!

**Comment by adamkoch** [comment]
Yep will do.

**Comment by adamkoch** [comment]
Fixed in #55
