### ISSUE TITLE
Documentation: Github 101

### ISSUE THREAD

**Issue by fmatosqg** [Western-Health-Covid19-Collaboration/wh_covid19_app#56]
> A potential obstacle may be Anaesthetists like myself being able to provide updates and resolve issues on GitHub. I am looking to involve a couple more colleagues on resolving these issues, however, we may be limited in our tech skills! 
> It might be that we look to the GDG slack community to create a 101 document (Resolving GitHub issues for dummies!) and in addition request a call/Zoom/email or other means of support as we learn these skills, in a period when we are already quite time-poor.
> If that does become the case I will reach out! Thank you for your consideration :raised_hands:

**Comment by fmatosqg** [comment]
I can't assign myself to this issue, but I'll be taking it and making a PR.

Comment here if you want to get assigned to it or collaborate etc.

**Comment by lukesleeman** [comment]
Oh, that would be super helpful.  Can you tag me when the PR comes through?  Love to see what is happening.

We have a `docs` directory in the repo as well as a wiki.  Hopefully one of those can help out.

**Comment by fmatosqg** [comment]
@lukesleeman @greggmiller  coming through https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/69

**Comment by lukesleeman** [comment]
Thanks to the excellent work by @fmatosqg we can now close this issue 🙌
