### ISSUE TITLE
Update Android Launcher Icon and App Name

### ISSUE THREAD

**Issue by workerbee22** [Western-Health-Covid19-Collaboration/wh_covid19_app#71]
Make the launcher icon an Android Adaptive Icon, so on devices like Google Pixel, Samsung devices etc. the icon is not just a white circle with the icon very small in the middle of the white circle.

**Comment by lukesleeman** [comment]
@workerbee22 do you want to tag this one either as `design` if we need assets or `ready for dev` if somebody can pick it up?

I've put this down to 3rd priority - The lack of adaptive icon makes me 😬😬😬 every time I see it, but ultimately the android icon isn't going matter much to the staff in the hospital once the flood of patients starts 😕

**Comment by workerbee22** [comment]
Yep all good and appropriate 👍

**Comment by workerbee22** [comment]
Note that designers have provided and assets in the app for Adaptive Icons already. So will just investigate why these are not being used atm.

**Comment by workerbee22** [comment]
Adding to scope of this change:

- icon title to be **WHAC19** which is the new working name for the app.

**Comment by workerbee22** [comment]
@Mattro Mentioned working on a new icon. Either way, I've been held up. So someone else can get to this once we check if there will be a new product icon with @Mattro

**Comment by workerbee22** [comment]
Waiting on new assets and/or new icon from designers before we do this.

**Comment by lukesleeman** [comment]
Good call - I've pulled off the ready for dev label.

**Comment by workerbee22** [comment]
PR https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/pull/184

Fixes the icon title for iOS and Android. But still need to fix Android Adaptive icon, for which waiting for new assets/icon.

**Comment by lukesleeman** [comment]
I'm assigning @marcedwards to this as well to provide his ✨ new icon ✨

**Comment by workerbee22** [comment]
@lukesleeman We'll need a flutter dev to do this on both sides, but we need the assets from @marcedwards

**Comment by marcedwards** [comment]
@workerbee22 I’m working on the new icon, and will post to the Slack team when it’s very close to being done, and then update all the assets.

**Comment by workerbee22** [comment]
@marcedwards Can't wait to see it, but no massive rush today.
