### ISSUE TITLE
Update PPE Techniques page buttons

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#72]
The PPE page currently looks like this:

![](https://user-images.githubusercontent.com/902252/77302471-79b07580-6d45-11ea-985e-dc63f4a4b326.png)

It needs to look like this:

![image](https://user-images.githubusercontent.com/902252/77474437-35b79080-6e6b-11ea-9442-6c51aa919a2c.png)

The updated designs are in Zeplin.  Things I can see:

- There are two buttons for Taking off PPE
- The taking off buttons have different colours
- The title of the page needs to change
- A phone button in the top right - This should work the same as the one in the "Your welfare" page - just direct out to a webpage

**Comment by lukesleeman** [comment]
@Western-Health-Covid19-Collaboration/flutter-devs who can pick this one up?  Its ready for dev and a great 1st issue for somebody to attack :-)

**Comment by adamkoch** [comment]
I can do this quickly now if nobody else is?

**Comment by lukesleeman** [comment]
> I can do this quickly now if nobody else is?

I think @kimngyn and @ericjiang97 are on it at the moment

**Comment by adamkoch** [comment]
Ok cool 👍
