### ISSUE TITLE
Rough, ugly version of the disclaimer screen

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#73]
We need to build a really quick and ugly version of the disclaimer screen.  The nice beautiful ✨ well designed ✨ version of this screen is being tracked as part of #47  .  But its going to be a while until the designers get around to doing it.

In the meantime we have the copy and it would be great to just do a rough version so we have _something_ in the application.

Here is the copy that needs to go on it (taken from greg's comment on #47 )

> This app is designed to be used by Anaesthetic and Critical Care doctors at Western Health who are caring for patients during the COVID-19 Pandemic. The guidelines, protocols and advice within this app are designed to educate staff and suggest recommended management of patients with COVID-19. The recommendations within this application do not indicate an exclusive course of action as the results must be contextualised to the patient at hand and variations may be appropriate.
The authors of this app have made efforts to ensure the information is up to date, but encourage users to confirm the indicated therapy with existing guidelines. The responsibility is on you, the treating physician, to ensure the correct therapy is being used.
>
>The authors accept no responsibility for any information perceived as misleading or the success of any treatment regimen detailed in the guidelines.
The app is made available on the understanding that Western Health and its employees shall have no liability (including liability by reason of negligence) to the users for any loss, damage, cost or expense incurred or arising by reason of any person using or relying on the information and whether caused by reason of any error, negligent act, omission or misinterpretation in the app or otherwise.
>
>The Western Health trademark and app cannot be copied, modified, reproduced, published, uploaded, distributed or posted without the prior written consent of Western Health.
>
>You must agree to accept these terms and conditions before proceeding to use the app.

Based on "The plan" in the readme.md there are two places the disclaimer needs to go into the app.   When the user first opens the app, before they hit the main screen, they have to click some kind of "I accept"

![image](https://user-images.githubusercontent.com/902252/77476307-71a02500-6e6e-11ea-8164-20dcefdca0b3.png)

Then they can get to the disclaimer any time from the info and resources screen

![image](https://user-images.githubusercontent.com/902252/77476350-87ade580-6e6e-11ea-859e-4f36c3c8af65.png)

**Comment by lukesleeman** [comment]
@adamkoch given your design background, perhaps this is something you could pick up today and implement in a way that is not _too ugly_ ?

Its going to be a few days until we have actual proper designs from the design team (being tracked in issue #47 ) so I'm keen we just do some "developer design" and get this into the app ASAP.  We can always come and polish it in 3 or 4 days time once the finalised designs get produced.

In the meantime just use your best judgment on how it should look

**Comment by adamkoch** [comment]
@lukesleeman sorry I am of action during the day now as have some urgent work stuff to attend to. i will try and spend some time in the evenings after kids asleep but i would recommend another dev pick it up if possible for now

**Comment by lukesleeman** [comment]
@Western-Health-Covid19-Collaboration/flutter-devs  - who can pick this issue up?  Its ready for dev to go 😁

**Comment by alessandrofavero** [comment]
I can pick this one up after work @lukesleeman

**Comment by lukesleeman** [comment]
Thats great!  If anybody else is avalible to tackle it even soon just assign the issue to yourself and start work 😁. If nobody has taken it by the time you get off work Alessandro, you can grab it 👍

Luke

**Comment by lukesleeman** [comment]
Based on https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/47#issuecomment-603532832

This screen should ahve an "I accept" button
It only needs to pop up the first time they enter the app.  Once they accept it, they don;t see it again on app load.  Of course you can access any time through the info screen :+1:

**Comment by alessandrofavero** [comment]
I'm picking this up now

**Comment by marcedwards** [comment]
@alessandrofavero Awesome! There’s some more info on the design here: https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/issues/47

**Comment by alessandrofavero** [comment]
@marcedwards @lukesleeman I have a first one working with:
- first-time view
- an agree button
- changes if seen from the info page (no button + back button on App bar)
![disclaimer_first_time](https://user-images.githubusercontent.com/43284065/77513117-7f829400-6ec8-11ea-9d6d-e8f06863a0d9.gif)

![disclaimer_accepted](https://user-images.githubusercontent.com/43284065/77513142-8e694680-6ec8-11ea-9d3c-275b659850d4.gif)

**Comment by alessandrofavero** [comment]
> @alessandrofavero Awesome! There’s some more info on the design here: #47

I'm looking at it now!

**Comment by lukesleeman** [comment]
Wow!  Amazing work, you are all going sooooo fast!  

TBH, when I set things up this morning I didn't think the designs would be done for a few days.  It sounds like they are almost complete!

I'm going to actually close this issue and just get @alessandrofavero working on the final version ( #47 ) , given we have nice designs.

Great job everybody 👏
