### ISSUE TITLE
Change title "Intubation" to "Airway"

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#76]
Another important aspect of Airway management is Extubation (removing the breathing tube). 
Apologies but  consideration of extubation was slightly neglected as we were all focusing on intubation (often its weeks later in COVID patients that they require extubation).

With this in mind, we should change title to Airway (which will cover both intubation and extubation).
Is this easy enough to go straight to devs or should design look?

Another aspect of this will be we would like a subsection in "Airway" called "Extubation"

**Comment by marcedwards** [comment]
I think this is entirely your call, and it can go straight to a developer to change.

The only design consideration is to make sure we have updated design docs (hi, @Mattro).

**Comment by Mattro** [comment]
Can do. Easy change.

**Comment by greggmiller** [comment]
Thanks Marc, ready for dev it is!

**Comment by greggmiller** [comment]
Is it easy @Mattro @marcedwards to add a subsection within Airway called extubation? It can be lowest in the priority of the section.

**Comment by Mattro** [comment]
As a sub-heading, or as a button?

Happy to add it. Can you hook me up with some content to put there?

**Comment by Mattro** [comment]
![image](https://user-images.githubusercontent.com/1920449/77507312-4fcd8f00-6ebc-11ea-80f8-cad4648e2892.png)

**Zeplin**
Web link: https://zpl.io/2GlWe5J
App link: zpl://screen?pid=5e7597a68651056664fb6e53&sid=5e75998deff8336f22e350ed

**Comment by greggmiller** [comment]
That's perfect @Mattro

**Comment by joshcase** [comment]
Fixed in #91

**Comment by lukesleeman** [comment]
Nice!
