### ISSUE TITLE
Remove unneeded images for PPE donning and doffing

### ISSUE THREAD

**Issue by marcedwards** [Western-Health-Covid19-Collaboration/wh_covid19_app#77]
There’s four images that we no longer need. I’m creating this as an issue rather than doing it myself, in case there’s places in the code that reference them that also need to be edited (developer assistance required!).

These can all be deleted:
```
/assets/images/mask_on.jpg
/assets/images/gown_on.jpg
/assets/images/gloves_on.jpg
/assets/images/eye_protection_on.jpg
```

**Comment by lukesleeman** [comment]
@marcedwards  - Thanks for the heads up!  I've tagged this one `Read for dev` :-) !  In future feel free to add the `Read for dev` label to issues that are ready to go 👍 🏎🏎
