### ISSUE TITLE
Add in a code of conduct

### ISSUE THREAD

**Issue by lukesleeman** [Western-Health-Covid19-Collaboration/wh_covid19_app#86]
Most open source projects have a code of conduct.  I started things so quickly, I didn't have time to look for a good one and add it to the repo.

Somebody needs to have a look at open source code of conducts, find a commonly used, suitable code, and add it to the `/docs` directory.  The readme.md should be updated to point at it

**Comment by lukesleeman** [comment]
`@Poornima Sivakumar` from the GDG slack will be working on this one :-)

**Comment by domesticmouse** [comment]
[Here's ours](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md), for reference.

**Comment by poornima2796** [comment]
Thanks @domesticmouse !

**Comment by lukesleeman** [comment]
This is now merged, great job @poornima2796 ! 🙌

**Comment by poornima2796** [comment]
Thanks @lukesleeman ! :)
