### ISSUE TITLE
Section for Proning

### ISSUE THREAD

**Issue by benblackman** [Western-Health-Covid19-Collaboration/wh_covid19_app#88]
Could we consider a section with checklist/steps for proning? 

ICU do it a bit differently from us in theatre and theatre staff cross-skilling will need to be on the same page. This is how they do it https://www.youtube.com/watch?v=YFrA1cCuDnY&feature=youtu.be

Not sure whether better as a subsection of #42 ICU > General Care or a subsection in #40 ICU > Ventilation > Adjuncts, but it would lend itself well to a checklist for preparation then a list of steps displayed in the App.

@greggmiller feel free to bin this issue if it's already been covered and I missed it, or if you think it's adding too much content. Any thoughts @galtaforce ?

**Comment by galtaforce** [comment]
I think it would be a good idea to include a video. We just need to have an "approved" method of proning.

**Comment by greggmiller** [comment]
Excellent point Ben.
I think we should have this video link in. 
We should include it in ICU general section and JMS section probably?
I think listview would be good for both of these sections. I will put this in #42 and #43

My understanding is that the video content is not embedded in the app so won't take up extra size but instead plays the link through an inbuilt media/youtube player. So extra videos should not be too much of a problem.  @adamkoch did the previous work on this for PPE so can probably confirm this?

**Comment by greggmiller** [comment]
[Prone Checklist September 2018.pptx](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/files/4384430/Prone.Checklist.September.2018.pptx)

I've just had this checklist sent through from ICU. We will add this in at some point as an infographic.

**Comment by benblackman** [comment]
Sounds great. I suspect it may need a bit of reformatting for a small screen but seems very comprehensive.

**Comment by adamkoch** [comment]
> My understanding is that the video content is not embedded in the app so won't take up extra size but instead plays the link through an inbuilt media/youtube player. So extra videos should not be too much of a problem. @adamkoch did the previous work on this for PPE so can probably confirm this?

Actually I ended up just embedding lower-res versions inside the binary ([here](https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/tree/master/assets/videos)). We can switch it to embedded videos if needed.

**Comment by lukesleeman** [comment]
I'm closing this issue - the Proning section is complete, and the video is tracked by another issue
