### ISSUE TITLE
Add design system colours to style.dart

### ISSUE THREAD

**Issue by marcedwards** [Western-Health-Covid19-Collaboration/wh_covid19_app#9]
Here’s an expanded colour palette for the app, that should cover some potential future colours we may need. It’s based on Matt’s original work, with the **500** weight colours being the primaries.

![colours](https://user-images.githubusercontent.com/1121547/77247077-984d3880-6c81-11ea-9e81-96a172bc960c.png)

Here’s the colours as Dart code:

```
Color green-50 = const Color.fromRGBO(214.0, 233.0, 191.0, 1.0);
Color green-500 = const Color.fromRGBO(173.0, 211.0, 127.0, 1.0);
Color green-600 = const Color.fromRGBO(145.0, 184.0, 112.0, 1.0);
Color green-800 = const Color.fromRGBO(75.0, 117.0, 74.0, 1.0);
Color green-900 = const Color.fromRGBO(34.0, 77.0, 52.0, 1.0);
Color blue-50 = const Color.fromRGBO(181.0, 226.0, 239.0, 1.0);
Color blue-500 = const Color.fromRGBO(106.0, 197.0, 222.0, 1.0);
Color blue-600 = const Color.fromRGBO(95.0, 168.0, 196.0, 1.0);
Color blue-800 = const Color.fromRGBO(68.0, 94.0, 131.0, 1.0);
Color blue-900 = const Color.fromRGBO(52.0, 50.0, 92.0, 1.0);
Color purple-50 = const Color.fromRGBO(197.0, 168.0, 200.0, 1.0);
Color purple-500 = const Color.fromRGBO(139.0, 81.0, 144.0, 1.0);
Color purple-600 = const Color.fromRGBO(120.0, 72.0, 127.0, 1.0);
Color purple-800 = const Color.fromRGBO(74.0, 50.0, 86.0, 1.0);
Color purple-900 = const Color.fromRGBO(46.0, 37.0, 61.0, 1.0);
Color grey-50 = const Color.fromRGBO(255.0, 255.0, 255.0, 1.0);
Color grey-500 = const Color.fromRGBO(236.0, 243.0, 240.0, 1.0);
Color grey-600 = const Color.fromRGBO(212.0, 220.0, 216.0, 1.0);
Color grey-800 = const Color.fromRGBO(151.0, 162.0, 157.0, 1.0);
Color grey-900 = const Color.fromRGBO(115.0, 128.0, 122.0, 1.0);
```

I (or anyone) can add these to `style.dart`, but I have a couple of questions prior to doing so:

- Are the constant names good as is? Feel free to let me know if there’s style changes you’d like.
- Is there anything else about the code that requires changes?

**Comment by rockgecko-development** [comment]
Hey Marc,
1. No, `-` is invalid. Go with `grey_900` or `grey900`
2. the first 3 params in the fromRGBO are ints. Opacity is double. So you have to remove the decimal `.0` from those.

I actually had the same issue last week when a designer sent me a generated dart snippet via adobe xd, generating code that doesn't compile. Must be an adobe thing :)

**Comment by marcedwards** [comment]
Thanks for the feedback! Here’s the updated code:

```
Color green50 = const Color.fromRGBO(214, 233, 191, 1.0);
Color green500 = const Color.fromRGBO(173, 211, 127, 1.0);
Color green600 = const Color.fromRGBO(145, 184, 112, 1.0);
Color green800 = const Color.fromRGBO(75, 117, 74, 1.0);
Color green900 = const Color.fromRGBO(34, 77, 52, 1.0);
Color blue50 = const Color.fromRGBO(181, 226, 239, 1.0);
Color blue500 = const Color.fromRGBO(106, 197, 222, 1.0);
Color blue600 = const Color.fromRGBO(95, 168, 196, 1.0);
Color blue800 = const Color.fromRGBO(68, 94, 131, 1.0);
Color blue900 = const Color.fromRGBO(52, 50, 92, 1.0);
Color purple50 = const Color.fromRGBO(197, 168, 200, 1.0);
Color purple500 = const Color.fromRGBO(139, 81, 144, 1.0);
Color purple600 = const Color.fromRGBO(120, 72, 127, 1.0);
Color purple800 = const Color.fromRGBO(74, 50, 86, 1.0);
Color purple900 = const Color.fromRGBO(46, 37, 61, 1.0);
Color grey50 = const Color.fromRGBO(255, 255, 255, 1.0);
Color grey500 = const Color.fromRGBO(236, 243, 240, 1.0);
Color grey600 = const Color.fromRGBO(212, 220, 216, 1.0);
Color grey800 = const Color.fromRGBO(151, 162, 157, 1.0);
Color grey900 = const Color.fromRGBO(115, 128, 122, 1.0);
```

**Comment by rockgecko-development** [comment]
LGTM - but I'm only lurking here until tomorrow night / Tuesday :)

**Comment by rockgecko-development** [comment]
Oh, with the 50/500/600/800/900, this is more what Flutter/Material calls _swatch_, right? If  you define 10 of them, they can be defined like this:
````
Color bluePrimary = Color.fromRGBO(106, 197, 222, 1.0);
static const MaterialColor blueSwatch = MaterialColor(
    bluePrimary,
    <int, Color>{
       50: Color.fromRGBO(181, 226, 239, 1.0),
      100: //TODO,
      200: //TODO,
      300: //TODO,
      400: //TODO,
      500: bluePrimary,
      600: Color.fromRGBO(95, 168, 196, 1.0),
      700: //TODO,
      800: Color.fromRGBO(68, 94, 131, 1.0),
      900: Color.fromRGBO(52, 50, 92, 1.0),
    },
  );
````
And then referenced like
`var color = blueSwatch[600]` etc

If anyone has experience making custom `swatch`es, we could go this route, but otherwise it's probably not necessary, it's fine to reference each color separately.

**Comment by workerbee22** [comment]
I'm assuming we'll hold off on themeing for now? 

Also is it worth in `style.dart` to use an abstract class? So then in code everything is referenced as `Styles.bluePrimary` ? Just makes the code a little more readable, thoughts?

**Comment by marcedwards** [comment]
I’m happy and comfortable with whatever works. It’s no trouble for me to get the swatch stuff happening.

**Comment by marcedwards** [comment]
Actually, maybe it’s a distraction for now. Maybe we just stick with the flat constants for now. If it’s okay, I think I will keep adding design system stuff as Issues, and let developers move it into the code?

**Comment by marcedwards** [comment]
![colours-checkerboard](https://user-images.githubusercontent.com/1121547/77279892-0132c000-6d17-11ea-8912-5398ff4b89c2.png)

Ok, here are the final (for now) colours that can be put into `style.dart`. I also have some notes on usage below.

```
Color green50 = const Color.fromRGBO(214, 233, 191, 1.0);
Color green500 = const Color.fromRGBO(173, 211, 127, 1.0);
Color green600 = const Color.fromRGBO(145, 184, 112, 1.0);
Color green800 = const Color.fromRGBO(75, 117, 74, 1.0);
Color green900 = const Color.fromRGBO(34, 77, 52, 1.0);
Color blue50 = const Color.fromRGBO(181, 226, 239, 1.0);
Color blue500 = const Color.fromRGBO(106, 197, 222, 1.0);
Color blue600 = const Color.fromRGBO(95, 168, 196, 1.0);
Color blue800 = const Color.fromRGBO(68, 94, 131, 1.0);
Color blue900 = const Color.fromRGBO(52, 50, 92, 1.0);
Color purple50 = const Color.fromRGBO(197, 168, 200, 1.0);
Color purple500 = const Color.fromRGBO(139, 81, 144, 1.0);
Color purple600 = const Color.fromRGBO(120, 72, 127, 1.0);
Color purple800 = const Color.fromRGBO(74, 50, 86, 1.0);
Color purple900 = const Color.fromRGBO(46, 37, 61, 1.0);
Color grey50 = const Color.fromRGBO(255, 255, 255, 1.0);
Color grey500 = const Color.fromRGBO(236, 243, 240, 1.0);
Color grey600 = const Color.fromRGBO(175, 185, 181, 1.0);
Color grey800 = const Color.fromRGBO(49, 52, 51, 1.0);
Color grey900 = const Color.fromRGBO(19, 20, 20, 1.0);
Color blackAlpha50 = const Color.fromRGBO(0, 0, 0, 0.2);
Color blackAlpha500 = const Color.fromRGBO(0, 0, 0, 0.4);
Color blackAlpha600 = const Color.fromRGBO(0, 0, 0, 0.6);
Color blackAlpha800 = const Color.fromRGBO(0, 0, 0, 0.8);
Color blackAlpha900 = const Color.fromRGBO(0, 0, 0, 1.0);
```

The intention is for all our colour needs to be covered by the constants above. If we’re missing something, we can add it as a constant, so we have a good handle on what’s being used and so they can be easily modified later.

### Main background and text

App Background: `grey500`
Major text (headings etc): `blackAlpha900`
Minor text (body text): `blackAlpha600`

### Section colours

The various sections of the app are denoted by their own colour, to make grouping easier to see.

Look After Yourself: `grey50`
Intubation: `green500`
ICU for new starters: `blue500`
If we need another section: `purple500`

**Comment by adamkoch** [comment]
@marcedwards is there a few named colors we can give to some of these shades? kid of like what I see here:
https://app.zeplin.io/project/5e7597a68651056664fb6e53/styleguide/colors?cid=5e7599bbeff8336f22e3516f

eg.
Color backgroundGreen = green500;
Color appBackground = grey500;
etc.

It's better if we can use the named colors in the code as much as possible so we keep re-using the same ones over and over (otherwise one background may end up with green500 and another with green600)

**Comment by adamkoch** [comment]
I kind of started this here but will migrate over to your colors in next PR:
https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/6a7c261e6fe732c319f1b6ad3a4de16482dae9b8/lib/style.dart#L9

**Comment by marcedwards** [comment]
Thanks! I agree, and I think your proposed solution is good.

**Comment by lukesleeman** [comment]
Awesome!  Now this is merged, can we close this issue?  Or is there more work?

**Comment by adamkoch** [comment]
There's still a bit of work to be done around the colors/styles but we can close this one and follow up separately.
