### ISSUE TITLE
Changes to wording on home screen and on app hierarchy map

### ISSUE THREAD

**Issue by greggmiller** [Western-Health-Covid19-Collaboration/wh_covid19_app#96]
After several discussions throughout today with @Western-Health-Covid19-Collaboration/medical  and others.

**_Changes are:_**

**ICU** 
**Ventilation** remains
**General care** change to **Daily Round**
Tips for **Junior staff**  change to **Cross-skilling**

(Cross-skilling is the likely event that many medics will be working in roles outwith their usual responsibilities during the surge of the pandemic)

 **Airway** 

Change **Algorithm** to **Infographics**

**Info and resources** 
Add **WH Novel Coronavirus information** (previously on hierarchy as Google Covid News Feed) (this is only a link to https://coronavirus.wh.org.au/# so will be fit for devs when in)

On info and resources add **Acknowledgements and references** section

@Western-Health-Covid19-Collaboration/designers 
@Western-Health-Covid19-Collaboration/medical 

I have put as number 1 priority as I think changing this is a quick fix that may be ready for devs depending on @Mattro and  @marc thoughts? It also impacts quite significantly on the understanding and navigation of the app.

I think this aligns with the discussions from today but please feel free to comment/query.

**Comment by lukesleeman** [comment]
Yep, I think either @Mattro or @marcedwards Will need to update the `Main` and `Flow Diagram` screens in zeplin, with these changes, then we should be good to go.

**Comment by Mattro** [comment]
I’ll knock this one off in the next hour.

**Comment by lukesleeman** [comment]
Amazing!  🙌

Post some pics and move to ‘read for dev’ when you get it done 🙂

Luke

**Comment by Mattro** [comment]
This is ready to go @lukesleeman

**Comment by greggmiller** [comment]
Awesome!

@Western-Health-Covid19-Collaboration/flutter-devs 
Over to you! Thanks!

**Comment by greggmiller** [comment]
@Mattro  Sorry after discussing this I’ve realised it might be better if Intubation and Extubation were laid out symmetrically. They are essentially equal and opposite actions (tube goes in, tube comes out!). So it will be more intuitive and functional for the user if the architecture is  the same:

Airway                        -->  Intubation --> Steps, checklist, infographics
                                   --> Extubation --> Steps, checklist, infographics

**Comment by greggmiller** [comment]
Can I retract previous comment, (unless @Western-Health-Covid19-Collaboration/designers @Mattro  have been working on it in last few hours).

It is good for the first iteration if extubation is one box. 

I am removing design label and saying ready for @Western-Health-Covid19-Collaboration/flutter-devs

**Comment by lukesleeman** [comment]
Awesome!  This is how its looking now:

![Main](https://user-images.githubusercontent.com/902252/77729716-77a32b00-7053-11ea-8862-22d35e716814.png)

Can one of our @Western-Health-Covid19-Collaboration/flutter-devs pick it up and implement?

Don't forget there are a few changes to the info screen as well.  See gregs description on this issue :-)

**Comment by yimingc2** [comment]
> **Info and resources**
> Add **WH Novel Coronavirus information** (previously on hierarchy as Google Covid News Feed) (this is only a link to https://coronavirus.wh.org.au/# so will be fit for devs when in)

Hi @greggmiller @lukesleeman , I don't see **WH Novel Coronavirus information** section in the design. Was there a **Google Covid News Feed** section in the info page? Thanks

![example](https://user-images.githubusercontent.com/14011195/77817213-6161a180-711d-11ea-9304-3fb54376dea3.gif)

I added this section like that. What do you think?

**Comment by greggmiller** [comment]
Hi @yimingc2, on information architecture https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/master/README.md there was, but you are right I don't think it made it on to information screen. 

Is it easy enough to add a "WH COVID-19 information" section on the information page? @Western-Health-Covid19-Collaboration/designers 

The swipe works well @yimingc2  but would need to be signposted 😄

**Comment by yimingc2** [comment]
> Hi @yimingc2, on information architecture https://github.com/Western-Health-Covid19-Collaboration/wh_covid19_app/blob/master/README.md there was, but you are right I don't think it made it on to information screen.
> 
> Is it easy enough to add a "WH COVID-19 information" section on the information page? @Western-Health-Covid19-Collaboration/designers
> 
> The swipe works well @yimingc2 but would need to be signposted 😄

In a device with a smaller screen, say iPhone SE, the title of the sections can be cut off as well.

![Simulator Screen Shot - iPhone SE - 2020-03-28 at 21 12 09](https://user-images.githubusercontent.com/14011195/77820789-ed34f700-7138-11ea-933f-bec1288d8d24.png)

Since we don't have much time, maybe we don't need to spend too much time on this if there's no easy fix.

**Comment by workerbee22** [comment]
@yimingc2 There is an easy fix, update `ReusableCard` to ad an `Expanded` widget and a `Wrap` widget or or `Flexible`

**Comment by lukesleeman** [comment]
👋 Great work on this @yimingc2 

We have some updated designs from the design team.  The home page now has some updates to look like this:

![Main (scrolled)](https://user-images.githubusercontent.com/902252/77846313-086b3980-7201-11ea-838f-816b614964a0.png)

As far as I know its just changes to the titles in the "Airway" section

@yimingc2 Are you able to update?

**Comment by yimingc2** [comment]
> 👋 Great work on this @yimingc2
> 
> We have some updated designs from the design team. The home page now has some updates to look like this:
> 
> ![Main (scrolled)](https://user-images.githubusercontent.com/902252/77846313-086b3980-7201-11ea-838f-816b614964a0.png)
> 
> As far as I know its just changes to the titles in the "Airway" section
> 
> @yimingc2 Are you able to update?

Sure thing! Will do

**Comment by greggmiller** [comment]
This looks great on the current build now 😄 Thanks @yimingc2 👍 

I have one minor change request. 
Could "Extubation" be changed to "Extubation guide" and the subtext under extubation be changed from "infographic" to "step by step guide" please?
This is to match the intubation guide.  
This is ready for @Western-Health-Covid19-Collaboration/flutter-devs.
👍

**Comment by yimingc2** [comment]
> This looks great on the current build now 😄 Thanks @yimingc2 👍
> 
> I have one minor change request.
> Could "Extubation" be changed to "Extubation guide" and the subtext under extubation be changed from "infographic" to "step by step guide" please?
> This is to match the intubation guide.
> This is ready for @Western-Health-Covid19-Collaboration/flutter-devs.
> 👍

Hi Greg, sorry the PR related to this issue is already merged. I should close this one. We can create another issue for the further wording changes. BTW maybe the design in Zeplin should update for the new changes first in case some misundertanding.

**Comment by lukesleeman** [comment]
> > This looks great on the current build now 😄 Thanks @yimingc2 👍
> > I have one minor change request.
> > Could "Extubation" be changed to "Extubation guide" and the subtext under extubation be changed from "infographic" to "step by step guide" please?
> > This is to match the intubation guide.
> > This is ready for @Western-Health-Covid19-Collaboration/flutter-devs.
> > 👍
> 
> Hi Greg, sorry the PR related to this issue is already merged. I should close this one. We can create another issue for the further wording changes. BTW maybe the design in Zeplin should update for the new changes first in case some misundertanding.

Huh, just checked the app and its done.  I think @marcedwards took care of it 😁 

Great job everybody 🙌

**Comment by greggmiller** [comment]
Yeah @marcedwards 🙌  did it and let me know on Slack. Thanks all 😃
